import {initAds,maybeInterstitial,showRewarded,adsAvailable,bannerOnScreens} from './arcade-ads.js';
const THEMES=[['Original',0],['Glacier',30],['Solar',100],['Aurora',250]];
export function mount({S,rocket,draw,icon}){
 const title=rocket?'Rocket Thread':"Don't Touch Red",key=rocket?'rocketthread':'donttouchred',$=id=>document.getElementById(id);
 let saved={best:0,total:0,plays:0,skin:0,sound:true,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches,daily:{}};
 let saveIssue=false;
 try{const raw=JSON.parse(localStorage.getItem(key+'.v2')||'{}');for(const k of ['best','total','plays','skin'])if(Number.isFinite(raw[k])&&raw[k]>=0)saved[k]=Math.floor(raw[k]);for(const k of ['sound','reduced'])if(typeof raw[k]==='boolean')saved[k]=raw[k];if(raw.daily&&typeof raw.daily==='object')saved.daily=Object.fromEntries(Object.entries(raw.daily).filter(([k,v])=>/^\d{4}-\d{2}-\d{2}$/.test(k)&&Number.isFinite(v)&&v>=0).slice(-14));saved.best=Math.max(saved.best,Number(localStorage.getItem(key+'.best'))||0);if(!THEMES[saved.skin]||saved.total<THEMES[saved.skin][1])saved.skin=0;}catch{saveIssue=true;}
 const persist=()=>{try{localStorage.setItem(key+'.v2',JSON.stringify(saved));saveIssue=false;}catch{saveIssue=true;} $('save-note').textContent=saveIssue?'Progress cannot be saved on this device.':'';};
 const day=()=>new Date().toISOString().slice(0,10),track=(event,data={})=>window.arcade?.track?.(event,{mode,...data});
 let run=null,screen='home',mode='endless',runDay='',hold=false,tap=0,acc=0,last=performance.now(),trail=[],effects=[],resultDelay=0,earned=0,bonusUsed=false,busy=false,returnTo='home',context=null;
 const canvas=$('c'),ctx=canvas.getContext('2d');let width=0,height=0;
 function resize(){width=innerWidth;height=innerHeight;const d=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(width*d);canvas.height=Math.round(height*d);canvas.style.width=width+'px';canvas.style.height=height+'px';ctx.setTransform(d,0,0,d,0,0);}
 addEventListener('resize',resize);resize();
 function sound(kind){if(!saved.sound)return;try{context??=new (window.AudioContext||window.webkitAudioContext)();void context.resume();const o=context.createOscillator(),g=context.createGain();o.connect(g);g.connect(context.destination);o.type=kind==='fail'?'triangle':'sine';const at=context.currentTime;o.frequency.setValueAtTime(kind==='fail'?160:kind==='gold'?880:kind==='bounce'?260:520,at);o.frequency.exponentialRampToValueAtTime(kind==='fail'?40:kind==='gold'?1320:380,at+.12);g.gain.setValueAtTime(.045,at);g.gain.exponentialRampToValueAtTime(.001,at+.18);o.start();o.stop(at+.2);}catch{ $('save-note').textContent='Sound is unavailable in this browser.';}}
 function refresh(){ $('best').textContent=saved.best;$('daily-best').textContent=saved.daily[day()]??'—';$('bank').textContent=saved.total;$('daily-date').textContent=day()+' · same course all day';$('sound').checked=saved.sound;$('motion').checked=saved.reduced;
 $('looks').replaceChildren(...THEMES.map(([name,need],i)=>{const b=document.createElement('button');b.className='look'+(i===saved.skin?' selected':'');b.setAttribute('aria-pressed',String(i===saved.skin));b.disabled=saved.total<need;b.innerHTML=`<i style="background:${['#ff7850','#66dbff','#ffc354','#b6ff89'][i]}"></i><span>${name}</span><small>${saved.total>=need?'Unlocked':need+' sparks'}</small>`;b.onclick=()=>{saved.skin=i;persist();refresh();};return b;}));const next=THEMES.find(x=>x[1]>saved.total);$('next').textContent=next?`${next[1]-saved.total} sparks to ${next[0]}`:'Every look unlocked. Chase your best.';$('unlock-progress').max=next?.[1]||250;$('unlock-progress').value=saved.total; $('save-note').textContent=saveIssue?'Progress cannot be saved on this device.':'';}
 function show(s){screen=s;document.body.dataset.screen=s;for(const p of document.querySelectorAll('[data-panel]'))p.hidden=p.dataset.panel!==s;$('hud').hidden=!['play','paused'].includes(s);$('pause').hidden=s!=='play';hold=false;tap=0;acc=0;last=performance.now();refresh();if(s!=='play')requestAnimationFrame(()=>document.querySelector(`[data-panel="${s}"] button`)?.focus({preventScroll:true}));}
 function fullscreen(){if(!document.fullscreenElement&&document.documentElement.requestFullscreen)document.documentElement.requestFullscreen().catch(()=>{/* iOS and embedded browsers use the full viewport. */});}
 function start(which=mode){if(busy)return;mode=which;runDay=day();const seed=mode==='daily'?S.dailySeed(runDay):(crypto.getRandomValues(new Uint32Array(1))[0]);run=rocket?S.newRun(seed):S.newGame(seed);trail=[];effects=[];earned=0;bonusUsed=false;resultDelay=0;show('play');fullscreen();sound('start');track('level_start',{seed});$('mode-label').textContent=mode==='daily'?'DAILY · '+runDay:'ENDLESS';canvas.focus();}
 function pause(){if(screen==='play'&&run&&!run.over){show('paused');track('pause');}}
 async function finish(){if(screen!=='play')return;show('result');saved.plays++;const old=mode==='daily'?(saved.daily[runDay]||0):saved.best;if(mode==='daily')saved.daily[runDay]=Math.max(old,run.score);else saved.best=Math.max(saved.best,run.score);earned=run.t>=2?Math.max(1,Math.floor(run.score/3)+(rocket?run.cells:run.golds_taken)*2):0;saved.total+=earned;persist();refresh();$('result-score').textContent=run.score;$('result-title').textContent=run.score>old?'Personal best!':rocket?'One more flight?':'One more bounce?';$('result-detail').textContent=rocket?`${Math.floor(run.y)}m climbed · ${run.cells} cells · ${run.nearMisses} near misses`:`${run.t.toFixed(1)} seconds · ${run.golds_taken} gold collected`;$('earned').textContent=`+${earned} sparks earned`;$('reward').hidden=!earned||!adsAvailable();$('reward').disabled=false;$('reward-note').textContent='';track('level_fail',{score:run.score,seconds:Math.floor(run.t)});busy=true;for(const b of document.querySelectorAll('[data-panel="result"] button'))b.disabled=true;try{await maybeInterstitial();}finally{busy=false;for(const b of document.querySelectorAll('[data-panel="result"] button'))b.disabled=false;}}
 $('go').onclick=()=>start('endless');$('daily').onclick=()=>start('daily');$('retry').onclick=()=>start();$('home').onclick=()=>{if(!busy){run=null;show('home');}};$('pause').onclick=pause;$('resume').onclick=()=>{show('play');canvas.focus();};$('quit').onclick=()=>{run=null;show('home');};
 for(const b of document.querySelectorAll('[data-settings]'))b.onclick=()=>{returnTo=screen;show('settings');};$('settings-back').onclick=()=>show(returnTo);$('sound').onchange=()=>{saved.sound=$('sound').checked;persist();sound('start');};$('motion').onchange=()=>{saved.reduced=$('motion').checked;persist();};
 $('reward').onclick=async()=>{if(busy||bonusUsed||!earned)return;busy=true;$('reward').disabled=true;for(const id of ['retry','home'])$(id).disabled=true;try{const r=await showRewarded();if(r.rewarded){bonusUsed=true;saved.total+=earned;persist();refresh();$('earned').textContent=`+${earned*2} sparks earned`;$('reward').hidden=true;$('reward-note').textContent='Bonus collected. Your score stays the same.';track('reward',{reward:'cosmetic_sparks',amount:earned});}else $('reward-note').textContent=r.reason||'No ad available. Try again later.';}finally{busy=false;$('reward').disabled=false;for(const id of ['retry','home'])$(id).disabled=false;}};
 canvas.addEventListener('pointerdown',e=>{if(screen!=='play'||run.over)return;e.preventDefault();canvas.setPointerCapture(e.pointerId);hold=true;tap=e.clientX<width/2?-1:1;});const release=()=>{hold=false;};canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',release);canvas.addEventListener('lostpointercapture',release);
 addEventListener('keydown',e=>{if(e.code==='Escape'){e.preventDefault();if(screen==='play')pause();else if(screen==='paused')$('resume').click();return;}if(screen==='play'&&['Space','ArrowLeft','ArrowRight'].includes(e.code)){e.preventDefault();if(!e.repeat){hold=true;tap=e.code==='ArrowLeft'?-1:1;}}});addEventListener('keyup',e=>{if(['Space','ArrowLeft','ArrowRight'].includes(e.code))hold=false;});addEventListener('blur',pause);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});
 let toastUntil=0;
 function toast(text,now){$('toast').textContent=text;toastUntil=now+1700;}
 function frame(now){const dt=Math.min(.05,Math.max(0,(now-last)/1000));last=now;if(screen==='play'&&run&&!run.over){acc+=dt;while(acc>=S.DT&&!run.over){S.step(run,rocket?{hold}:{tap});tap=0;acc-=S.DT;for(const e of run.events){if(['score','cell','gold'].includes(e.type)){sound(e.type==='score'?'score':'gold');effects.push({x:run.x,y:run.y,age:0,color:e.type==='score'?'#a9f4ff':'#ffd06c'});}if(e.type==='bounce'&&!saved.reduced)sound('bounce');if(e.type==='near')toast('CLOSE CALL',now);if(e.type==='zone')toast(e.zone.name.toUpperCase(),now);if(e.type==='new')toast('INCOMING: '+e.kind.toUpperCase(),now);if(['crash','hit'].includes(e.type)){sound('fail');resultDelay=.65;effects.push({x:run.x,y:run.y,age:0,color:'#ff4667'});}}}trail.push({x:run.x,y:run.y});if(trail.length>22)trail.shift();$('score').textContent=run.score;$('zone').textContent=rocket?S.zoneFor(run.score).name:Math.floor(run.t)+'s survived';$('hint').textContent=run.t<5?(rocket?'HOLD →   RELEASE ←':'TAP LEFT ↶   TAP RIGHT ↷'):'';}
 if(screen==='play'&&run?.over){resultDelay-=dt;if(resultDelay<=0)void finish();}for(const e of effects)e.age+=dt;effects=effects.filter(e=>e.age<.65);$('toast').style.opacity=now<toastUntil?'1':'0';draw(ctx,width,height,run,{time:now/1000,reduced:saved.reduced,skin:saved.skin,trail: saved.reduced?[]:trail,effects:saved.reduced?[]:effects,screen});requestAnimationFrame(frame);}
 const hero=$('hero');icon(hero.getContext('2d'),hero.width,hero.height,0);document.title=title;initAds().then(()=>{if(screen==='result')$('reward').hidden=!earned||!adsAvailable();});bannerOnScreens('screen',['home','result']);show('home');requestAnimationFrame(frame);
 // Read-only snapshot for browser QA and replay tooling. No state setters.
 window.arcadeView=()=>({screen,mode,seed:run?.seed,t:run?.t,score:run?.score,over:run?.over,hold,skin:saved.skin,total:saved.total,best:saved.best,day:runDay});
 return {icon};
}
