import * as S from './sim.mjs';
const COLORS=['#e2f9ff','#75dbff','#ffd570','#baff9e'];
function rr(c,x,y,w,h,r=5){c.beginPath();c.roundRect(x,y,w,h,r);c.fill();}
function orb(c,x,y,r,color){c.shadowColor=color;c.shadowBlur=r*.9;const g=c.createRadialGradient(x-r*.35,y-r*.4,r*.06,x,y,r);g.addColorStop(0,'#ffffff');g.addColorStop(.4,color);g.addColorStop(1,'#476579');c.fillStyle=g;c.beginPath();c.arc(x,y,r,0,7);c.fill();c.shadowBlur=0;c.fillStyle='#ffffffcf';c.beginPath();c.ellipse(x-r*.3,y-r*.4,r*.3,r*.15,-.5,0,7);c.fill();}
export function icon(c,w,h,skin=0){c.clearRect(0,0,w,h);const g=c.createLinearGradient(0,0,w,h);g.addColorStop(0,'#39273e');g.addColorStop(1,'#0b111f');c.fillStyle=g;rr(c,0,0,w,h,w*.23);c.save();c.translate(w*.5,h*.5);c.rotate(-.3);c.shadowColor='#ff3356';c.shadowBlur=w*.045;c.fillStyle='#fb3454';rr(c,-w*.4,-h*.28,w*.48,h*.14,w*.025);rr(c,w*.03,h*.14,w*.4,h*.14,w*.025);c.shadowBlur=0;c.strokeStyle='#b6f4ff66';c.lineWidth=w*.05;c.beginPath();c.moveTo(-w*.3,h*.25);c.lineTo(w*.12,-h*.22);c.stroke();orb(c,w*.07,-h*.07,w*.14,COLORS[skin]);c.restore();}
export function draw(c,w,h,run,v){const s=Math.min((w-28)/S.W,(h-170)/S.H),ox=w/2,oy=94+S.H*s/2,X=x=>ox+x*s,Y=y=>oy-y*s,l=X(-S.W/2),top=Y(S.H/2),bw=S.W*s,bh=S.H*s,t=v.reduced?0:v.time;
 const bg=c.createRadialGradient(w*.5,h*.35,10,w*.5,h*.5,h*.7);bg.addColorStop(0,'#302033');bg.addColorStop(1,'#080d19');c.fillStyle=bg;c.fillRect(0,0,w,h);c.strokeStyle='#df416619';c.lineWidth=1;for(let x=-h;x<w+h;x+=70){c.beginPath();c.moveTo(x,0);c.lineTo(x-h*.3,h);c.stroke();}
 c.shadowColor='#000';c.shadowBlur=25;c.fillStyle='#101a29';rr(c,l-9,top-9,bw+18,bh+18,15);c.shadowBlur=0;const deck=c.createLinearGradient(l,top,l+bw,top+bh);deck.addColorStop(0,'#203044');deck.addColorStop(1,'#101a2a');c.fillStyle=deck;rr(c,l,top,bw,bh,8);
 c.save();c.beginPath();c.rect(l,top,bw,bh);c.clip();c.strokeStyle='#8aa6bc0c';for(let y=top;y<top+bh;y+=s){c.beginPath();c.moveTo(l,y);c.lineTo(l+bw,y);c.stroke();}for(let x=l;x<l+bw;x+=s){c.beginPath();c.moveTo(x,top);c.lineTo(x,top+bh);c.stroke();}c.restore();
 c.strokeStyle='#536a82';c.lineWidth=3;c.strokeRect(l,top,bw,bh);c.strokeStyle='#c6e8f5';c.lineWidth=2;for(const [x,y,sx,sy] of [[l,top,1,1],[l+bw,top,-1,1],[l,top+bh,1,-1],[l+bw,top+bh,-1,-1]]){c.beginPath();c.moveTo(x,y+sy*17);c.lineTo(x,y);c.lineTo(x+sx*17,y);c.stroke();}
 const reds=run?.reds||[{kind:'block',x:-2.4,y:3,hw:1.5,hh:.35,age:2},{kind:'bar',x:2,y:-2,hw:1.6,hh:.3,age:2}];
 for(const o of reds){const warning=o.age<S.WARN;const color=warning?'#ff9b9f':'#ff3d5e';c.fillStyle=color;c.strokeStyle=color;c.lineWidth=warning?1.5:3;c.globalAlpha=warning?.55:1;c.setLineDash(warning?[5,4]:[]);c.shadowColor='#ff365b';c.shadowBlur=warning||v.reduced?0:10;
 if(o.kind==='block'||o.kind==='bar'){const x=X(o.x-o.hw),y=Y(o.y+o.hh),ww=o.hw*2*s,hh=o.hh*2*s;if(warning){c.strokeRect(x,y,ww,hh);c.setLineDash([]);c.fillRect(x,y+hh+4,ww*Math.min(1,o.age/S.WARN),2);}else{const g=c.createLinearGradient(x,y,x,y+hh);g.addColorStop(0,'#ff8794');g.addColorStop(.18,'#ff3d5e');g.addColorStop(1,'#a91438');c.fillStyle=g;rr(c,x,y,ww,hh,Math.min(5,hh/3));c.shadowBlur=0;c.fillStyle='#ffb9c0';c.fillRect(x+4,y+3,Math.max(0,ww-8),2);c.strokeStyle='#761d3977';c.lineWidth=2;c.save();c.beginPath();c.rect(x,y,ww,hh);c.clip();for(let k=x-20;k<x+ww;k+=14){c.beginPath();c.moveTo(k,y+hh);c.lineTo(k+hh,y);c.stroke();}c.restore();}}
 else if(o.kind==='laser'){const q=S.laserEnds(o,o.age);c.lineWidth=warning?1.5:.16*s;c.beginPath();c.moveTo(X(q[0]),Y(q[1]));c.lineTo(X(q[2]),Y(q[3]));c.stroke();c.setLineDash([]);for(const [x,y] of [[q[0],q[1]],[q[2],q[3]]]){c.fillStyle=warning?'#ff7888':'#ffe7e9';c.beginPath();c.arc(X(x),Y(y),3,0,7);c.fill();}}
 else if(o.kind==='chaser'){c.beginPath();c.arc(X(o.x),Y(o.y),.4*s,0,7);if(warning)c.stroke();else{c.fill();c.shadowBlur=0;c.fillStyle='#461b35';c.beginPath();c.arc(X(o.x),Y(o.y),.17*s,0,7);c.fill();c.fillStyle='#fff3ef';c.beginPath();c.arc(X(o.x)-2,Y(o.y)-3,2,0,7);c.fill();}}
 else{const hw=S.W/2,hh=S.H/2;const q=o.side===0?[o.a,-hh,o.b,-hh]:o.side===1?[hw,o.a,hw,o.b]:o.side===2?[o.a,hh,o.b,hh]:[-hw,o.a,-hw,o.b];c.lineWidth=.2*s;c.beginPath();c.moveTo(X(q[0]),Y(q[1]));c.lineTo(X(q[2]),Y(q[3]));c.stroke();}
 c.shadowBlur=0;c.globalAlpha=1;c.setLineDash([]);}
 for(const g of run?.golds||[]){const x=X(g.x),y=Y(g.y);c.save();c.translate(x,y);c.rotate(Math.PI/4+t*.7);c.shadowColor='#ffe399';c.shadowBlur=v.reduced?0:12;c.fillStyle='#ffd575';rr(c,-S.GOLD_R*s,-S.GOLD_R*s,S.GOLD_R*s*2,S.GOLD_R*s*2,4);c.shadowBlur=0;c.fillStyle='#fff6cc';rr(c,-3,-3,6,6,1);c.restore();}
 if(run){for(let i=0;i<v.trail.length;i++){const p=v.trail[i];c.globalAlpha=i/v.trail.length*.22;c.fillStyle=COLORS[v.skin];c.beginPath();c.arc(X(p.x),Y(p.y),S.R*s*(i/v.trail.length),0,7);c.fill();}c.globalAlpha=1;orb(c,X(run.x),Y(run.y),S.R*s,run.over?'#ff6b80':COLORS[v.skin]);}
 else orb(c,X(Math.sin(t*.7)*2),Y(Math.cos(t*.6)*3),S.R*s,COLORS[v.skin]);
 for(const e of v.effects){c.globalAlpha=1-e.age/.65;c.strokeStyle=e.color;c.lineWidth=2;c.beginPath();c.arc(X(e.x),Y(e.y),8+e.age*60,0,7);c.stroke();c.globalAlpha=1;}
 c.fillStyle='#7d92aa';c.font='9px system-ui';c.textAlign='center';c.fillText('ONE TOUCH. NEW DIRECTION.',w/2,Math.min(h-30,top+bh+27));
}
