import {fresh,TYPES,tick,collect,build,staff,assign,upgrade,repair,beacon,expedition,capacity,restore,rescue} from './engine.mjs';
import {draw,roomBox} from './art.mjs';
import {initAds,maybeInterstitial,showRewarded,adsAvailable} from './arcade-ads.js';
const $=s=>document.querySelector(s),KEY='tovelly.below-the-dust.v1';
let state=fresh(),selected=0,tab='room',paused=true,speed=1,shownEnd=false,dirty=true,saveClock=0,paintClock=0,last=performance.now(),visualTime=0;
let saved=null;try{saved=localStorage.getItem(KEY);if(saved){const loaded=restore(saved);if(loaded)state=loaded;else $('#save-state').textContent='Old save unreadable. A fresh shelter is ready.';}}catch{$('#save-state').textContent='Storage unavailable. This shelter lasts for this visit.';}
const canvas=$('#shelter'),g=canvas.getContext('2d');const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function fit(){const dpr=Math.min(devicePixelRatio||1,2);canvas.width=480*dpr;canvas.height=480*dpr;g.setTransform(dpr,0,0,dpr,0,0);}fit();window.addEventListener('resize',fit);
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));$('#save-state').textContent='Progress saved on this device';}catch{$('#save-state').textContent='Could not save. Keep this tab open.';}}
function announce(text){$('#announcement').textContent=text;}
function updateAction(action,text){if(action()){announce(text);save();dirty=true;render();}else announce('Not available yet. Check supplies, staffing or room capacity.');}
function button(text,fn,cls='',disabled=false){const el=document.createElement('button');el.textContent=text;el.className=cls;el.disabled=disabled;el.addEventListener('click',fn);return el;}
function element(tag,text,cls=''){const e=document.createElement(tag);e.textContent=text;e.className=cls;return e;}
function choose(i){selected=i;tab='room';const amount=collect(state,i);if(amount){announce(`Collected ${Math.floor(amount)} ${TYPES[state.rooms[i].type].resource}.`);save();}dirty=true;render();}
$('#room-access').replaceChildren(...Array.from({length:6},(_,i)=>button('',()=>choose(i))));
canvas.addEventListener('pointerdown',e=>{const b=canvas.getBoundingClientRect(),x=(e.clientX-b.left)*480/b.width,y=(e.clientY-b.top)*480/b.height;for(let i=0;i<6;i++){const r=roomBox(i);if(x>=r.x&&x<=r.x+r.w&&y>=r.y&&y<=r.y+r.h){choose(i);break;}}});
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{tab=b.dataset.tab;dirty=true;render();}));
function renderPanel(){const panel=$('#panel');panel.replaceChildren();const active=state.mode==='active';
 if(tab==='crew'){panel.append(element('h3','Your people'),element('p',`Select a room, then move people here. Matching skills produce 30% more. Beds: ${state.crew.length}/${capacity(state)}.`,'desc'));state.crew.forEach((p,id)=>{const row=element('div','','crew-row');row.append(element('span',p.name[0],'portrait'));const info=element('div','','crew-info');info.append(element('b',p.name),element('small',`${p.skill.toUpperCase()} · ${p.room===-2?'OUTSIDE':p.room===-1?'AVAILABLE':TYPES[state.rooms[p.room].type].name}`));row.append(info);const valid=state.rooms[selected]&&state.rooms[selected].type!=='home'&&staff(state,selected).length<3;row.append(button(p.room===selected?'Free up':'Assign here',()=>updateAction(()=>assign(state,id,p.room===selected?-1:selected),`${p.name}'s assignment updated.`),'',!active||p.room===-2||(p.room!==selected&&!valid)));panel.append(row);});return;}
 if(tab==='signal'){panel.append(element('h3','A way back outside'),element('p','Finish the three beacon stages and survive seven full days. Each stage uses scrap and 20 power.','desc'));const steps=element('div','','beacon-steps');['ANTENNA','AMPLIFIER','SIGNAL'].forEach((x,i)=>steps.append(element('span',x,i<state.beacon?'done':'')));panel.append(steps);const costs=[50,80,110];panel.append(button(state.beacon===3?'Beacon online':`Build stage ${state.beacon+1} · ${costs[state.beacon]} scrap`,()=>updateAction(()=>beacon(state),'One step closer to rescue.'),'primary wide',!active||state.beacon===3||state.resources.scrap<costs[state.beacon]||state.resources.power<20));panel.append(element('p',`${Math.min(7,Math.floor(state.time/60))}/7 days completed. ${state.beacon===3?'Keep the shelter running.':'The workshop is your best source of scrap.'}`,'desc'));panel.append(element('h3','Scavenge the surface'));panel.append(element('p',state.expedition?`${state.crew[state.expedition.id].name} returns in ${Math.ceil(state.expedition.left)} seconds.`:'Free up one crew member, then send them outside for scrap and food. Costs 12 food; takes 35 seconds.','desc'));panel.append(button('Send a scavenger',()=>updateAction(()=>expedition(state),'Expedition underway.'),'wide',!active||!!state.expedition||!state.crew.some(p=>p.room===-1)||state.resources.food<12));return;}
 const r=state.rooms[selected];if(!r){panel.append(element('h3','Make room for tomorrow'),element('p','Choose what this shelter needs next. New rooms start without crew.','desc'));const list=element('div','','build-list');for(const [type,meta] of Object.entries(TYPES)){const b=button('',()=>updateAction(()=>build(state,selected,type),`${meta.name} built.`),'build-option',!active||state.resources.scrap<meta.cost);b.append(element('b',meta.name),element('small',type==='home'?'Four extra beds':type==='med'?'Produces hope':`Produces ${meta.resource}`),element('span',`${meta.cost} scrap`));list.append(b);}panel.append(list);return;}
 const type=TYPES[r.type],workers=staff(state,selected),head=element('div','','room-heading');head.append(element('h3',type.name),element('span',`LEVEL ${r.level}`,'level'));panel.append(head);
 panel.append(element('p',r.damaged?'Production stopped. Repair the incident to bring this room back online.':r.type==='home'?`A place to rest. Adds ${r.level*4} beds to the shelter.`:`Produces ${type.resource} every 10 seconds with crew assigned. ${r.type==='power'?'Keeps the shelter running.':r.type==='med'?'Keeps spirits up.':'Needs power to work.'}`,'desc'+(r.damaged?' danger':'')));
 if(type.resource){const meter=element('div','','meter'),bar=element('div');bar.style.width=r.progress*10+'%';meter.append(bar);panel.append(meter);const prod=element('div','','production');prod.append(element('span',r.damaged?'OFFLINE':workers.length?`${workers.length}/3 CREW`:'NO CREW'),element('span',`${Math.floor(r.pending)} READY`));panel.append(prod);panel.append(button(`Collect ${Math.floor(r.pending)} ${type.resource}`,()=>{const n=collect(state,selected);if(n){announce(`Collected ${Math.floor(n)} ${type.resource}.`);save();dirty=true;render();}else announce('Storage is full, or supplies are not ready yet.');},'primary wide',r.pending<1||state.resources[type.resource]>=120));const assigner=element('div','','assignment');assigner.append(button('−',()=>{const person=state.crew.findIndex(p=>p.room===selected);updateAction(()=>assign(state,person,-1),'Crew member is now available.');},'',!active||!workers.length),element('span',`${workers.length} working · ${state.crew.filter(p=>p.room===-1).length} available`),button('+',()=>{const id=state.crew.findIndex(p=>p.room===-1&&p.skill===type.skill);const any=id>=0?id:state.crew.findIndex(p=>p.room===-1);updateAction(()=>assign(state,any,selected),'Crew assigned.');},'',!active||workers.length>=3||!state.crew.some(p=>p.room===-1)));panel.append(assigner);}
 const actions=element('div','','actions');actions.append(button(r.level===3?'Fully upgraded':`Upgrade · ${r.level*40} scrap`,()=>updateAction(()=>upgrade(state,selected),'Room upgraded.'),'',!active||r.level===3||r.damaged||state.resources.scrap<r.level*40));if(r.damaged)actions.append(button('Repair · 12 scrap',()=>updateAction(()=>repair(state,selected),'Room repaired.'),'',!active||state.resources.scrap<12));else actions.append(button('Manage crew',()=>{tab='crew';dirty=true;render();}));panel.append(actions);
}
function render(){for(const key of ['power','food','scrap','hope']){$('#'+key).textContent=Math.floor(state.resources[key]);$('#'+key).classList.toggle('low',state.resources[key]<20);}$('#day').textContent=`DAY ${String(Math.min(7,Math.floor(state.time/60)+1)).padStart(2,'0')} / 07`;$('#population').textContent=`${state.crew.length}/${capacity(state)} SURVIVORS`;$('#pause').textContent=paused?'▶':'Ⅱ';$('#pause').setAttribute('aria-label',paused?'Resume shelter':'Pause shelter');$('#latest').textContent=state.log[0];$('#log').replaceChildren(...state.log.map(t=>element('li',t)));$('#room-access').querySelectorAll('button').forEach((b,i)=>{const r=state.rooms[i];b.textContent=r?`${TYPES[r.type].name}${r.damaged?' !':r.pending>=1?' +'+Math.floor(r.pending):''}`:`Build room ${i+1}`;b.className=[selected===i?'selected':'',r?.pending>=1?'ready':'',r?.damaged?'broken':''].join(' ');});document.querySelectorAll('[data-tab]').forEach(b=>{b.setAttribute('aria-selected',String(b.dataset.tab===tab));b.tabIndex=b.dataset.tab===tab?0:-1;});if(dirty){const buttons=[...$("#panel").querySelectorAll("button")];const focusIndex=buttons.indexOf(document.activeElement);renderPanel();if(focusIndex>=0){const next=$("#panel").querySelectorAll("button")[focusIndex];if(next&&!next.disabled)next.focus({preventScroll:true});}dirty=false;}}
$('.tabs').addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const tabs=['room','crew','signal'];tab=tabs[(tabs.indexOf(tab)+(e.key==='ArrowRight'?1:2))%3];dirty=true;render();document.querySelector(`[data-tab="${tab}"]`).focus();}});
$('#pause').onclick=()=>{paused=!paused;announce(paused?'Shelter paused. Take your time.':'Shelter running.');save();render();};$('#speed').onclick=()=>{speed=speed===1?2:1;$('#speed').textContent=speed+'× SPEED';};
$('#journal-toggle').onclick=()=>{$('#log').hidden=!$('#log').hidden;};
function showWelcome(){paused=true;$('#begin').textContent=saved?'Continue shelter ↗':'Open the shelter ↗';$('#welcome').showModal();render();}
$('#help').onclick=showWelcome;$('#begin').onclick=()=>{$('#welcome').close();paused=false;last=performance.now();render();};
function reset(){state=fresh();selected=0;tab='room';paused=false;shownEnd=false;dirty=true;save();render();}
$('#restart').onclick=()=>{paused=true;$('#confirm').showModal();render();};$('#cancel-restart').onclick=()=>{$('#confirm').close();};$('#confirm-restart').onclick=()=>{$('#confirm').close();reset();};
$('#again').onclick=()=>{$('#finish').close();reset();};$('#view-shelter').onclick=()=>{$('#finish').close();};
$('#reward').onclick=async()=>{$('#reward').disabled=true;const r=await showRewarded();if(r.rewarded&&rescue(state)){shownEnd=false;paused=false;$('#finish').close();dirty=true;save();render();}else $('#ad-note').textContent=r.reason||'No reward was received.';$('#reward').disabled=false;};
function ending(){shownEnd=true;paused=true;save();$('#ending-title').textContent=state.mode==='won'?'You kept the lights on.':'The shelter fell quiet.';$('#ending-copy').textContent=state.mode==='won'?`${state.crew.length} people. Seven days. A signal through the dust. Your little shelter made it.`:`You lasted ${Math.floor(state.time/60)} days and ${Math.floor(state.time%60)} seconds. Keep collecting food and power, and repair rooms before hope runs out.`;$('#reward').hidden=state.mode!=='lost'||state.rescued||!adsAvailable();$('#ad-note').textContent='';$('#finish').showModal();maybeInterstitial().catch(()=>{$('#ad-note').textContent='The optional ad could not load.';});}
document.addEventListener('visibilitychange',()=>{if(document.hidden){paused=true;save();render();}});window.addEventListener('pagehide',save);
function frame(now){const dt=Math.min(.1,(now-last)/1000);last=now;if(!paused){let remaining=dt*speed;while(remaining>0){const slice=Math.min(.1,remaining);tick(state,slice);remaining-=slice;}visualTime+=dt;saveClock+=dt;if(saveClock>=3){save();saveClock=0;}}draw(g,state,selected,reduced?0:visualTime);paintClock+=dt;if(paintClock>.5){dirty=true;render();paintClock=0;}if(state.mode!=='active'&&!shownEnd)ending();requestAnimationFrame(frame);}
initAds();render();showWelcome();requestAnimationFrame(frame);

