export const TYPES={power:{name:'Generator',resource:'power',cost:45,out:14,color:'#e6a658',skill:'engineer'},grow:{name:'Grow room',resource:'food',cost:45,out:11,color:'#93bd83',skill:'grower'},work:{name:'Workshop',resource:'scrap',cost:55,out:9,color:'#76afb7',skill:'tinkerer'},home:{name:'Living quarters',resource:null,cost:50,out:0,color:'#d79581',skill:null},med:{name:'Quiet room',resource:'hope',cost:50,out:4,color:'#b7a3d4',skill:null}};
const NAMES=['Mara','Sol','Kit','Juno','Ned','Bea','Pip','Fern','Otis','Rae','Wren','Ash'];
const cap=(n,a,b)=>Math.max(a,Math.min(b,n));
export function fresh(){return {version:1,time:0,resources:{power:75,food:75,scrap:85,hope:85},rooms:[{type:'power',level:1,progress:0,pending:0,damaged:false},{type:'grow',level:1,progress:0,pending:0,damaged:false},{type:'work',level:1,progress:0,pending:0,damaged:false},null,null,null],crew:NAMES.slice(0,6).map((name,i)=>({name,skill:['engineer','grower','tinkerer'][i%3],room:i%3})),beacon:0,expedition:null,nextIncident:40,nextArrival:90,seed:18327,mode:'active',rescued:false,log:['Welcome underground. Tap a room to collect its supplies.']};}
function random(s){s.seed=(s.seed*1664525+1013904223)>>>0;return s.seed/4294967296;}
export function note(s,text){s.log.unshift(text);s.log=s.log.slice(0,12);}
export function capacity(s){return 6+s.rooms.reduce((n,r)=>n+(r?.type==='home'?4*r.level:0),0);}
export function staff(s,index){return s.crew.filter(p=>p.room===index);}
export function collect(s,index){const room=s.rooms[index];if(!room||!TYPES[room.type].resource||room.pending<1)return false;const key=TYPES[room.type].resource;const amount=Math.min(room.pending,120-s.resources[key]);if(amount<1)return false;s.resources[key]+=amount;room.pending-=amount;return amount;}
export function build(s,index,type){if(s.mode!=='active'||!Number.isInteger(index)||index<0||index>=6||s.rooms[index]||!TYPES[type])return false;const cost=TYPES[type].cost;if(s.resources.scrap<cost)return false;s.resources.scrap-=cost;s.rooms[index]={type,level:1,progress:0,pending:0,damaged:false};note(s,`${TYPES[type].name} built. ${type==='home'?'Room for four more people.':'Assign someone to get it running.'}`);return true;}
export function assign(s,person,index){if(s.mode!=='active'||!s.crew[person]||s.crew[person].room===-2||!Number.isInteger(index)||index< -1||index>=6)return false;if(index>=0&&(!s.rooms[index]||s.rooms[index].type==='home'||staff(s,index).length>=3))return false;s.crew[person].room=index;return true;}
export function upgrade(s,index){const r=s.rooms[index];if(s.mode!=='active'||!r||r.level>=3||r.damaged)return false;const cost=r.level*40;if(s.resources.scrap<cost)return false;s.resources.scrap-=cost;r.level++;note(s,`${TYPES[r.type].name} upgraded to level ${r.level}.`);return true;}
export function repair(s,index){const r=s.rooms[index];if(s.mode!=='active'||!r?.damaged||s.resources.scrap<12)return false;s.resources.scrap-=12;r.damaged=false;note(s,`${TYPES[r.type].name} repaired. Back to work.`);return true;}
export function beacon(s){const costs=[50,80,110];if(s.mode!=='active'||s.beacon>=3||s.resources.scrap<costs[s.beacon]||s.resources.power<20)return false;s.resources.scrap-=costs[s.beacon];s.resources.power-=20;s.beacon++;note(s,`Beacon stage ${s.beacon}/3 complete. ${s.beacon===3?'Signal is live. Keep everyone safe until day seven is complete.':'The outside world feels closer.'}`);return true;}
export function expedition(s){if(s.mode!=='active'||s.expedition||s.resources.food<12)return false;const id=s.crew.findIndex(p=>p.room===-1);if(id<0)return false;s.resources.food-=12;s.crew[id].room=-2;s.expedition={id,left:35};note(s,`${s.crew[id].name} is scavenging outside. Back in 35 seconds.`);return true;}
export function rescue(s){if(s.mode!=='lost'||s.rescued)return false;s.rescued=true;s.mode='active';s.resources.power=60;s.resources.food=60;s.resources.hope=60;s.resources.scrap=Math.max(20,s.resources.scrap);for(const r of s.rooms)if(r)r.damaged=false;note(s,'Emergency supplies arrived. One more chance.');return true;}
export function tick(s,dt){if(s.mode!=='active')return;dt=cap(dt,0,.25);s.time+=dt;const built=s.rooms.filter(Boolean).length;
 s.resources.power=Math.max(0,s.resources.power-dt*(built*.27+s.crew.length*.1));s.resources.food=Math.max(0,s.resources.food-dt*s.crew.length*.15);
 const damaged=s.rooms.filter(r=>r?.damaged).length;const shortage=s.resources.power<1||s.resources.food<1;
 s.resources.hope=cap(s.resources.hope+dt*(shortage?-.85:damaged?-.12*damaged:.015),0,120);
 for(let i=0;i<s.rooms.length;i++){const r=s.rooms[i];if(!r||r.damaged||r.type==='home'||(r.type!=='power'&&s.resources.power<1))continue;const people=staff(s,i);if(!people.length)continue;r.progress+=dt;if(r.progress>=10){r.progress-=10;const skill=people.reduce((n,p)=>n+(p.skill===TYPES[r.type].skill?1.3:1),0);r.pending=Math.min(75,r.pending+TYPES[r.type].out*skill*(1+(r.level-1)*.4));}}
 if(s.expedition){s.expedition.left-=dt;if(s.expedition.left<=0){const p=s.crew[s.expedition.id];p.room=-1;s.resources.scrap=Math.min(120,s.resources.scrap+35+Math.floor(random(s)*16));s.resources.food=Math.min(120,s.resources.food+15);note(s,`${p.name} returned with scrap and food.`);s.expedition=null;}}
 if(s.time>=s.nextIncident){s.nextIncident=s.time+48+random(s)*24;const candidates=s.rooms.map((r,i)=>r&&!r.damaged&&r.type!=='home'?i:-1).filter(i=>i>=0);if(candidates.length){const i=candidates[Math.floor(random(s)*candidates.length)];s.rooms[i].damaged=true;note(s,`${['A dust-clogged vent','A burst pipe','A short circuit'][Math.floor(random(s)*3)]} shut down the ${TYPES[s.rooms[i].type].name.toLowerCase()}. Repair costs 12 scrap.`);}}
 if(s.time>=s.nextArrival){s.nextArrival+=90;if(s.crew.length<capacity(s)&&s.crew.length<NAMES.length){const i=s.crew.length;s.crew.push({name:NAMES[i],skill:['grower','engineer','tinkerer'][i%3],room:-1});note(s,`${NAMES[i]} found the shelter. A fresh pair of hands.`);}else note(s,'A traveller passed by. Build living quarters to welcome more people.');}
 if(s.resources.hope<=0){s.mode='lost';note(s,'Hope ran out. Your crew abandoned the shelter.');}else if(s.time>=420&&s.beacon===3){s.mode='won';note(s,'Seven days survived. Your beacon reached a rescue convoy. Everyone made it.');}
}
export function restore(value){try{const s=JSON.parse(value);if(s.version!==1||!Number.isFinite(s.time)||s.time<0||s.time>1e8||!['active','won','lost'].includes(s.mode)||!Array.isArray(s.rooms)||s.rooms.length!==6||!Array.isArray(s.crew)||s.crew.length<6||s.crew.length>12||!Number.isInteger(s.beacon)||s.beacon<0||s.beacon>3)return null;for(const k of ['power','food','scrap','hope'])if(!Number.isFinite(s.resources[k])||s.resources[k]<0||s.resources[k]>120)return null;for(const r of s.rooms)if(r&&(!TYPES[r.type]||!Number.isInteger(r.level)||r.level<1||r.level>3||!Number.isFinite(r.pending)||r.pending<0||r.pending>75||!Number.isFinite(r.progress)||r.progress<0||r.progress>10||typeof r.damaged!=='boolean'))return null;for(const p of s.crew)if(typeof p.name!=='string'||!NAMES.includes(p.name)||!['grower','engineer','tinkerer'].includes(p.skill)||!Number.isInteger(p.room)||p.room< -2||p.room>5||(p.room>=0&&!s.rooms[p.room]))return null;if(new Set(s.crew.map(p=>p.name)).size!==s.crew.length)return null;for(let i=0;i<6;i++)if(staff(s,i).length>3)return null;if(!Number.isFinite(s.nextIncident)||!Number.isFinite(s.nextArrival)||!Number.isInteger(s.seed)||typeof s.rescued!=='boolean'||!Array.isArray(s.log)||s.log.some(x=>typeof x!=='string'))return null;if(s.expedition&&(!Number.isInteger(s.expedition.id)||!s.crew[s.expedition.id]||s.crew[s.expedition.id].room!==-2||!Number.isFinite(s.expedition.left)||s.expedition.left<0||s.expedition.left>35))return null;if(s.crew.filter(p=>p.room===-2).length!==(s.expedition?1:0))return null;return s;}catch{return null;}}

