import {fresh,TYPES,MAX,group,staff,reachable,dig,build,extend,assign,collect,upgrade,repair,beacon,expedition,capacity,rescue,restore,tick,limit} from './vault-engine.mjs';
import {createArt,roomBox,atlas} from './vault-art.mjs';
import {initAds,maybeInterstitial,showRewarded,adsAvailable} from './arcade-ads.js';
const $=id=>document.getElementById(id),KEY='tovelly.below-the-dust.v2';let state=fresh(),selected=1,panel=null,picked=null,paused=true,speed=1,ended=false,saveTime=0,last=performance.now(),time=0,uiTime=0;
let saved=false;try{const loaded=restore(localStorage.getItem(KEY));if(loaded){state=loaded;saved=true;}else if(localStorage.getItem('tovelly.below-the-dust.v1'))$('old-save').textContent='This is a new vault system. Your earlier shelter is kept separately; this version begins at the entrance.';}catch{$('save').textContent='Storage unavailable: this visit only';}
const cam={x:0,y:95,zoom:Math.max(.75,Math.min(1.3,innerWidth/500))},canvas=$('vault'),art=createArt(canvas),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,pointers=new Map();let drag=null,gesture=null,pinch=null,messageTimer=0;
const labels={power:'POWER',food:'FOOD',water:'WATER',scrap:'SCRAP',hope:'HOPE'},colors={power:'#f4d289',food:'#bad989',water:'#8cdeea',scrap:'#dfcbb3',hope:'#d3b5e5'};
for(const k of Object.keys(MAX)){$('resources').insertAdjacentHTML('beforeend',`<div class="resource" id="res-${k}" style="--c:${colors[k]}"><span>${labels[k]}</span><b>0</b><i></i></div>`);}
function announce(t){$('message').textContent=t;messageTimer=4;}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));$('save').textContent='Saved on this device';}catch{$('save').textContent='Storage unavailable: keep this tab open';}}
function act(fn,text){const result=fn();if(result){save();announce(text||state.log[0]);renderPanel();hud();}else announce('Check supplies, room capacity or available dwellers.');return result;}
function button(text,fn,disabled=false,cls=''){const b=document.createElement('button');b.textContent=text;b.disabled=disabled;b.className=cls;b.onclick=fn;return b;}
function el(tag,text,cls=''){const e=document.createElement(tag);e.textContent=text;e.className=cls;return e;}
function close(){panel=null;$('panel').classList.add('hidden');}
function focusRoom(i){const b=roomBox(i);cam.zoom=Math.max(cam.zoom,Math.min(1.2,innerWidth/300));cam.x=-(b.x+b.w/2)*cam.zoom;cam.y=innerHeight*.35-(b.y+b.h/2)*cam.zoom;}
function select(i){selected=i;if(picked!==null){if(act(()=>assign(state,picked,i),`${state.crew[picked].name} assigned.`)){picked=null;close();}return;}const n=collect(state,i);if(n){announce(`Collected ${Math.floor(n)} ${TYPES[state.rooms[i].type].resource}.`);save();}panel='room';renderPanel();}
function navLots(){const row=el('div','','row');row.append(button('‹ Previous',()=>{selected=(selected+15)%16;focusRoom(selected);renderPanel();}),el('small',`FLOOR ${Math.floor(selected/4)+1} · PLOT ${selected%4+1}`),button('Next ›',()=>{selected=(selected+1)%16;focusRoom(selected);renderPanel();}));return row;}
function renderPanel(){const p=$('panel');if(!panel){p.classList.add('hidden');return;}p.classList.remove('hidden');p.replaceChildren(button('×',close,false,'close'));p.firstChild.setAttribute('aria-label','Close panel');const active=state.mode==='active';
if(panel==='crew'){p.append(el('h2','People make a home'),el('p',`${state.crew.length}/${capacity(state)} beds. Drag a person into a room, or select them then tap a room. Matched skills improve output.`));const list=el('div','','crew');state.crew.forEach((person,id)=>{const b=button('',()=>{picked=id;close();announce(`${person.name} selected. Tap a room to assign, or People to cancel.`);},!active||person.room===-2,picked===id?'picked':'');b.append(el('b',person.name),el('small',`${person.skill.toUpperCase()} ${'★'.repeat(person.talent)}`),el('small',person.room<0?person.room===-2?'SCAVENGING':'AT THE ENTRANCE':TYPES[state.rooms[person.room].type].name));b.onpointerdown=e=>{if(person.room===-2)return;const start={x:e.clientX,y:e.clientY};b.setPointerCapture(e.pointerId);b.onpointermove=m=>{if(Math.hypot(m.clientX-start.x,m.clientY-start.y)>12){const wp=world(m.clientX,m.clientY);drag={id,x:wp.x,y:wp.y};p.style.opacity='.25';}};b.onpointerup=m=>{p.style.opacity='';if(drag){const room=hitRoom(world(m.clientX,m.clientY));if(room!==null)act(()=>assign(state,id,room),`${person.name} moved.`);drag=null;close();b.onclick=null;}b.onpointermove=null;};b.onpointercancel=()=>{drag=null;p.style.opacity='';};};list.append(b);});p.append(list);return;}
if(panel==='signal'){p.append(el('h2','A signal through the dust'),el('p',`Transmitter ${state.beacon}/3. Survive seven full days with a working transmitter. Day ${Math.min(7,Math.floor(state.time/60)+1)}. Your fabrication lab makes scrap.`));p.append(button(state.beacon===3?'Transmitter online':`Build stage ${state.beacon+1} · ${[80,120,160][state.beacon]} scrap + 30 power`,()=>act(()=>beacon(state)),!active||state.beacon===3||state.resources.scrap<[80,120,160][state.beacon]||state.resources.power<30,'primary'));p.append(el('p',state.expedition?`${state.crew[state.expedition.id].name} returns in ${Math.ceil(state.expedition.left)}s.`:'Send an idle dweller outside. 15 food buys a trip; they bring 65 scrap and 20 food back.'));p.append(button('Send scavenger',()=>act(()=>expedition(state)),!active||!!state.expedition||!state.crew.some(x=>x.room===-1)||state.resources.food<15));return;}
const r=state.rooms[selected];if(!r){p.append(el('h2',state.dug[selected]?'Bring this room to life':'Build your haven'),navLots());if(!reachable(state,selected)){p.append(el('p','Extend the lift for this floor. Build the room beside the lift before digging an outer plot.'),button('Extend lift · 35 scrap',()=>act(()=>extend(state)),!active||state.floors>=4||state.resources.scrap<35));return;}if(!state.dug[selected]){p.append(el('p','Carve a room out of the mountain. Every room starts here.'),button('Excavate · 10 scrap',()=>act(()=>dig(state,selected)),!active||state.resources.scrap<10,'primary'));return;}const choices=el('div','','choices');for(const [key,meta]of Object.entries(TYPES)){const b=button('',()=>{if(act(()=>build(state,selected,key))){focusRoom(selected);renderPanel();}},!active||state.resources.scrap<meta.cost);const thumb=el('div');thumb.style.cssText=`position:absolute;left:7px;top:8px;width:43px;height:52px;border-radius:5px;background-image:url(assets/rooms-v2.png);background-size:300% 200%;background-position:${meta.tile%3*50}% ${Math.floor(meta.tile/3)*100}%`;b.append(thumb,el('b',meta.name),el('small',`${meta.cost} scrap · ${meta.resource||'extra beds'}`));choices.append(b);}p.append(choices);return;}
const meta=TYPES[r.type],ids=group(state,selected),n=staff(state,selected).length,total=ids.reduce((a,i)=>a+state.rooms[i].pending,0),damaged=ids.some(i=>state.rooms[i].damaged);p.append(el('h2',meta.name),el('p',`${ids.length===2?'DOUBLE ROOM · ':''}LEVEL ${r.level} · ${n}/${ids.length*3} DWELLERS${meta.skill?' · '+meta.skill.toUpperCase():''}`),navLots());if(damaged)p.append(button('Contain incident · 15 scrap',()=>act(()=>repair(state,selected)),!active||state.resources.scrap<15,'primary'));else if(meta.resource)p.append(button(`Collect ${Math.floor(total)} ${meta.resource}`,()=>act(()=>collect(state,selected),`Collected ${meta.resource}.`),!active||total<1||state.resources[meta.resource]>=MAX[meta.resource],'primary'));const row=el('div','','row');const worker=state.crew.findIndex(x=>x.room===ids[0]),idle=state.crew.findIndex(x=>x.room===-1&&x.skill===meta.skill),any=idle>=0?idle:state.crew.findIndex(x=>x.room===-1);row.append(button('− Dweller',()=>act(()=>assign(state,worker,-1),'Dweller returned to the entrance.'),!active||worker<0),button('+ Dweller',()=>act(()=>assign(state,any,selected),'Dweller assigned.'),!active||any<0||n>=ids.length*3));p.append(row);p.append(button(r.level===3?'Fully upgraded':`Upgrade · ${r.level*45*ids.length} scrap`,()=>act(()=>upgrade(state,selected)),!active||r.level>=3||damaged||state.resources.scrap<r.level*45*ids.length));}
function hud(){for(const k of Object.keys(MAX)){const d=$('res-'+k);d.querySelector('b').textContent=Math.floor(state.resources[k]);d.querySelector('i').style.width=state.resources[k]/MAX[k]*100+'%';d.classList.toggle('low',state.resources[k]<20);}$('day').textContent=`DAY ${String(Math.min(7,Math.floor(state.time/60)+1)).padStart(2,'0')} / 07`;$('population').textContent=`${state.crew.length}/${capacity(state)} DWELLERS`;$('pause').textContent=paused?'▶':'Ⅱ';$('pause').setAttribute('aria-label',paused?'Resume shelter':'Pause shelter');const built=state.rooms.filter(Boolean);$('mission').textContent=!built.length?'YOUR FIRST ROOM: EXCAVATE → DYNAMO → ASSIGN A DWELLER':!built.some(r=>r.type==='water')?'BUILD WATERWORKS TO KEEP YOUR PEOPLE HYDRATED':!built.some(r=>r.type==='grow')?'BUILD A BOTANICAL FARM TO KEEP EVERYONE FED':picked!==null?`ASSIGNING ${state.crew[picked].name.toUpperCase()} · TAP A ROOM`:'GROW YOUR HAVEN · BUILD THE RESCUE TRANSMITTER';}
$('build').onclick=()=>{picked=null;panel='room';if(!reachable(state,selected))selected=state.rooms.findIndex((r,i)=>!r&&reachable(state,i));if(selected<0)selected=1;renderPanel();};$('people').onclick=()=>{picked=null;panel='crew';renderPanel();};$('signal').onclick=()=>{panel='signal';renderPanel();};$('pause').onclick=()=>{paused=!paused;hud();};$('speed').onclick=()=>{speed=speed===1?2:1;$('speed').textContent=speed+'×';};
function world(x,y){return {x:(x-innerWidth/2-cam.x)/cam.zoom,y:(y-cam.y)/cam.zoom};}function hitRoom(p){for(let i=0;i<16;i++){const b=roomBox(i);if(p.x>=b.x&&p.x<=b.x+b.w&&p.y>=b.y&&p.y<=b.y+b.h)return i;}return null;}
function zoom(f,x=innerWidth/2,y=innerHeight*.4){const before=world(x,y);cam.zoom=limit(cam.zoom*f,.45,2.1);cam.x=x-innerWidth/2-before.x*cam.zoom;cam.y=y-before.y*cam.zoom;}
$('zoom-in').onclick=()=>zoom(1.2);$('zoom-out').onclick=()=>zoom(1/1.2);$('home-camera').onclick=()=>{cam.x=0;cam.y=95;cam.zoom=Math.max(.75,Math.min(1.3,innerWidth/500));};canvas.onwheel=e=>{e.preventDefault();zoom(Math.exp(-e.deltaY*.001),e.clientX,e.clientY);};
canvas.onpointerdown=e=>{canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){drag=null;gesture=null;const [a,b]=[...pointers.values()];pinch={distance:Math.hypot(a.x-b.x,a.y-b.y)};return;}const p=world(e.clientX,e.clientY);gesture={id:e.pointerId,x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,moved:false};for(const [id,pos]of art.positions)if(state.crew[id]?.room!==-2&&Math.abs(pos.x-p.x)<17&&p.y>pos.y-52&&p.y<pos.y+5){drag={id,x:pos.x,y:pos.y};break;}};
canvas.onpointermove=e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){const [a,b]=[...pointers.values()],distance=Math.hypot(a.x-b.x,a.y-b.y);if(pinch)zoom(distance/Math.max(1,pinch.distance),(a.x+b.x)/2,(a.y+b.y)/2);pinch={distance};return;}if(!gesture)return;const dx=e.clientX-gesture.x,dy=e.clientY-gesture.y;gesture.moved||=Math.hypot(e.clientX-gesture.startX,e.clientY-gesture.startY)>6;if(drag){const p=world(e.clientX,e.clientY);drag.x=p.x;drag.y=p.y+20;}else{cam.x=limit(cam.x+dx,-1000*cam.zoom,1000*cam.zoom);cam.y=limit(cam.y+dy,-1100*cam.zoom,innerHeight*.65);}gesture.x=e.clientX;gesture.y=e.clientY;};
canvas.onpointerup=e=>{pointers.delete(e.pointerId);if(pinch){if(pointers.size===0)pinch=null;gesture=null;return;}const p=world(e.clientX,e.clientY);if(drag&&gesture?.moved){const i=hitRoom(p);if(i!==null)act(()=>assign(state,drag.id,i),`${state.crew[drag.id].name} moved to the room.`);}else if(gesture&&!gesture.moved){const i=hitRoom(p);if(i!==null)select(i);else if(Math.abs(p.x)<85&&p.y>230+state.floors*176&&p.y<260+state.floors*176)act(()=>extend(state));else close();}drag=null;gesture=null;};canvas.onpointercancel=()=>{pointers.clear();drag=null;gesture=null;pinch=null;};
function welcome(){paused=true;close();$('begin').textContent=saved?'Continue your haven ↗':'Build your first room ↗';$('welcome').showModal();hud();}$('help').onclick=welcome;$('begin').onclick=()=>{$('welcome').close();paused=false;last=performance.now();hud();};$('new-run').onclick=()=>{$('welcome').close();$('confirm').showModal();};$('cancel').onclick=()=>{$('confirm').close();welcome();};function reset(){state=fresh();saved=false;ended=false;selected=1;picked=null;paused=false;close();art.positions.clear();$('home-camera').click();save();hud();}$('reset').onclick=()=>{$('confirm').close();reset();};$('again').onclick=async()=>{$('again').disabled=true;try{await maybeInterstitial();}catch{}$('again').disabled=false;$('finish').close();reset();};$('view').onclick=()=>{$('finish').close();};$('reward').onclick=async()=>{$('reward').disabled=true;try{const result=await showRewarded();if(result.rewarded&&rescue(state)){ended=false;paused=false;$('finish').close();save();}else $('ad-note').textContent=result.reason||'No reward received.';}catch{$('ad-note').textContent='Ad unavailable. Please try again later.';}finally{$('reward').disabled=false;}};
function ending(){ended=true;paused=true;save();$('finish-title').textContent=state.mode==='won'?'Your haven made it.':'The lights went out.';$('finish-copy').textContent=state.mode==='won'?`${state.crew.length} people, seven days, and a signal through the dust.`:'Keep power, food and water flowing. Match dwellers to rooms, collect supplies and respond to incidents.';$('reward').hidden=state.mode!=='lost'||state.rescued||!adsAvailable();$('finish').showModal();}
document.addEventListener('visibilitychange',()=>{if(document.hidden){paused=true;save();hud();}});window.addEventListener('pagehide',save);window.addEventListener('keydown',e=>{if(e.target.tagName==='INPUT'||document.querySelector('dialog[open]'))return;if(e.code==='Escape'){close();picked=null;}if(e.code==='KeyP')$('pause').click();if(e.code==='Equal')zoom(1.2);if(e.code==='Minus')zoom(1/1.2);});
function frame(now){const dt=Math.min(.1,(now-last)/1000);last=now;if(!paused){tick(state,dt*speed);time+=dt;saveTime+=dt;if(saveTime>3){save();saveTime=0;}}art.draw(state,cam,selected,time,drag,reduced);uiTime+=dt;messageTimer-=dt;if(messageTimer<=0)$('message').textContent=paused?'PAUSED · YOUR SHELTER IS SAFE WHILE YOU PLAN':'';if(uiTime>.75){hud();if(panel&&!drag&&!gesture){const focused=document.activeElement?.textContent;renderPanel();if(focused){const b=[...$('panel').querySelectorAll('button')].find(x=>x.textContent===focused);if(b)b.focus({preventScroll:true});}}uiTime=0;}if(state.mode!=='active'&&!ended)ending();requestAnimationFrame(frame);}initAds().catch(()=>{});hud();welcome();requestAnimationFrame(frame);const ready=()=>{$('begin').disabled=false;};if(atlas.complete)ready();else{atlas.onload=ready;atlas.onerror=()=>{$('old-save').textContent='Room artwork could not load. Refresh to try again.';$('begin').textContent='Artwork unavailable';};}

