export const TYPES={power:{name:'Dynamo hall',resource:'power',cost:55,out:18,color:'#ffc170',skill:'engineering',tile:0},grow:{name:'Botanical farm',resource:'food',cost:50,out:16,color:'#c1e989',skill:'botany',tile:1},water:{name:'Waterworks',resource:'water',cost:50,out:16,color:'#82dceb',skill:'science',tile:2},home:{name:'Living quarters',resource:null,cost:60,out:0,color:'#ffb99d',skill:null,tile:3},work:{name:'Fabrication lab',resource:'scrap',cost:65,out:14,color:'#abc9ee',skill:'engineering',tile:4},med:{name:'Sanctuary',resource:'hope',cost:65,out:7,color:'#d8b6f5',skill:'science',tile:5}};
const NAMES=['Mara','Sol','Kit','Juno','Nia','Theo','Pip','Fern','Otis','Rae','Wren','Ash'];
export const limit=(v,a,b)=>Math.max(a,Math.min(b,v));
export const MAX={power:300,food:300,water:300,scrap:600,hope:100};
export function fresh(){return {version:2,time:0,resources:{power:140,food:140,water:140,scrap:360,hope:90},rooms:Array(16).fill(null),dug:Array(16).fill(false),floors:1,crew:NAMES.slice(0,4).map((name,i)=>({name,skill:['engineering','botany','science','engineering'][i],talent:3+i%3,room:-1})),beacon:0,expedition:null,nextIncident:100,nextArrival:95,seed:18327,mode:'active',rescued:false,log:['A door in the hillside. Four people. Everything else is yours to build.']};}
export function note(s,t){s.log.unshift(t);s.log=s.log.slice(0,12);}
const random=s=>{s.seed=(s.seed*1664525+1013904223)>>>0;return s.seed/4294967296};
export function group(s,i){if(!s.rooms[i])return [];const pair=i%2===0?i+1:i-1;return s.rooms[pair]?.type===s.rooms[i].type&&s.rooms[pair].level===s.rooms[i].level?[i,pair].sort((a,b)=>a-b):[i];}
export function staff(s,i){const ids=group(s,i);return s.crew.filter(p=>ids.includes(p.room));}
export const capacity=s=>4+s.rooms.filter(r=>r?.type==='home').reduce((a,r)=>a+3*r.level,0);
export function reachable(s,i){return Number.isInteger(i)&&i>=0&&i<16&&Math.floor(i/4)<s.floors&&(i%4===1||i%4===2||!!s.rooms[i%4===0?i+1:i-1]);}
export function dig(s,i){if(s.mode!=='active'||!reachable(s,i)||s.dug[i]||s.resources.scrap<10)return false;s.resources.scrap-=10;s.dug[i]=true;note(s,'Rock cleared. Choose a room to bring this space to life.');return true;}
export function build(s,i,type){if(s.mode!=='active'||!s.dug[i]||s.rooms[i]||!TYPES[type]||s.resources.scrap<TYPES[type].cost)return false;s.resources.scrap-=TYPES[type].cost;s.rooms[i]={type,level:1,progress:0,pending:0,damaged:false};const ids=group(s,i);for(const p of s.crew)if(ids.includes(p.room))p.room=ids[0];note(s,ids.length===2?`${TYPES[type].name} merged into a double room.`:`${TYPES[type].name} is ready. Drag a dweller inside to start work.`);return true;}
export function extend(s){if(s.mode!=='active'||s.floors>=4||s.resources.scrap<35||!s.rooms.slice((s.floors-1)*4,s.floors*4).some(Boolean))return false;s.resources.scrap-=35;s.floors++;note(s,'Lift extended. A new floor is ready to excavate.');return true;}
export function assign(s,id,i){const p=s.crew[id];if(s.mode!=='active'||!p||p.room===-2||!Number.isInteger(i)||i< -1||i>=16||i>=0&&(!s.rooms[i]||staff(s,i).length>=group(s,i).length*3))return false;p.room=i<0?-1:group(s,i)[0];return true;}
export function collect(s,i){if(s.mode!=='active'||!s.rooms[i])return false;const ids=group(s,i),key=TYPES[s.rooms[i].type].resource;if(!key)return false;let sum=0;for(const id of ids){const r=s.rooms[id],n=Math.min(r.pending,MAX[key]-s.resources[key]);s.resources[key]+=n;r.pending-=n;sum+=n;}return sum;}
export function upgrade(s,i){const r=s.rooms[i],ids=group(s,i);if(s.mode!=='active'||!r||r.level>=3||ids.some(j=>s.rooms[j].damaged)||s.resources.scrap<r.level*45*ids.length)return false;s.resources.scrap-=r.level*45*ids.length;for(const j of ids)s.rooms[j].level++;note(s,`${TYPES[r.type].name} upgraded. More output, same footprint.`);return true;}
export function repair(s,i){const ids=group(s,i);if(s.mode!=='active'||!ids.some(j=>s.rooms[j].damaged)||s.resources.scrap<15)return false;s.resources.scrap-=15;for(const j of ids)s.rooms[j].damaged=false;note(s,'Incident contained. Everyone is back to work.');return true;}
export function beacon(s){const costs=[80,120,160];if(s.mode!=='active'||s.beacon>=3||s.resources.scrap<costs[s.beacon]||s.resources.power<30)return false;s.resources.scrap-=costs[s.beacon];s.resources.power-=30;s.beacon++;note(s,`Rescue transmitter ${s.beacon}/3. ${s.beacon===3?'Stay alive until day seven.':'A little closer to the outside.'}`);return true;}
export function expedition(s){const id=s.crew.findIndex(p=>p.room===-1);if(s.mode!=='active'||s.expedition||id<0||s.resources.food<15)return false;s.resources.food-=15;s.crew[id].room=-2;s.expedition={id,left:30};note(s,`${s.crew[id].name} is searching the surface.`);return true;}
export function rescue(s){if(s.mode!=='lost'||s.rescued)return false;s.mode='active';s.rescued=true;for(const k of ['power','food','water','hope'])s.resources[k]=90;s.resources.scrap=Math.max(60,s.resources.scrap);for(const r of s.rooms)if(r)r.damaged=false;return true;}
export function tick(s,dt){if(s.mode!=='active')return;dt=limit(dt,0,.25);s.time+=dt;const built=s.rooms.filter(Boolean).length;s.resources.power=Math.max(0,s.resources.power-dt*(built*.06+s.crew.length*.025));for(const key of ['food','water'])s.resources[key]=Math.max(0,s.resources[key]-s.crew.length*dt*.08);const shortage=['power','food','water'].some(k=>s.resources[k]<1);s.resources.hope=limit(s.resources.hope+dt*(shortage?-.45:s.rooms.some(r=>r?.damaged)?-.04:.01),0,100);
for(let i=0;i<16;i++){const r=s.rooms[i];if(!r||group(s,i)[0]!==i)continue;const ids=group(s,i),people=staff(s,i);if(!people.length||!TYPES[r.type].resource||ids.some(j=>s.rooms[j].damaged)||r.type!=='power'&&s.resources.power<1)continue;r.progress+=dt;if(r.progress>=12){r.progress-=12;const skill=people.reduce((n,p)=>n+(p.skill===TYPES[r.type].skill?1+p.talent*.12:.7),0);r.pending=Math.min(150,r.pending+TYPES[r.type].out*skill*(1+(r.level-1)*.35));}}
if(s.time>=s.nextIncident){s.nextIncident=s.time+65+random(s)*30;const candidates=s.rooms.map((r,i)=>r&&r.type!=='home'&&!r.damaged?i:-1).filter(i=>i>=0);if(candidates.length){const i=candidates[Math.floor(random(s)*candidates.length)];s.rooms[i].damaged=true;note(s,`Incident in ${TYPES[s.rooms[i].type].name}. Tap the red room and repair it.`);}}
if(s.time>=s.nextArrival){s.nextArrival+=95;if(s.crew.length<capacity(s)&&s.crew.length<12){const i=s.crew.length;s.crew.push({name:NAMES[i],skill:['science','engineering','botany'][i%3],talent:3+i%3,room:-1});note(s,`${NAMES[i]} has arrived at the entrance.`);}}
if(s.expedition){s.expedition.left-=dt;if(s.expedition.left<=0){s.crew[s.expedition.id].room=-1;s.resources.scrap=Math.min(600,s.resources.scrap+65);s.resources.food=Math.min(300,s.resources.food+20);note(s,'Scavenger returned with 65 scrap and 20 food.');s.expedition=null;}}
if(s.resources.hope<=0)s.mode='lost';else if(s.time>=420&&s.beacon===3)s.mode='won';}
export function restore(raw){try{const s=JSON.parse(raw);if(s.version!==2||!Number.isFinite(s.time)||s.time<0||s.time>1e8||!['active','lost','won'].includes(s.mode)||!Array.isArray(s.rooms)||s.rooms.length!==16||!Array.isArray(s.dug)||s.dug.length!==16||s.dug.some(x=>typeof x!=='boolean')||!Number.isInteger(s.floors)||s.floors<1||s.floors>4||!Array.isArray(s.crew)||s.crew.length<4||s.crew.length>12||!Number.isInteger(s.beacon)||s.beacon<0||s.beacon>3)return null;for(const [k,max]of Object.entries(MAX))if(!Number.isFinite(s.resources[k])||s.resources[k]<0||s.resources[k]>max)return null;for(let i=0;i<16;i++){const r=s.rooms[i];if(r&&(!s.dug[i]||Math.floor(i/4)>=s.floors||!TYPES[r.type]||![1,2,3].includes(r.level)||typeof r.damaged!=='boolean'||!Number.isFinite(r.progress)||r.progress<0||r.progress>12||!Number.isFinite(r.pending)||r.pending<0||r.pending>150))return null;}for(const p of s.crew)if(!NAMES.includes(p.name)||!['engineering','science','botany'].includes(p.skill)||!Number.isInteger(p.talent)||p.talent<1||p.talent>5||!Number.isInteger(p.room)||p.room< -2||p.room>15||p.room>=0&&!s.rooms[p.room])return null;if(new Set(s.crew.map(p=>p.name)).size!==s.crew.length||!Number.isFinite(s.nextIncident)||!Number.isFinite(s.nextArrival)||!Number.isInteger(s.seed)||typeof s.rescued!=='boolean'||!Array.isArray(s.log)||s.log.some(t=>typeof t!=='string'))return null;for(let i=0;i<16;i++)if(s.rooms[i]&&staff(s,i).length>group(s,i).length*3)return null;if(s.expedition&&(!s.crew[s.expedition.id]||s.crew[s.expedition.id].room!==-2||!Number.isFinite(s.expedition.left)||s.expedition.left<0||s.expedition.left>30))return null;if(s.crew.filter(p=>p.room===-2).length!==(s.expedition?1:0))return null;return s;}catch{return null;}}
