import {LEVELS,loadProgress,unlocked,recordWin} from './levels.mjs';
import {createGame} from './sim.mjs';import {makeRenderer} from './art.mjs';import {initAds,showRewarded,maybeInterstitial,adsAvailable} from './arcade-ads.js';
const $=id=>document.getElementById(id),screens=['menu','levels','help','result','paused'];
let progress;try{progress=loadProgress(localStorage.getItem('getaway.v1'));}catch{progress=loadProgress(null);}
let game=createGame(Matter,0),mode='menu',levelIndex=0,helpReturn='menu',muted=true,audio=null,last=0,acc=0,move=0,jump=false,dive=false,pointerMove=null,keys=new Set(),jumpUntil=0,diveUntil=0,tutorialRead=false;
const renderer=makeRenderer($('game'));window.addEventListener('resize',()=>renderer.resize());
function clearInput(){move=0;jump=false;dive=false;keys.clear();pointerMove=null;jumpUntil=0;diveUntil=0;$('nub').style.transform='';}
function screen(next){mode=next;screens.forEach(id=>$(id).hidden=id!==next);const playing=next==='play';['hud','controls','progress'].forEach(id=>$(id).hidden=!playing);if(!playing)$('hint').hidden=true;clearInput();}
function sound(type){if(muted)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);const f={shot:340,zap:150,bonk:90,smash:210,boom:60,loot:850,jump:400,spring:600,hit:110,win:1100,grab:450,dive:230}[type]||200;o.type=type==='shot'?'square':'sine';o.frequency.setValueAtTime(f,audio.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(30,f*.45),audio.currentTime+.12);g.gain.setValueAtTime(type==='shot'?.025:.08,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.17);o.start();o.stop(audio.currentTime+.18);}catch{$('notice').textContent='Sound is unavailable in this browser.';muted=true;}}
function begin(i){if(!unlocked(progress,i))return;game.dispose();levelIndex=i;game=createGame(Matter,i);renderer.reset();screen('play');$('levelNo').textContent=`GETAWAY ${String(i+1).padStart(2,'0')} / 12`;$('levelName').textContent=game.level.name;$('hintText').textContent=game.level.tip;$('hint').hidden=false;last=performance.now();acc=0;sound('jump');}
function levelMenu(){screen('levels');$('levelGrid').replaceChildren();LEVELS.forEach((l,i)=>{const b=document.createElement('button');b.className='level-card';b.disabled=!unlocked(progress,i);b.setAttribute('aria-label',`Level ${i+1}: ${l.name}${b.disabled?', locked':''}`);const n=document.createElement('b'),t=document.createElement('span'),stars=document.createElement('small');n.textContent=String(i+1).padStart(2,'0');t.textContent=l.name;stars.textContent=b.disabled?'LOCKED':'★'.repeat(progress[i])+'☆'.repeat(3-progress[i]);b.append(n,t,stars);b.onclick=()=>begin(i);$('levelGrid').append(b);});}
function result(){const won=game.phase==='won';screen('result');$('resultTag').textContent=won?'YOU ACTUALLY MADE IT':'THAT WENT WELL.';$('resultTitle').textContent=won?'Clean-ish getaway.':'A minor setback.';$('stars').textContent=won?'★'.repeat(game.stars)+'☆'.repeat(3-game.stars):'↻';$('resultCopy').textContent=won?`${game.collected}/3 loot bags. ${game.health}/3 shields. ${game.knockouts} robots knocked over. ${Math.round(game.tick/60)} seconds.`:game.reason;$('next').hidden=!won;$('next').textContent=levelIndex===11?'ALL 12 CLEARED →':'NEXT GETAWAY →';$('retry').textContent=won?'Replay for more stars':'Try again';secondChance(won);if(won){progress=recordWin(progress,levelIndex,game.stars);try{localStorage.setItem('getaway.v1',JSON.stringify(progress));}catch{$('notice').textContent='Progress could not be saved. Keep this tab open to continue.';}}}
function continueGame(){begin(Math.min(progress.findIndex(v=>v===0)<0?0:progress.findIndex(v=>v===0),11));}
$('play').onclick=()=>{if(!tutorialRead&&progress.every(v=>!v)){helpReturn='start';screen('help');}else continueGame();};$('choose').onclick=levelMenu;$('levelsBack').onclick=()=>screen('menu');$('how').onclick=()=>{helpReturn='menu';screen('help');};$('helpBack').onclick=()=>{tutorialRead=true;if(helpReturn==='start')continueGame();else screen(helpReturn);};$('sound').onclick=()=>{muted=!muted;$('sound').textContent=muted?'SOUND OFF':'SOUND ON';$('sound').setAttribute('aria-label',muted?'Enable sound':'Mute sound');sound('loot');};$('hintClose').onclick=()=>$('hint').hidden=true;
$('pause').onclick=()=>screen('paused');$('resume').onclick=()=>screen('play');$('restart').onclick=()=>begin(levelIndex);$('pauseMenu').onclick=()=>screen('menu');$('next').onclick=()=>afterBreak(()=>levelIndex===11?levelMenu():begin(levelIndex+1));$('retry').onclick=()=>afterBreak(()=>begin(levelIndex));$('resultMenu').onclick=levelMenu;
function hold(id,down,up){const el=$(id);el.addEventListener('pointerdown',e=>{e.preventDefault();el.setPointerCapture(e.pointerId);down();});el.addEventListener('pointerup',up);el.addEventListener('pointercancel',up);el.addEventListener('lostpointercapture',up);el.addEventListener('click',e=>{if(e.detail===0){down();setTimeout(up,180);}});}
hold('left',()=>move=-1,()=>move=0);hold('right',()=>move=1,()=>move=0);hold('jump',()=>{jump=true;jumpUntil=performance.now()+120;},()=>jump=false);hold('dive',()=>{dive=true;diveUntil=performance.now()+120;},()=>dive=false);
const stick=$('stick');function drag(e){const r=stick.getBoundingClientRect();move=Math.max(-1,Math.min(1,(e.clientX-r.left-r.width/2)/34));if(Math.abs(move)<.15)move=0;$('nub').style.transform=`translateX(${move*24}px)`;}
stick.addEventListener('pointerdown',e=>{e.preventDefault();pointerMove=e.pointerId;stick.setPointerCapture(e.pointerId);drag(e);});stick.addEventListener('pointermove',e=>{if(e.pointerId===pointerMove)drag(e);});const stop=()=>{pointerMove=null;move=0;$('nub').style.transform='';};stick.addEventListener('pointerup',stop);stick.addEventListener('pointercancel',stop);stick.addEventListener('lostpointercapture',stop);
window.addEventListener('keydown',e=>{if(e.code==='Escape'){if(mode==='play')screen('paused');else if(mode==='paused')screen('play');return;}if(mode!=='play')return;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyA','KeyD','KeyW','KeyS'].includes(e.code)){e.preventDefault();keys.add(e.code);}});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{if(mode==='play')screen('paused');});document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode==='play')screen('paused');});
function loop(t){acc+=Math.min(100,t-(last||t));last=t;if(mode==='play'){let n=0;while(acc>=1000/60&&n++<6){acc-=1000/60;const k=(keys.has('ArrowRight')||keys.has('KeyD')?1:0)-(keys.has('ArrowLeft')||keys.has('KeyA')?1:0);game.step({move:k||move,jump:jump||t<jumpUntil||keys.has('Space')||keys.has('ArrowUp')||keys.has('KeyW'),dive:dive||t<diveUntil||keys.has('KeyS')||keys.has('ArrowDown')});for(const e of game.events)sound(e.type);if(game.phase!=='playing'){result();break;}}$('health').textContent='♥'.repeat(game.health)+'♡'.repeat(3-game.health);$('health').setAttribute('aria-label',`${game.health} of 3 shields`);$('loot').textContent=`$ ${game.collected}/3`;$('progressText').textContent=game.grab?'ON THE ROPE · JUMP TO LET GO':`${Math.max(0,Math.round((1-game.player.torso.position.x/game.level.length)*100))}% TO THE VAN`;$('progressFill').style.width=`${Math.max(0,Math.min(100,game.player.torso.position.x/game.level.length*100))}%`;if(game.tick>850)$('hint').hidden=true;}else acc=0;renderer.draw(game,mode==='menu'?'menu':'play');requestAnimationFrame(loop);}
requestAnimationFrame(loop);
if('serviceWorker'in navigator&&!window.Capacitor)navigator.serviceWorker.register('sw.js').catch(()=>{$('notice').textContent='Offline play is unavailable. You can still play online.';});

// Ads (phone app only; arcade-ads.js reports why when there are none). A rewarded ad is only ever the
// player's choice: after a loss, once per attempt, it puts them back on solid ground with one shield.
// Interstitials wait for the player to leave the result screen; the module spaces them out itself.
initAds();
function secondChance(won){const b=$('secondChance'),note=$('adNote');note.textContent='';b.hidden=won||game.revived||!adsAvailable();b.disabled=false;b.textContent='WATCH AN AD: SECOND CHANCE';
 b.onclick=async()=>{b.disabled=true;b.textContent='Loading ad...';const r=await showRewarded();
  if(r.rewarded&&game.revive()){screen('play');last=performance.now();acc=0;sound('jump');return;}
  b.hidden=true;note.textContent=r.rewarded?'That attempt cannot be continued.':r.reason;};}
async function afterBreak(go){const shown=await maybeInterstitial();if(shown==='failed')console.error('Interstitial skipped between levels.');go();}
