import * as S from './sim.mjs';
const SKINS=['#ff865b','#7edfff','#ffd16f','#c0ff9b'];
const palettes=[['#091528','#1e3c57','#80e1e6'],['#100f29','#383158','#bca9ff'],['#20131f','#6c4037','#ffb16e'],['#0d1928','#345364','#8ce4ee'],['#071f30','#24586c','#aeeefa'],['#090d22','#2c3162','#b9c5ff']];
function round(c,x,y,w,h,r=4){if(w<=0||h<=0)return;c.beginPath();c.roundRect(x,y,w,h,r);c.fill();}
export function ship(c,x,y,size,tilt,color,t=0){c.save();c.translate(x,y);c.rotate(tilt);const s=size;c.shadowColor=color;c.shadowBlur=s*.7;c.fillStyle='#ff8a42';c.beginPath();c.moveTo(-s*.38,s*.75);c.quadraticCurveTo(-s*.45,s*1.6,0,s*(2.3+Math.sin(t*30)*.3));c.quadraticCurveTo(s*.45,s*1.6,s*.38,s*.75);c.fill();c.shadowBlur=0;c.fillStyle='#fff0a5';c.beginPath();c.moveTo(-s*.2,s*.7);c.lineTo(0,s*1.6);c.lineTo(s*.2,s*.7);c.fill();c.fillStyle=color;c.beginPath();c.moveTo(-s*.45,0);c.lineTo(-s*.9,s*.85);c.lineTo(-s*.37,s*.65);c.lineTo(s*.37,s*.65);c.lineTo(s*.9,s*.85);c.lineTo(s*.45,0);c.fill();const g=c.createLinearGradient(-s,0,s,0);g.addColorStop(0,'#7594ae');g.addColorStop(.45,'#fffaf1');g.addColorStop(1,'#adbeca');c.fillStyle=g;c.beginPath();c.moveTo(0,-s*1.25);c.bezierCurveTo(s*.65,-s*.65,s*.56,s*.4,s*.34,s*.8);c.lineTo(-s*.34,s*.8);c.bezierCurveTo(-s*.56,s*.4,-s*.65,-s*.65,0,-s*1.25);c.fill();c.fillStyle='#163852';c.beginPath();c.ellipse(0,-s*.18,s*.23,s*.35,0,0,7);c.fill();c.fillStyle='#a9efff';c.beginPath();c.ellipse(-s*.06,-s*.3,s*.08,s*.14,-.25,0,7);c.fill();c.fillStyle=color;round(c,-s*.34,s*.45,s*.68,s*.12,1);c.restore();}
export function icon(c,w,h,skin=0){c.clearRect(0,0,w,h);const g=c.createRadialGradient(w*.5,h*.4,0,w*.5,h*.5,w*.55);g.addColorStop(0,'#345578');g.addColorStop(1,'#071124');c.fillStyle=g;round(c,0,0,w,h,w*.23);c.strokeStyle='#a4e6ff1c';c.lineWidth=w*.012;for(let i=0;i<3;i++){c.beginPath();c.arc(w*.5,h*.51,w*(.22+i*.1),0,7);c.stroke();}c.save();c.translate(w*.51,h*.47);c.rotate(.28);ship(c,0,0,w*.23,0,SKINS[skin],0);c.restore();}
export function draw(c,w,h,run,v){const zone=run?S.ZONES.indexOf(S.zoneFor(run.score)):0,[bg,steel,glow]=palettes[zone],s=Math.min(w/S.SHAFT,h/18),left=(w-S.SHAFT*s)/2,cam=run?.y||0,t=v.reduced?0:v.time;const X=x=>w/2+x*s,Y=y=>h*.7-(y-cam)*s;
 const sky=c.createLinearGradient(0,0,0,h);sky.addColorStop(0,bg);sky.addColorStop(1,steel);c.fillStyle=sky;c.fillRect(0,0,w,h);
 // Far gantries move at a different rate from the flight corridor.
 c.fillStyle='#02091444';for(let i=0;i<7;i++){const x=(i/6)*w;c.fillRect(x,0,Math.max(4,w*.02),h);}c.strokeStyle='#b5d9e512';c.lineWidth=1;const shift=(cam*s*.25)%110;for(let y=-110+shift;y<h;y+=110){c.beginPath();c.moveTo(0,y);c.lineTo(w,y+70);c.stroke();}
 for(let i=0;i<40;i++){const x=((i*97.3)%997)/997*w,y=(((i*67.7)%701)+cam*2)%701/701*h;c.fillStyle=i%3?'#c5eaff22':'#c5eaff66';c.fillRect(x,y,i%3?1:2,2);}
 c.fillStyle='#02091644';c.fillRect(left,0,S.SHAFT*s,h);for(const x of [left,left+S.SHAFT*s-5]){c.fillStyle='#68879b';c.fillRect(x,0,5,h);c.fillStyle=glow;c.fillRect(x+1,0,1,h);for(let y=(cam*s)%58-58;y<h;y+=58){c.fillStyle='#0c1728';c.fillRect(x-3,y,11,14);c.fillStyle='#89a8ba';c.fillRect(x,y+3,4,3);}}
 function slab(x,y,ww,hh){if(ww<=0||y>h+80||y+hh< -80)return;const g=c.createLinearGradient(0,y,0,y+hh);g.addColorStop(0,'#748997');g.addColorStop(.12,steel);g.addColorStop(.85,bg);g.addColorStop(1,'#030b17');c.fillStyle=g;c.fillRect(x,y,ww,hh);c.fillStyle=glow;c.fillRect(x,y,ww,2);c.fillStyle='#0006';c.fillRect(x,y+hh-4,ww,4);c.save();c.beginPath();c.rect(x,y,ww,hh);c.clip();c.strokeStyle='#e1b97870';c.lineWidth=4;for(let k=x-20;k<x+ww+20;k+=20){c.beginPath();c.moveTo(k,y+hh-9);c.lineTo(k+8,y+hh-1);c.stroke();}c.restore();c.fillStyle='#c8d9e6';for(let bx=x+12;bx<x+ww-8;bx+=40){c.beginPath();c.arc(bx,y+hh/2,1.5,0,7);c.fill();}}
 const course=run?.course;
 if(course){for(const o of course.winds){const top=Y(o.y1),bottom=Y(o.y0);if(bottom<0||top>h)continue;c.fillStyle='#82dcff12';c.fillRect(left,top,S.SHAFT*s,bottom-top);c.strokeStyle='#adeaff55';c.lineWidth=1.5;for(let j=0;j<6;j++){const yy=top+(bottom-top)*(j+.5)/6,xx=left+((t*70*o.push+j*53)% (S.SHAFT*s)+S.SHAFT*s)%(S.SHAFT*s);c.beginPath();c.moveTo(xx,yy);c.lineTo(xx+Math.sign(o.push)*20,yy);c.stroke();}}
 for(const o of course.gates){const g=S.gateAt(o,run.t),yy=Y(o.y+o.thick),hh=o.thick*s;slab(left,yy,X(g.x-g.w/2)-left,hh);slab(X(g.x+g.w/2),yy,left+S.SHAFT*s-X(g.x+g.w/2),hh);c.fillStyle=glow;for(const xx of [X(g.x-g.w/2)-4,X(g.x+g.w/2)]){c.shadowColor=glow;c.shadowBlur=v.reduced?0:10;c.fillRect(xx,yy,4,hh);c.shadowBlur=0;}}
 for(const o of course.tunnels){if(Y(o.y0)<0||Y(o.y1)>h)continue;for(let y=o.y0;y<o.y1;y+=.25){const q=S.tunnelAt(o,y);c.fillStyle=steel;c.fillRect(left,Y(y+.25),X(q.c-q.w/2)-left,.25*s+1);c.fillRect(X(q.c+q.w/2),Y(y+.25),left+S.SHAFT*s-X(q.c+q.w/2),.25*s+1);c.fillStyle=glow;c.fillRect(X(q.c-q.w/2)-2,Y(y+.25),2,.25*s+1);c.fillRect(X(q.c+q.w/2),Y(y+.25),2,.25*s+1);}}
 for(const o of course.spinners){if(Y(o.y)<-o.len*s||Y(o.y)>h+o.len*s)continue;const q=S.spinnerAt(o,run.t);c.lineCap='round';c.lineWidth=o.thick*s;c.strokeStyle='#ff7956';c.shadowColor='#ff7547';c.shadowBlur=v.reduced?0:12;c.beginPath();c.moveTo(X(q.ax),Y(q.ay));c.lineTo(X(q.bx),Y(q.by));c.stroke();c.shadowBlur=0;c.fillStyle='#fff5d4';c.beginPath();c.arc(X(o.x),Y(o.y),5,0,7);c.fill();}
 for(const q of course.cells){if(run.gotCells.includes(q.id)||Y(q.y)<-20||Y(q.y)>h+20)continue;c.save();c.translate(X(q.x),Y(q.y));c.rotate(Math.PI/4);c.shadowColor='#ffd069';c.shadowBlur=v.reduced?0:10;c.fillStyle='#ffc85b';round(c,-s*.22,-s*.22,s*.44,s*.44,3);c.shadowBlur=0;c.fillStyle='#fff0bf';round(c,-s*.08,-s*.12,s*.12,s*.18,1);c.restore();}}
 if(run){for(let i=0;i<v.trail.length;i++){const p=v.trail[i];c.fillStyle=`rgba(255,160,86,${i/v.trail.length*.22})`;c.beginPath();c.arc(X(p.x),Y(p.y)+s*.4,(i/v.trail.length)*s*.22,0,7);c.fill();}if(!run.over)ship(c,X(run.x),Y(run.y),S.R*s,run.tilt,SKINS[v.skin],t);else{c.fillStyle='#ffe0aa';c.beginPath();c.arc(X(run.x),Y(run.y),S.R*s*.6,0,7);c.fill();}}
 else{slab(left,h*.32,S.SHAFT*s*.29,25);slab(left+S.SHAFT*s*.65,h*.32,S.SHAFT*s*.35,25);ship(c,w*.5,h*.7,22,Math.sin(t*.6)*.2,SKINS[v.skin],t);}
 for(const e of v.effects){c.strokeStyle=e.color;c.globalAlpha=1-e.age/.65;c.lineWidth=2;c.beginPath();c.arc(X(e.x),Y(e.y),(10+e.age*80),0,7);c.stroke();c.globalAlpha=1;}c.lineCap='butt';
}
