import {fresh,start,tick,move,shoot,reload,serve,buy,clamp,spawn} from './engine.mjs';
import {renderer} from './art.mjs';
import {initAds,maybeInterstitial} from './arcade-ads.js';
const $=id=>document.getElementById(id),canvas=$('world'),draw=renderer(canvas);let s=fresh(),last=0,keys=new Set(),joy={x:0,y:0},look=null,audio=null,muted=false,calm=matchMedia('(prefers-reduced-motion: reduce)').matches,lastPhase='title',hitTime=0,best=0;
try{best=Number(localStorage.getItem('tovelly.nightshift.best'))||0;muted=localStorage.getItem('tovelly.nightshift.mute')==='true';}catch{}$('quiet').checked=muted;$('calm').checked=calm;$('best').textContent=best?`YOUR BEST SHIFT RUN · ${best.toLocaleString()} POINTS`:'';
initAds().catch(()=>{});
function sound(kind){if(muted)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();const now=audio.currentTime,g=audio.createGain();g.connect(audio.destination);if(kind==='shot'){const buffer=audio.createBuffer(1,audio.sampleRate*.25,audio.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*(1-i/data.length);const n=audio.createBufferSource();n.buffer=buffer;const filter=audio.createBiquadFilter();filter.type='lowpass';filter.frequency.setValueAtTime(3000,now);filter.frequency.exponentialRampToValueAtTime(160,now+.24);n.connect(filter);filter.connect(g);g.gain.setValueAtTime(.36,now);g.gain.exponentialRampToValueAtTime(.001,now+.25);n.start();const o=audio.createOscillator();o.frequency.setValueAtTime(90,now);o.frequency.exponentialRampToValueAtTime(30,now+.2);o.connect(g);o.start();o.stop(now+.25);}else{const o=audio.createOscillator();o.type=kind==='reload'?'triangle':'sine';o.frequency.setValueAtTime(kind==='serve'?640:kind==='hurt'?100:230,now);o.frequency.exponentialRampToValueAtTime(kind==='serve'?1000:70,now+.16);g.gain.setValueAtTime(.09,now);g.gain.exponentialRampToValueAtTime(.001,now+.2);o.connect(g);o.start();o.stop(now+.21);}}catch{}}
function fire(){const r=shoot(s);if(r.fired)sound('shot');if(r.hit)hitTime=.18;}function load(){if(reload(s))sound('reload')}function service(){if(serve(s))sound('serve')}
function resetInput(){keys.clear();joy={x:0,y:0};look=null;$('stick').firstElementChild.style.transform='';}
function pause(){if(s.phase==='play'){s.phase='paused';resetInput();}else if(s.phase==='paused')s.phase='play';}
$('start').onclick=()=>{start(s);sound('serve');$('menu').classList.add('hidden');};$('pause').onclick=pause;$('fire').onclick=fire;$('reload').onclick=load;$('serve').onclick=service;
$('quiet').onchange=e=>{muted=e.target.checked;try{localStorage.setItem('tovelly.nightshift.mute',String(muted))}catch{}};$('calm').onchange=e=>{calm=e.target.checked;};
$('next').onclick=async()=>{if(s.phase==='paused'){s.phase='play';return}const phase=s.phase;if(phase==='won'||phase==='lost'){$('next').disabled=true;try{await maybeInterstitial();}catch{}finally{$('next').disabled=false;}}if(phase==='break'){s.night++;start(s);}else{s=fresh();start(s);}};$('restart').onclick=()=>{s=fresh();start(s);};document.querySelectorAll('[data-upgrade]').forEach(b=>b.onclick=()=>{if(buy(s,b.dataset.upgrade)){sound('serve');renderPanel();}});
function renderPanel(){const paused=s.phase==='paused',ended=s.phase==='won'||s.phase==='lost';$('breakLabel').textContent=paused?'ON YOUR BREAK':s.phase==='won'?'EMPLOYEE OF THE MONTH':s.phase==='lost'?'SHIFT ABANDONED':`SHIFT ${s.night} COMPLETE`;$('breakTitle').textContent=paused?'Take a breath.':s.phase==='won'?'You made it.':s.phase==='lost'?'Clocked out.':'Still in one piece.';$('breakText').textContent=paused?'WASD / thumb pad to move. Drag the shop to look up and around. Space or FIRE shoots. R reloads. Face a bag-carrying customer and press E to serve. Red eyes mean trouble.':`${s.kills} toys unstuffed · ${s.served} customers served · ${s.score} points. ${ended?'Try another run and beat your best.':`$${s.cash} in the till. Spend it before the next shift.`}`;$('upgrades').classList.toggle('hidden',paused||ended);$('next').textContent=paused?'BACK TO WORK ↗':ended?'ANOTHER SHIFT ↗':'NEXT SHIFT ↗';$('restart').classList.toggle('hidden',!paused);for(const b of document.querySelectorAll('[data-upgrade]')){const type=b.dataset.upgrade,cost={shells:60,reload:50,health:35}[type];b.disabled=s.cash<cost||type==='shells'&&s.capacity===8||type==='reload'&&s.fast||type==='health'&&s.hp===100;}}
window.addEventListener('keydown',e=>{if(e.target instanceof HTMLInputElement)return;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();keys.add(e.code);if(!e.repeat){if(e.code==='Space')fire();if(e.code==='KeyR')load();if(e.code==='KeyE')service();if(e.code==='Escape'||e.code==='KeyP')pause();}});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{if(s.phase==='play')pause();resetInput();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&s.phase==='play')pause();});
canvas.addEventListener('pointerdown',e=>{if(s.phase!=='play')return;canvas.setPointerCapture(e.pointerId);look={id:e.pointerId,x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,drag:false};});canvas.addEventListener('pointermove',e=>{if(!look||e.pointerId!==look.id||s.phase!=='play')return;const dx=e.clientX-look.x,dy=e.clientY-look.y;if(Math.hypot(e.clientX-look.startX,e.clientY-look.startY)>5)look.drag=true;s.p.yaw+=dx*.005;s.p.pitch=clamp(s.p.pitch-dy*.004,-.8,.8);look.x=e.clientX;look.y=e.clientY;});canvas.addEventListener('pointerup',e=>{if(look&&look.id===e.pointerId&&!look.drag&&e.pointerType==='mouse')fire();look=null;});canvas.addEventListener('pointercancel',()=>look=null);
let stickId=null;const stick=$('stick');function stickMove(e){const r=stick.getBoundingClientRect(),x=(e.clientX-r.x-r.width/2)/35,y=(e.clientY-r.y-r.height/2)/35,len=Math.max(1,Math.hypot(x,y));joy={x:x/len,y:y/len};stick.firstElementChild.style.transform=`translate(${joy.x*23}px,${joy.y*23}px)`;}stick.onpointerdown=e=>{stickId=e.pointerId;stick.setPointerCapture(e.pointerId);stickMove(e);};stick.onpointermove=e=>{if(e.pointerId===stickId)stickMove(e);};stick.onpointerup=stick.onpointercancel=()=>{stickId=null;joy={x:0,y:0};stick.firstElementChild.style.transform='';};
function frame(time){const dt=Math.min((time-last)/1000,.05)||.016;last=time;if(s.phase==='title'){s.p.yaw=Math.sin(time*.00013)*.12;s.p.x=-.3;if(!s.entities.length){spawn(s,'bear',false,-1.3,5.5);spawn(s,'rabbit',false,2,7);spawn(s,'bear',true,1.2,4);}for(const e of s.entities)e.age+=dt;}if(s.phase==='play'){move(s,(keys.has('KeyW')||keys.has('ArrowUp')?1:0)-(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-joy.y,(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0)+joy.x,dt);if(keys.has('ArrowLeft'))s.p.yaw-=dt*1.8;if(keys.has('ArrowRight'))s.p.yaw+=dt*1.8;const hp=s.hp;tick(s,dt);if(s.hp<hp)sound('hurt');}draw(s,time/1000,calm);hitTime=Math.max(0,hitTime-dt);$('hit').style.opacity=String(hitTime>0?1:0);$('night').textContent=String(s.night).padStart(2,'0');$('clock').textContent=`${s.time<12.5?'12':Math.min(5,Math.floor(s.time/12.5))}:00 AM`;$('cash').textContent=`$${s.cash}`;$('health').textContent=Math.ceil(s.hp);$('healthbar').style.width=`${s.hp}%`;$('ammo').innerHTML=`<strong>${s.reload?'…':s.ammo}</strong><span>/ ${s.capacity} SHELLS</span>`;$('notice').textContent=s.messageTime?s.message:'';$('objective').textContent=s.blackout?'POWER OUT • FOLLOW THE RED EYES':s.reload?'RELOADING • KEEP MOVING':`${Math.max(0,Math.ceil(75-s.time))}s TO OPENING • SERVE THE FRIENDLY ONES`;$('serve').disabled=s.phase!=='play';$('reload').disabled=s.phase!=='play'||!!s.reload||s.ammo===s.capacity;$('fire').disabled=s.phase!=='play'||!!s.reload;if(s.phase!==lastPhase){$('break').classList.toggle('hidden',!['break','paused','won','lost'].includes(s.phase));if(['break','paused','won','lost'].includes(s.phase)){resetInput();renderPanel();}if(['won','lost'].includes(s.phase)){best=Math.max(best,s.score);try{localStorage.setItem('tovelly.nightshift.best',String(best));}catch{}}lastPhase=s.phase;}requestAnimationFrame(frame);}requestAnimationFrame(frame);

$('start').disabled=false;
