export const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export const angle=v=>Math.atan2(Math.sin(v),Math.cos(v));
export const TYPES=['bear','rabbit','monkey','teddy'];
export function fresh(){return {phase:'title',night:1,time:0,hp:100,cash:0,score:0,kills:0,served:0,ammo:6,capacity:6,fast:false,reload:0,cooldown:0,blackout:0,flash:0,hurt:0,spawn:8,customer:2,entities:[],particles:[],p:{x:0,z:1.4,yaw:0,pitch:0},message:'',messageTime:0,nextId:1,shots:0};}
export function say(s,message){s.message=message;s.messageTime=3.6;}
export function start(s){s.phase='play';s.time=0;s.spawn=7;s.customer=1;s.entities=[];s.p={x:0,z:1.4,yaw:0,pitch:0};s.ammo=s.capacity;s.reload=0;s.blackout=0;s.cooldown=0;s.hp=Math.max(s.hp,35);say(s,s.night===1?'Welcome to Plush & Co. Serve the customer with E.':'The toys remember you. Keep checking behind you.');}
export function spawn(s,type,friendly=false,x=null,z=10){const e={id:s.nextId++,type,friendly,x:x??((s.nextId%3)-1)*2.6,z,y:type==='rabbit'&&!friendly?2.65:.8,hp:type==='teddy'?2:1,age:0,attack:0,seed:s.nextId*2.3};s.entities.push(e);return e;}
export function target(s,e){const dx=e.x-s.p.x,dz=e.z-s.p.z;return {d:Math.hypot(dx,dz),a:angle(Math.atan2(dx,dz)-s.p.yaw),v:Math.atan2(e.y-1.55,Math.hypot(dx,dz))-s.p.pitch};}
export function move(s,forward,side,dt){if(s.phase!=='play')return;const len=Math.max(1,Math.hypot(forward,side));const dx=(Math.sin(s.p.yaw)*forward+Math.cos(s.p.yaw)*side)*dt*2.6/len,dz=(Math.cos(s.p.yaw)*forward-Math.sin(s.p.yaw)*side)*dt*2.6/len;const nx=clamp(s.p.x+dx,-3.35,3.35),nz=clamp(s.p.z+dz,.65,10.8);if(!(nx< -2.35&&s.p.z<2.25))s.p.x=nx;if(!(s.p.x< -2.35&&nz<2.25))s.p.z=nz;}
export function reload(s){if(s.phase!=='play'||s.reload||s.ammo===s.capacity)return false;s.reload=s.fast?1.15:2.1;say(s,'Reloading… keep your distance.');return true;}
export function serve(s){if(s.phase!=='play')return false;const e=s.entities.filter(e=>e.friendly).find(e=>{const t=target(s,e);return t.d<4&&Math.abs(t.a)<.55});if(!e){say(s,'Face a friendly customer with a shopping bag. Get closer.');return false}s.entities=s.entities.filter(x=>x!==e);s.cash+=25;s.score+=100;s.served++;say(s,'Order packed. +$25. Thank you for shopping!');return true;}
export function shoot(s){if(s.phase!=='play'||s.reload||s.cooldown)return {fired:false};if(!s.ammo){reload(s);return {fired:false}}s.ammo--;s.shots++;s.cooldown=.72;s.flash=.13;const candidates=s.entities.map(e=>({e,...target(s,e)})).filter(t=>Math.abs(t.a)<.12+.28/Math.max(1,t.d)&&Math.abs(t.v)<.14+.45/Math.max(1,t.d)).sort((a,b)=>a.d-b.d);const hit=candidates[0]?.e;if(!hit)return {fired:true};if(hit.friendly){s.cash=Math.max(0,s.cash-20);s.hp=Math.max(0,s.hp-10);say(s,'That was a customer! −$20. Look for glowing red eyes.');s.entities=s.entities.filter(e=>e!==hit);return {fired:true,friendly:true}}
hit.hp--;for(let i=0;i<22;i++)s.particles.push({x:hit.x,y:hit.y,z:hit.z,vx:Math.sin(i*2.4)*2,vy:1+(i%5)*.4,vz:Math.cos(i*2.4)*2,life:1.2,color:i%3?'#ecdbc8':'#a68adb'});if(hit.hp<=0){s.entities=s.entities.filter(e=>e!==hit);s.kills++;s.cash+=12;s.score+=60;if(hit.type==='teddy'){spawn(s,'mini',false,clamp(hit.x-.6,-4,4),hit.z);spawn(s,'mini',false,clamp(hit.x+.6,-4,4),hit.z);say(s,'There were TWO more inside that one.')}else say(s,'Just stuffing. +$12.')}else say(s,'Those seams are tough. Hit it again.');return {fired:true,hit:true};}
export function tick(s,dt){if(s.phase!=='play')return;dt=Math.min(dt,.1);s.time+=dt;for(const k of ['cooldown','blackout','flash','hurt','messageTime'])s[k]=Math.max(0,s[k]-dt);if(s.reload){s.reload-=dt;if(s.reload<=0){s.reload=0;s.ammo=s.capacity;say(s,'Loaded. Watch the ceiling.')}}s.spawn-=dt;s.customer-=dt;if(s.spawn<=0){const types=s.night===1?['bear','rabbit','bear','monkey']:TYPES;const type=types[Math.floor(s.time/8)%types.length];spawn(s,type);s.spawn=Math.max(4,10-s.night*1.4);say(s,type==='bear'?'Stitching creaks. The bear moves when you look away.':type==='rabbit'?'Stuffing falls from the ceiling. Look up.':type==='monkey'?'Cymbals in the dark. Follow the red eyes.':'Something big is coming apart at the seams.');if(type==='monkey')s.blackout=5;}if(s.customer<=0){if(!s.entities.some(e=>e.friendly))spawn(s,'bear',true,1.8,10);s.customer=17;}for(const e of [...s.entities]){e.age+=dt;e.attack=Math.max(0,e.attack-dt);const t=target(s,e);if(e.friendly){e.z=Math.max(4,e.z-dt*.9);if(e.age>26){s.entities=s.entities.filter(x=>x!==e);say(s,'A customer left. No service, no tips.')}continue;}const seen=Math.abs(t.a)<.63&&Math.abs(t.v)<.62;let speed=e.type==='mini'?1.05:e.type==='rabbit'?.64:e.type==='bear'?(seen?0:.83):.52;speed*=1+s.night*.12;if(t.d>.9){e.x+=(s.p.x-e.x)/t.d*speed*dt;e.z+=(s.p.z-e.z)/t.d*speed*dt;}if(e.type==='rabbit'&&t.d<3)e.y=Math.max(.8,e.y-dt*1.2);if(t.d<1.25&&!e.attack){s.hp=Math.max(0,s.hp-(e.type==='mini'?7:12));s.hurt=.35;e.attack=1.7;say(s,'Too close! Back up and fire.');}}for(const p of s.particles){p.life-=dt;p.x+=p.vx*dt;p.z+=p.vz*dt;p.y+=p.vy*dt;p.vy-=4*dt;}s.particles=s.particles.filter(p=>p.life>0);if(s.hp<=0){s.phase='lost';s.entities=[];}else if(s.time>=75){s.phase=s.night===3?'won':'break';s.cash+=50;s.score+=250;s.entities=[];s.blackout=0;}}
export function buy(s,type){if(s.phase!=='break')return false;const cost={shells:60,reload:50,health:35}[type];if(!cost||s.cash<cost||type==='shells'&&s.capacity===8||type==='reload'&&s.fast||type==='health'&&s.hp===100)return false;s.cash-=cost;if(type==='shells')s.capacity=8;if(type==='reload')s.fast=true;if(type==='health')s.hp=Math.min(100,s.hp+35);return true;}
