import {blank,guide,apply,replay} from './design.mjs';
import {build,flatFacets} from './physics/paper.mjs';
import {model,analyse,createFlight} from './physics/flight.mjs';
import {scenarios} from './physics/scenarios.mjs';
import {createMansion} from './mansion.mjs';
import {initAds,maybeInterstitial} from './arcade-ads.js';
const $=id=>document.getElementById(id),KEY='tovelly.paperflight.design.v1';let ops=[],sheet=blank(),guideIndex=0,guided=true,phase='intro',last=performance.now(),time=0,paused=false,flight=null,built=null,plane=null,analysis=null,scene=null,air=true,muted=true,audio=null,best=0,line=null,drawing=null,foldMode=true,toastTime=0,viewDrag=null,slowFrames=0,changedAt=0;
try{const saved=JSON.parse(localStorage.getItem(KEY)||'null');if(saved&&Array.isArray(saved.ops)){sheet=replay(saved.ops);ops=saved.ops;guideIndex=Math.min(8,Math.max(0,saved.guideIndex||0));guided=guideIndex<8&&saved.guided===true;}best=Number(localStorage.getItem('tovelly.paperflight.best'))||0;}catch{ops=[];sheet=blank();}
initAds().catch(()=>{});function toast(t){$('toast').textContent=t;toastTime=4;}
function save(){try{localStorage.setItem(KEY,JSON.stringify({ops,guideIndex,guided}));}catch{toast('Design cannot save on this device. Keep this tab open.');}}
function sound(type){if(muted)return;try{audio??=new AudioContext();audio.resume();const gain=audio.createGain();gain.connect(audio.destination);const osc=audio.createOscillator();osc.type=type==='fold'?'triangle':'sine';osc.frequency.setValueAtTime(type==='fold'?300:700,audio.currentTime);osc.frequency.exponentialRampToValueAtTime(type==='fold'?130:440,audio.currentTime+.13);gain.gain.setValueAtTime(.035,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+.16);osc.connect(gain);osc.start();osc.stop(audio.currentTime+.2);}catch{}}
function transition(next){if(next==='launch'){$('distance').textContent='0.0 m / 48 m';$('place').textContent='THE ENTRANCE HALL';}phase=next;document.body.dataset.phase=next;for(const id of ['intro','desk','launch','flight-hud','inspect'])$(id).classList.toggle('hidden',id==='flight-hud'?next!=='flight':next!==id);$('pause').disabled=next==='intro';last=performance.now();}
function remake(){try{built=build(sheet);plane=model(built);analysis=analyse(plane);scene?.setPlane(built,plane);$('analysis').textContent=`${(plane.mass*1000).toFixed(1)}g paper · ${sheet.folds.length} creases · ${analysis.verdict}`;$('verdict').textContent=`Your fold: ${analysis.verdict}. Fans add real moving air; reach their streams to stay aloft.`;return true;}catch(e){toast('This fold is too compressed to fly. Undo a crease and open the wings.');$('analysis').textContent=e.message;return false;}}
function commit(op){try{if(ops.length>=100)throw Error('This design has reached 100 edits. Undo an edit or start a fresh sheet.');const next=apply(sheet,op);if(next.facets.length>350)throw Error('This sheet is getting too complex. Undo a fold before adding more.');sheet=next;ops.push(op);line=null;changedAt=time;sound('fold');save();renderDesk();return true;}catch(e){toast(e.message);return false;}}
function renderDesk(){const next=guide[guideIndex];$('guide').classList.toggle('hidden',!guided||!next);$('free-controls').classList.toggle('hidden',guided&&!!next);$('guide-count').textContent=`GUIDED FIRST BUILD / ${Math.min(8,guideIndex+1)} OF 8`;$('guide-name').textContent=next?.name||'Your design, your flight.';$('guide-copy').textContent=next?.text||'';$('undo').disabled=!ops.length;$('crease').replaceChildren(...sheet.folds.map((f,i)=>{const o=document.createElement('option');o.value=i;o.textContent=`Crease ${i+1} · ${Math.round(f.open)}°`;return o;}));$('crease').disabled=!sheet.folds.length;$('angle').disabled=!sheet.folds.length;if(sheet.folds.length){$('crease').value=sheet.folds.length-1;$('angle').value=sheet.folds.at(-1).open;}updateAngleLabel();$('trim-row').classList.toggle('hidden',guideIndex<8||sheet.folds.length<8);$('paper-caption').textContent=guided?'Follow the highlighted crease, one fold at a time.':line?'Tap the side of the paper that should fold.':'Draw a crease, then tap the side to fold over.';remake();drawPaper();}
function updateAngleLabel(){$('angle-value').textContent=`${$('angle').value}° · 0 folded / 180 flat / 360 reversed`;}
$('guide-step').onclick=()=>{if(commit({type:'guide',index:guideIndex})){guideIndex++;if(guideIndex>=8){guided=false;toast('Your glider is ready. Try it, then come back to tune the tail.');}save();renderDesk();}};$('free').onclick=()=>{guided=false;save();renderDesk();};$('draw-fold').onclick=()=>{foldMode=true;line=null;toast('Drag a crease across the paper, then tap the flap to fold.');};$('flip').onclick=()=>commit({type:'flip'});$('clip').onclick=()=>{if(sheet.clips.length>=4){toast('Four clips is plenty for one sheet. Undo one to move it.');return;}commit({type:'clip'});};$('undo').onclick=()=>{const undone=ops.pop();if(undone?.type==='guide')guideIndex=Math.max(0,guideIndex-1);sheet=replay(ops);line=null;save();renderDesk();};$('crease').onchange=()=>{$('angle').value=sheet.folds[Number($('crease').value)].open;updateAngleLabel();drawPaper();};$('angle').oninput=updateAngleLabel;$('angle').onchange=()=>{const index=Number($('crease').value);commit({type:'open',index,angle:Number($('angle').value)});$('crease').value=index;};$('trim').oninput=()=>{$('trim-value').textContent=$('trim').value+'°';};$('trim').onchange=()=>commit({type:'trim',angle:Number($('trim').value)});
$('fresh').onclick=()=>$('new-sheet').showModal();$('keep').onclick=()=>$('new-sheet').close();$('replace').onclick=()=>{ops=[];sheet=blank();guideIndex=0;guided=true;line=null;$('new-sheet').close();save();renderDesk();};$('enter').onclick=()=>{transition('desk');renderDesk();};$('to-hall').onclick=()=>{if(remake()){save();transition('launch');toast('A gentle throw is a good starting point. Watch the down-blowing ceiling fan.');}};$('back-desk').onclick=()=>{flight=null;transition('desk');renderDesk();};$('view3d').onclick=()=>{if(remake())transition('inspect');};$('inspect-back').onclick=()=>{transition('desk');renderDesk();};
for(const key of ['speed','pitch','yaw'])$(key).oninput=()=>{$(key+'-label').textContent=key==='speed'?Number($(key).value).toFixed(1)+' m/s':$(key).value+'°';};
function throwPlane(){if(phase!=='launch'||!plane)return;flight=createFlight(plane,{speed:Number($('speed').value),pitch:Number($('pitch').value),yaw:Number($('yaw').value),roll:0},scenarios.mansion);transition('flight');sound('throw');fanButtons();toast('Ride the vents. Tap a fan or its button to switch it.');}
$('throw').onclick=throwPlane;function fanButtons(){$('fan-buttons').replaceChildren();for(const src of scenarios.mansion.airSources.filter(s=>s.type==='fan')){const b=document.createElement('button');b.textContent=`${src.id.replace(' fan','').toUpperCase()} ${flight.air.isOn(src.id,flight.state.t)?'ON':'OFF'}`;b.classList.toggle('off',!flight.air.isOn(src.id,flight.state.t));b.onclick=()=>{if(paused||phase!=='flight')return;const on=flight.toggle(src.id);toast(`${src.id}: ${on?'on':'off'}`);sound('fold');fanButtons();};$('fan-buttons').append(b);}}$('air-view').onclick=()=>{air=!air;scene.showAir(air);$('air-view').textContent=`Air trails: ${air?'ON':'OFF'}`;};
function end(){const r=flight.result;phase='result';$('flight-hud').classList.add('hidden');const won=r.goals?.passed;best=Math.max(best,r.distance);try{localStorage.setItem('tovelly.paperflight.best',String(best));}catch{}$('result-title').textContent=won?'Across the whole house.':r.reason==='hit'?`Caught the ${r.name}.`:'Back to the drawing board.';$('result-stats').textContent=`${r.distance.toFixed(1)} m · ${r.t.toFixed(1)} s`;const feedback=won?'Your folds, throw and fan choices carried you to the conservatory. Try a different design and see if it can do better.':r.name==='hall doorway'||r.name==='ballroom arch'?'You reached the doorway, but not through its opening. Try a little less tail bend or a lower launch angle.':r.name==='ceiling'?'Too much climb. Reduce your tail bend or launch angle.':r.name==='left wall'||r.name==='right wall'?'The plane drifted off line. Check matching wings and tail angles, then adjust your launch aim.':r.name==='planter'?'Nearly there. You need a little more height over the conservatory planter. Reach the garden fan’s stream.':r.reason==='landed'?'You ran out of height. Broader wings, a gentler throw and reaching the fans can help.':'Try a small change to one crease, then compare the flight.';$('result-copy').textContent=`${feedback} Best: ${best.toFixed(1)} m.`;$('result').showModal();}
let afterEnd=false;async function leaveResult(target){if(afterEnd)return;afterEnd=true;try{await maybeInterstitial();}catch{}finally{afterEnd=false;}$('result').close();flight=null;transition(target);if(target==='desk')renderDesk();}$('retry').onclick=()=>leaveResult('launch');$('refold').onclick=()=>leaveResult('desk');$('pause').onclick=()=>{if(phase==='intro'||phase==='result')return;paused=true;$('paused').showModal();};$('resume').onclick=()=>{paused=false;$('paused').close();last=performance.now();};$('quit').onclick=()=>{paused=false;flight=null;$('paused').close();transition('desk');renderDesk();};$('mute').onclick=()=>{muted=!muted;$('mute').textContent='Sound: '+(muted?'off':'on');sound('fold');};document.addEventListener('visibilitychange',()=>{if(document.hidden&&phase==='flight'&&!paused){paused=true;$('paused').showModal();}save();});window.addEventListener('pagehide',save);
const paper=$('paper'),pg=paper.getContext('2d');let paperMap={scale:1,x:0,y:0};function point(p){return [paperMap.x+p[0]*paperMap.scale,paperMap.y-p[1]*paperMap.scale];}function unpoint(e){const b=paper.getBoundingClientRect();return [(e.clientX-b.left-paperMap.x)/paperMap.scale,(paperMap.y-(e.clientY-b.top))/paperMap.scale];}
function drawPaper(){if(phase!=='desk')return;const rect=paper.getBoundingClientRect(),w=rect.width,h=rect.height;if(!w||!h)return;const dpr=Math.min(devicePixelRatio||1,2);if(paper.width!==w*dpr||paper.height!==h*dpr){paper.width=w*dpr;paper.height=h*dpr;}pg.setTransform(dpr,0,0,dpr,0,0);const bg=pg.createRadialGradient(w*.5,h*.4,20,w*.5,h*.5,w);bg.addColorStop(0,'#60715a');bg.addColorStop(1,'#293f34');pg.fillStyle=bg;pg.fillRect(0,0,w,h);pg.strokeStyle='#d9ddad0c';pg.lineWidth=1;for(let x=0;x<w;x+=20){pg.beginPath();pg.moveTo(x,0);pg.lineTo(x,h);pg.stroke();}for(let y=0;y<h;y+=20){pg.beginPath();pg.moveTo(0,y);pg.lineTo(w,y);pg.stroke();}const polys=flatFacets(sheet);const all=polys.flatMap(f=>f.poly);const minx=Math.min(0,...all.map(p=>p[0])),maxx=Math.max(sheet.width,...all.map(p=>p[0])),miny=Math.min(0,...all.map(p=>p[1])),maxy=Math.max(sheet.length,...all.map(p=>p[1]));paperMap.scale=Math.min((w-54)/(maxx-minx),(h-100)/(maxy-miny));paperMap.x=w/2-(minx+maxx)/2*paperMap.scale;paperMap.y=h/2+25+(miny+maxy)/2*paperMap.scale;pg.save();pg.setLineDash([3,5]);pg.strokeStyle='#dbe2c440';pg.strokeRect(...point([0,sheet.length]),sheet.width*paperMap.scale,sheet.length*paperMap.scale);pg.restore();const sorted=[...polys].sort((a,b)=>a.z-b.z);for(const [i,f]of sorted.entries()){pg.beginPath();f.poly.forEach((p,j)=>{const [x,y]=point(p);j?pg.lineTo(x,y):pg.moveTo(x,y);});pg.closePath();pg.shadowColor='#07171070';pg.shadowBlur=12;pg.shadowOffsetY=7;const grain=pg.createLinearGradient(0,0,w,h);grain.addColorStop(0,i%2?'#f5edd7':'#fff7e2');grain.addColorStop(1,i%2?'#dccfab':'#eee1bf');pg.fillStyle=grain;pg.fill();pg.shadowBlur=0;pg.shadowOffsetY=0;pg.strokeStyle='#b4a77e';pg.lineWidth=1;pg.stroke();}
for(let i=0;i<sheet.folds.length;i++){const f=sheet.folds[i];pg.strokeStyle=i===Number($('crease').value)?'#b2834ca8':'#9b906655';pg.lineWidth=i===Number($('crease').value)?1.5:.6;pg.setLineDash([3,3]);pg.beginPath();pg.moveTo(...point(f.a));pg.lineTo(...point(f.b));pg.stroke();}pg.setLineDash([]);const pending=line||(guided?guide[guideIndex]?.line?.map(x=>x):null);if(pending){pg.strokeStyle='#53dec5';pg.lineWidth=2;pg.setLineDash([7,5]);pg.beginPath();pg.moveTo(...point(pending[0]));pg.lineTo(...point(pending[1]));pg.stroke();pg.setLineDash([]);for(const p of pending){const q=point(p);pg.fillStyle='#a8f5db';pg.beginPath();pg.arc(q[0],q[1],4,0,Math.PI*2);pg.fill();}}if(drawing){pg.strokeStyle='#86e8d0';pg.lineWidth=2;pg.beginPath();pg.moveTo(...point(drawing.a));pg.lineTo(...point(drawing.b));pg.stroke();}pg.fillStyle='#cfe0c655';pg.font='9px Arial';pg.textAlign='left';pg.fillText('A4 / 80 GSM',15,h-15);}
paper.onpointerdown=e=>{if(guided)return;paper.setPointerCapture(e.pointerId);const p=unpoint(e);if(line){let layers='all';const k=Number($('crease').value)||0;if($('layers').value==='top')layers={top:1};if($('layers').value==='flap')layers={flap:k};if($('layers').value==='other')layers={notFlap:k};commit({type:'fold',a:line[0],b:line[1],move:p,kind:$('kind').value,layers});return;}drawing={a:p,b:p};};paper.onpointermove=e=>{if(drawing){drawing.b=unpoint(e);drawPaper();}};paper.onpointerup=()=>{if(drawing){if(Math.hypot(drawing.a[0]-drawing.b[0],drawing.a[1]-drawing.b[1])>.008){line=[drawing.a,drawing.b];$('paper-caption').textContent='Tap the flap you want to fold over.';}drawing=null;drawPaper();}};paper.onpointercancel=()=>{drawing=null;};
$('scene').onpointerdown=e=>{viewDrag={x:e.clientX,y:e.clientY,lastX:e.clientX,moved:false};$('scene').setPointerCapture(e.pointerId);};$('scene').onpointermove=e=>{if(!viewDrag)return;if(phase==='inspect')scene.rotate((e.clientX-viewDrag.lastX)*.012);if(Math.hypot(e.clientX-viewDrag.x,e.clientY-viewDrag.y)>8)viewDrag.moved=true;viewDrag.lastX=e.clientX;};$('scene').onpointerup=e=>{if(!viewDrag)return;if(phase==='launch'&&viewDrag.y-e.clientY>30){$('speed').value=Math.max(3,Math.min(12,3+(viewDrag.y-e.clientY)/180*9));$('speed').oninput();throwPlane();}else if(phase==='flight'&&!paused&&!viewDrag.moved){const id=scene.pickFan(e.clientX,e.clientY);if(id){flight.toggle(id);fanButtons();toast(id+' switched.');}}viewDrag=null;};$('scene').onpointercancel=()=>viewDrag=null;
window.addEventListener('resize',drawPaper);window.addEventListener('keydown',e=>{if(['INPUT','SELECT','BUTTON'].includes(e.target.tagName))return;if(e.code==='Space'&&phase==='launch'){e.preventDefault();throwPlane();}if(e.code==='Escape'&&phase!=='intro'&&phase!=='result')$('pause').click();});
function frame(now){const dt=Math.min(.035,(now-last)/1000);last=now;if(!paused){time+=dt;if(phase==='flight'&&flight){flight.step(dt);const x=flight.state.pos[0];$('distance').textContent=`${Math.max(0,x).toFixed(1)} m / 48 m`;$('place').textContent=x<10?'THE ENTRANCE HALL':x<24?'THE BALLROOM':x<36?'THE LIBRARY':'THE CONSERVATORY';const milestones=[10,24,36,46];$('checkpoints').querySelectorAll('span').forEach((n,i)=>n.classList.toggle('done',x>=milestones[i]));$('air-tip').textContent=x<10?'Clear the double doors. Rising air waits beyond.':x<16?'Ride the floor vents. Watch the ceiling fan ahead.':x<24?'The ceiling fan blows DOWN. The desk fan pushes forward.':x<36?'Thread the bookshelf gap. Catch the rising air beyond it.':'Catch the garden fan. Clear the planter. Reach the chaise.';if(flight.done)end();}toastTime-=dt;if(toastTime<=0)$('toast').textContent='';}if(scene)scene.draw(phase,flight,time,paused?0:dt);if(phase==='desk')drawPaper();requestAnimationFrame(frame);}
try{scene=await createMansion($('scene'),scenarios.mansion);remake();$('enter').disabled=false;$('enter').textContent=ops.length?'Continue your paper ↗':'Take a sheet of paper ↗';requestAnimationFrame(frame);}catch(e){$('enter').textContent='Unable to load the mansion';document.querySelector('#intro .fine').textContent=e.message+' Try refreshing or a browser with WebGL enabled.';console.error(e);}
