import * as THREE from './vendor/three.module.js';
import {mat3T,mat3Vec,sub} from './physics/vec.mjs';
export async function createMansion(canvas,scenario){
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.7));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
const scene=new THREE.Scene();scene.background=new THREE.Color('#9bafa8');const hallFog=new THREE.Fog('#bec4ae',28,80);scene.fog=hallFog;const camera=new THREE.PerspectiveCamera(65,innerWidth/innerHeight,.035,110);camera.position.set(-1,5.6,.4);camera.lookAt(8,3.7,0);const home=new THREE.Group();scene.add(home);const planeGroup=new THREE.Group();scene.add(planeGroup);let fans=[],flow=[],windowGlow=[],airVisible=true,inspectAngle=0;
const image=await new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>reject(Error('Mansion artwork could not load.'));i.src=new URL('./assets/mansion-materials.png',import.meta.url).href;});
function tile(index,rx=1,ry=1){const c=document.createElement('canvas');c.width=c.height=512;const g=c.getContext('2d');g.drawImage(image,index%2*image.width/2,Math.floor(index/2)*image.height/2,image.width/2,image.height/2,0,0,512,512);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(rx,ry);t.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());return t;}
const material=(color,options={})=>new THREE.MeshStandardMaterial({color,roughness:.7,...options});const mat={plaster:material('#dbd6bb'),wall:material('#d0cbb0',{map:tile(0,18,2),roughness:.9}),wood:material('#573e2b'),panel:material('#294b40'),gold:material('#bca16a',{metalness:.55,roughness:.32}),cream:material('#e7dfc6'),black:material('#293832'),floor:material('#f3d2a2',{map:tile(1,16,3),roughness:.38}),rug:material('#e9e1c8',{map:tile(2)}),painting:material('#e6d9bd',{map:tile(3)}),glass:material('#b7e4e3',{emissive:'#a6d5d1',emissiveIntensity:.45,roughness:.18}),cloth:material('#506d59',{roughness:.96}),bulb:material('#fff1c1',{emissive:'#ffd995',emissiveIntensity:2}),leaf:material('#547348'),fan:material('#7e9b91',{metalness:.45,roughness:.4})};
const boxGeo=new THREE.BoxGeometry(1,1,1);function box(x,y,z,w,h,d,m=mat.wood,parent=home){const o=new THREE.Mesh(boxGeo,m);o.position.set(x,y,z);o.scale.set(w,h,d);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o;}
function cylinder(x,y,z,rt,rb,height,m=mat.gold,parent=home){const o=new THREE.Mesh(new THREE.CylinderGeometry(rt,rb,height,16),m);o.position.set(x,y,z);o.castShadow=true;parent.add(o);return o;}
function sphere(x,y,z,r,m,parent=home){const o=new THREE.Mesh(new THREE.SphereGeometry(r,12,8),m);o.position.set(x,y,z);parent.add(o);return o;}
function torus(x,y,z,r,t,m,rot=[0,0,0],parent=home){const o=new THREE.Mesh(new THREE.TorusGeometry(r,t,7,36),m);o.position.set(x,y,z);o.rotation.set(...rot);parent.add(o);return o;}
scene.add(new THREE.HemisphereLight('#f3efda','#627a64',1.55));const sun=new THREE.DirectionalLight('#ffdfad',2.8);sun.position.set(7,14,-10);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-14;sun.shadow.camera.right=35;sun.shadow.camera.top=15;sun.shadow.camera.bottom=-15;sun.shadow.normalBias=.04;sun.target.position.set(16,0,0);scene.add(sun,sun.target);const fill=new THREE.DirectionalLight('#b5dce5',1.1);fill.position.set(30,8,10);scene.add(fill);
box(24.5,-.12,0,55,.24,8.6,mat.floor);box(24.5,6.6,0,55,.25,8.4,mat.cream);box(24.5,3.2,-4.14,55,6.4,.25,mat.wall);box(24.5,3.2,4.14,55,6.4,.25,mat.wall);
for(const z of [-3.98,3.98]){box(24.5,.72,z,55,1.44,.12,mat.panel);box(24.5,.14,z,55,.21,.21,mat.cream);box(24.5,1.44,z,55,.08,.22,mat.gold);box(24.5,1.53,z,55,.10,.18,mat.cream);box(24.5,6.18,z,55,.18,.3,mat.cream);box(24.5,5.97,z,55,.06,.17,mat.gold);for(let x=-2;x<52;x+=1.8){box(x,.76,z-Math.sign(z)*.08,.07,1.02,.07,mat.gold);box(x+.84,.27,z-Math.sign(z)*.08,1.62,.05,.07,mat.gold);box(x+.84,1.23,z-Math.sign(z)*.08,1.62,.05,.07,mat.gold);}}
// Doorway geometry comes from the collision data; decorative trim sits outside each opening.
for(const solid of scenario.solids){if(['left wall','right wall','ceiling','staircase','chandelier','chandelier chain','banquet table','bookshelf','planter'].includes(solid.name))continue;const b=solid.box,sz=b.max.map((v,i)=>v-b.min[i]);if(sz.some(x=>x<=0))continue;box(...b.min.map((v,i)=>v+sz[i]/2),...sz,solid.name==='library ceiling'?mat.wood:mat.panel);}
for(const [x,height,width]of [[10,4.4,2.6],[24,3.2,2.4],[36,2.9,4.4]]){for(const z of [-width/2-.13,width/2+.13]){box(x-.10,height/2,z,.30,height,.21,mat.cream);box(x-.27,height/2,z,.08,height,.07,mat.gold);cylinder(x-.4,height/2,z+Math.sign(z)*.35,.16,.22,height,mat.cream);cylinder(x-.4,.15,z+Math.sign(z)*.35,.3,.3,.3,mat.cream);cylinder(x-.4,height-.1,z+Math.sign(z)*.35,.3,.25,.2,mat.gold);}box(x-.15,height+.15,0,.4,.3,width+.8,mat.cream);box(x-.36,height+.31,0,.10,.08,width+1.05,mat.gold);}
for(const x of [2,7,15,20,31,40,47]){const z=-3.94;box(x,3.65,z,2,3.6,.08,mat.wood);box(x,3.65,z+.06,1.75,3.35,.04,mat.glass);box(x,3.65,z+.11,.06,3.35,.05,mat.cream);box(x,3.65,z+.11,1.75,.06,.05,mat.cream);box(x,2.5,z+.11,1.75,.06,.05,mat.cream);box(x,4.8,z+.11,1.75,.06,.05,mat.cream);for(const dx of [-1.18,1.18]){for(let k=0;k<5;k++){const curtain=cylinder(x+dx+(k-2)*.065,3.55,z+.30,.055,.10,3.9,mat.cloth);curtain.rotation.x=.04*Math.sign(dx);windowGlow.push(curtain);}sphere(x+dx,5.62,z+.23,.13,mat.gold);}box(x,5.57,z+.23,2.8,.13,.18,mat.gold);box(x,1.75,z+.2,2.4,.13,.44,mat.cream);
// Soft rectangles of sunlight on the parquet, with window mullion shadows.
const rayMat=new THREE.MeshBasicMaterial({color:'#fff0bd',transparent:true,opacity:.10,depthWrite:false,side:THREE.DoubleSide});const shaft=new THREE.Mesh(new THREE.PlaneGeometry(2,6.2),rayMat);shaft.position.set(x+1.9,2,-1.1);shaft.rotation.set(-.62,.55,.18);home.add(shaft);const patch=new THREE.Mesh(new THREE.PlaneGeometry(3.7,2.3),new THREE.MeshBasicMaterial({color:'#ffe5a3',transparent:true,opacity:.14,depthWrite:false}));patch.rotation.x=-Math.PI/2;patch.rotation.z=-.3;patch.position.set(x+2,.015,.2);home.add(patch);}
for(const x of [3,7.5,15,21,31,40,47]){const z=3.91;box(x,3.4,z,1.85,2.0,.12,mat.gold);box(x,3.4,z-.09,1.64,1.80,.07,mat.black);const picture=new THREE.Mesh(new THREE.PlaneGeometry(1.49,1.64),mat.painting);picture.position.set(x,3.4,z-.15);picture.rotation.y=Math.PI;home.add(picture);box(x,4.54,z-.22,1.2,.07,.12,mat.gold);}
for(const [x,w]of [[4,9],[17,11],[30,8],[44,12]]){const rug=new THREE.Mesh(new THREE.PlaneGeometry(w,2.5),mat.rug);rug.rotation.x=-Math.PI/2;rug.position.set(x,.021,0);rug.receiveShadow=true;home.add(rug);}
// The staircase stays out of the throwing lane, just as in the collision world.
for(let i=0;i<18;i++)box(-2.9+i*.22,(i+1)*.255/2,-2.6,.23,(i+1)*.255,2.6,mat.wood);for(let i=0;i<12;i++)cylinder(-2.7+i*.34,1.2+i*.24,-1.35,.035,.05,1.15,mat.gold);const rail=box(-.8,3.4,-1.35,4.6,.09,.10,mat.wood);rail.rotation.z=.6;
// Chandelier silhouettes match the physical hazard boxes.
for(const solid of scenario.solids.filter(s=>s.name==='chandelier')){const b=solid.box,x=(b.min[0]+b.max[0])/2,y=(b.min[1]+b.max[1])/2,z=(b.min[2]+b.max[2])/2;const rr=(b.max[2]-b.min[2])/2*.78;cylinder(x,(y+6.4)/2,z,.026,.026,6.4-y,mat.gold);torus(x,y-.12,z,rr,.035,mat.gold,[Math.PI/2,0,0]);for(let i=0;i<8;i++){const a=i*Math.PI/4,px=x+Math.cos(a)*rr,pz=z+Math.sin(a)*rr;cylinder(px,y,pz,.035,.04,.28,mat.gold);sphere(px,y+.2,pz,.07,mat.bulb);const crystal=sphere(px,y-.29,pz,.052,mat.glass);crystal.scale.y=2;}const light=new THREE.PointLight('#ffd999',13,9,2);light.position.set(x,y-.2,z);home.add(light);}
// Ballroom furniture and library shelves use the same occupied boxes as the course.
box(17,.78,-2.3,8,.14,1.4,mat.wood);for(const x of [13.3,20.7])for(const z of [-2.85,-1.75])cylinder(x,.37,z,.055,.07,.74,mat.wood);for(const x of [14,16,18,20]){cylinder(x,.94,-2.3,.13,.1,.17,mat.cream);sphere(x,1.12,-2.3,.17,mat.leaf);}
for(const solid of scenario.solids.filter(s=>s.name==='bookshelf')){const b=solid.box,c=b.min.map((v,i)=>(v+b.max[i])/2),sz=b.max.map((v,i)=>v-b.min[i]);box(...c,...sz,mat.wood);for(let y=.3;y<3.4;y+=.6){box(c[0]-.34,y,c[2],.08,.07,sz[2],mat.gold);for(let n=0;n<15;n++){const z=b.min[2]+.1+n*(sz[2]-.2)/15;box(c[0]-.355,y+.22,z,.10,.25+(n%4)*.04,.08,material(['#796d49','#486351','#9a6250','#586e75'][n%4]));}}}
for(const [x,z]of [[1,3.5],[8,-3.4],[22,3.5],[35,-3.5],[41.6,0],[48,3.2]]){const potY=x===41.6?.38:.3;const pot=cylinder(x,potY,z,.28,.20,potY*2,mat.cream);for(let n=0;n<8;n++){const a=n*Math.PI/4;const leaf=sphere(x+Math.cos(a)*.22,potY*2+.2+(n%3)*.16,z+Math.sin(a)*.22,.19,mat.leaf);leaf.scale.set(.65,2.2,.65);leaf.rotation.z=Math.cos(a)*.4;}}
// A low chaise marks the destination; the collision goal is its surrounding landing zone.
box(47.7,.28,0,2.7,.18,1.2,mat.wood);box(47.7,.46,0,2.5,.28,1.08,material('#b6aa7e'));box(48.8,.8,0,.20,.8,1.08,mat.cloth);for(const z of [-.43,.43])for(const x of [46.6,48.7])cylinder(x,.13,z,.04,.055,.26,mat.gold);
const pickables=[];for(const source of scenario.airSources||[]){if(source.type==='fan'){const root=new THREE.Group();root.position.fromArray(source.position);const dir=new THREE.Vector3(...source.direction).normalize();root.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,1),dir);home.add(root);const radius=source.radius*.8;torus(0,0,0,radius,.025,mat.gold,[0,0,0],root);torus(0,0,.10,radius,.018,mat.gold,[0,0,0],root);for(let i=0;i<12;i++){const a=i*Math.PI/6;const spoke=box(0,0,.11,radius*2,.009,.009,mat.gold,root);spoke.rotation.z=a;}const blades=new THREE.Group();root.add(blades);for(let i=0;i<4;i++){const blade=new THREE.Mesh(new THREE.SphereGeometry(radius*.53,12,6),mat.fan);blade.scale.set(.75,.3,.08);blade.position.set(Math.cos(i*Math.PI/2)*radius*.48,Math.sin(i*Math.PI/2)*radius*.48,0);blade.rotation.z=i*Math.PI/2+.3;blades.add(blade);}sphere(0,0,.13,radius*.14,mat.gold,root);if(source.id!=='ceiling fan'){const stand=box(0,-radius-.2,-.1,.09,.5,.09,mat.fan,root);box(0,-radius-.43,-.1,radius*1.3,.07,.3,mat.black,root);}const pick=new THREE.Mesh(new THREE.SphereGeometry(radius*1.3,12,8),new THREE.MeshBasicMaterial({visible:false}));pick.userData.fan=source.id;root.add(pick);pickables.push(pick);fans.push({source,root,blades});}
if(source.type==='vent'){const b=source.box,x=(b.min[0]+b.max[0])/2,z=(b.min[2]+b.max[2])/2;box(x,.035,z,b.max[0]-b.min[0],.07,b.max[2]-b.min[2],mat.black);for(let n=0;n<14;n++)box(b.min[0]+(n+.5)*(b.max[0]-b.min[0])/14,.079,z,.04,.015,b.max[2]-b.min[2],mat.gold);}}
// Air particles occupy the actual stream volumes. Their motion is a visual cue, not a force.
for(const source of scenario.airSources.filter(s=>s.type==='fan'||s.type==='vent')){const pos=new Float32Array(54*3);const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(pos,3));const points=new THREE.Points(geo,new THREE.PointsMaterial({color:'#ccead5',size:.033,transparent:true,opacity:.56,depthWrite:false}));home.add(points);flow.push({source,points,pos});}
const dustPos=new Float32Array(160*3);for(let i=0;i<160;i++){dustPos[i*3]=(i*3.731)%52;dustPos[i*3+1]=.4+(i*.971)%5.4;dustPos[i*3+2]=Math.sin(i*43)*3.5;}const dustGeo=new THREE.BufferGeometry();dustGeo.setAttribute('position',new THREE.BufferAttribute(dustPos,3));home.add(new THREE.Points(dustGeo,new THREE.PointsMaterial({color:'#fff1c3',size:.012,transparent:true,opacity:.4})));
let builtPlane=null;function setPlane(built,pl){while(planeGroup.children.length){const o=planeGroup.children.pop();o.geometry?.dispose();o.material?.dispose();}const rotation=mat3T(pl.bodyToBuild);for(const [index,facet]of built.facets.entries()){const points=(facet.poly3||facet.poly).map(p=>mat3Vec(rotation,sub(p,pl.cgBuild))),vertices=[];for(let i=1;i<points.length-1;i++)vertices.push(...points[0],...points[i],...points[i+1]);const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));geo.computeVertexNormals();const m=material(index%3===0?'#e9ddba':'#fff7df',{side:THREE.DoubleSide,roughness:.87,polygonOffset:true,polygonOffsetFactor:index*.15});const mesh=new THREE.Mesh(geo,m);mesh.castShadow=true;mesh.receiveShadow=true;planeGroup.add(mesh);const outline=new THREE.LineLoop(new THREE.BufferGeometry().setFromPoints(points.map(p=>new THREE.Vector3(...p))),new THREE.LineBasicMaterial({color:'#a49575',transparent:true,opacity:.6}));planeGroup.add(outline);}builtPlane=pl;}
const raycaster=new THREE.Raycaster();function pickFan(x,y){raycaster.setFromCamera(new THREE.Vector2(x/innerWidth*2-1,-y/innerHeight*2+1),camera);return raycaster.intersectObjects(pickables,false)[0]?.object.userData.fan;}
const from=new THREE.Vector3(),look=new THREE.Vector3();let previousMode='';function draw(mode,flight,t,dt=.016){const inspection=mode==='inspect',running=mode==='flight'||mode==='result';home.visible=!inspection;planeGroup.visible=mode!=='intro'&&mode!=='desk';if(inspection){scene.background.set('#263e35');scene.fog=null;planeGroup.position.set(0,1,0);planeGroup.rotation.set(.15,inspectAngle,0);camera.position.set(-.37,1.24,.37);camera.lookAt(0,1,0);}else{scene.background.set('#9bafa8');scene.fog=hallFog;if(running&&flight){planeGroup.position.fromArray(flight.state.pos);const q=flight.state.q;planeGroup.quaternion.set(q[1],q[2],q[3],q[0]);const [x,y,z]=flight.state.pos;from.set(x-1.15,Math.max(.4,Math.min(6,y+.34)),z+.26);look.set(x+5,y-.35,z);if(previousMode!==mode||dt===0)camera.position.copy(from);else camera.position.lerp(from,1-Math.exp(-dt*9));camera.lookAt(look);}else{planeGroup.position.set(.3,5.2,0);planeGroup.rotation.set(0,0,0);const cinematic=mode==='intro'||mode==='desk';from.set(cinematic?-1.8:-.9,cinematic?4.6:5.55,cinematic?1.3:.32);camera.position.lerp(from,.06);camera.lookAt(cinematic?9:7,cinematic?2.7:3.9,0);}for(const fan of fans){const on=flight?flight.air.isOn(fan.source.id,flight.state.t):fan.source.on!==false;fan.blades.rotation.z+=on?dt*19:0;fan.root.scale.setScalar(on?1:1);}
for(const {source,points,pos}of flow){const on=flight?flight.air.isOn(source.id,flight.state.t):source.on!==false;points.visible=airVisible&&on;for(let i=0;i<54;i++){const p=((t*.32+i/54)%1),a=i*2.399;if(source.type==='fan'){const dir=new THREE.Vector3(...source.direction).normalize(),len=p*source.reach,rr=source.radius*(.4+p)*(.35+(i%5)/6);const cross=new THREE.Vector3(0,1,0);if(Math.abs(dir.y)>.9)cross.set(1,0,0);cross.cross(dir).normalize();const up=new THREE.Vector3().crossVectors(dir,cross);const v=new THREE.Vector3(...source.position).addScaledVector(dir,len).addScaledVector(cross,Math.cos(a)*rr).addScaledVector(up,Math.sin(a)*rr);pos.set([v.x,v.y,v.z],i*3);}else{const b=source.box;pos[i*3]=b.min[0]+((i*.618)%1)*(b.max[0]-b.min[0]);pos[i*3+1]=p*b.max[1];pos[i*3+2]=b.min[2]+((i*.317)%1)*(b.max[2]-b.min[2]);}}points.geometry.attributes.position.needsUpdate=true;}for(let i=0;i<windowGlow.length;i++)windowGlow[i].rotation.x=.04+Math.sin(t*.7+i)*.015;}
previousMode=mode;renderer.render(scene,camera);}
window.addEventListener('resize',()=>{renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();});return {draw,setPlane,pickFan,rotate:v=>inspectAngle+=v,showAir:value=>airVisible=value,renderer,scene,camera};}

