import {PATH,ROAD,CARS,roadPoint,rng} from './arena.mjs';
const load=src=>new Promise(resolve=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>resolve(null);im.src=src;});
const art={cars:[],dirt:null};let ground=null;export const ready=Promise.all([...Array.from({length:6},(_,i)=>load('assets/top-car-'+i+'.webp')),load('assets/dirt.webp')]).then(a=>{art.cars=a.slice(0,6);art.dirt=a[6];ground=makeGround();});
function roadPath(g){g.beginPath();PATH.forEach((p,i)=>i?g.lineTo(p.x,p.y):g.moveTo(p.x,p.y));g.closePath();}
function tire(g,x,y,r=.85){g.fillStyle='#090e0bcc';g.beginPath();g.ellipse(x+.17,y+.25,r*1.1,r*.92,0,0,7);g.fill();g.fillStyle='#272c28';g.strokeStyle='#4c5144';g.lineWidth=.15;g.beginPath();g.arc(x,y,r,0,7);g.fill();g.stroke();g.fillStyle='#0c130f';g.beginPath();g.arc(x,y,r*.40,0,7);g.fill();}
function makeGround(){const c=document.createElement('canvas');c.width=1440;c.height=1920;const g=c.getContext('2d');g.scale(12,12);g.translate(60,80);g.fillStyle='#434a32';g.fillRect(-60,-80,120,160);if(art.dirt){const outside=g.createPattern(art.dirt,'repeat');outside.setTransform(new DOMMatrix().scale(.05));g.save();g.globalAlpha=.30;g.fillStyle=outside;g.fillRect(-60,-80,120,160);g.restore();}const random=rng(427);for(let i=0;i<14000;i++){const x=random()*120-60,y=random()*160-80;g.fillStyle=['#353e2e','#5c6242','#69704a','#242e27'][i%4];g.globalAlpha=.4;g.beginPath();g.arc(x,y,random()*.2+.035,0,7);g.fill();g.globalAlpha=1;}
 roadPath(g);g.lineJoin='round';g.lineCap='round';g.strokeStyle='#111913';g.lineWidth=ROAD*2+3;g.stroke();g.strokeStyle='#a59164';g.lineWidth=ROAD*2+1;g.stroke();let pat;if(art.dirt){pat=g.createPattern(art.dirt,'repeat');pat.setTransform(new DOMMatrix().scale(.035));}g.strokeStyle=pat||'#88734d';g.lineWidth=ROAD*2;g.stroke();g.strokeStyle='#75644833';g.stroke();
 for(const offset of [-3.1,3.1]){g.beginPath();PATH.forEach((p,i)=>{const q=PATH[(i+1)%160],a=Math.atan2(q.y-p.y,q.x-p.x);const x=p.x-Math.sin(a)*offset,y=p.y+Math.cos(a)*offset;i?g.lineTo(x,y):g.moveTo(x,y);});g.closePath();g.lineWidth=.36;g.strokeStyle='#34372955';g.stroke();}
 for(let i=0;i<160;i+=2){const p=PATH[i],q=PATH[(i+1)%160],a=Math.atan2(q.y-p.y,q.x-p.x);for(const side of [-1,1]){const x=p.x-Math.sin(a)*(ROAD+.5)*side,y=p.y+Math.cos(a)*(ROAD+.5)*side;if(roadPoint(x,y).d<ROAD-.1)continue;tire(g,x,y,.72);}}
 for(const cy of [-25,25]){g.save();g.translate(0,cy);g.rotate(cy<0?-.15:.2);for(let i=0;i<3;i++){g.fillStyle=['#667165','#78543a','#547473'][i];g.strokeStyle='#15251e';g.lineWidth=.4;g.fillRect(-5+i*2,-6+i*3,6,4);g.strokeRect(-5+i*2,-6+i*3,6,4);g.strokeStyle='#bbc0a455';g.lineWidth=.16;for(let j=0;j<7;j++){g.beginPath();g.moveTo(-4.8+i*2+j*.8,-5.7+i*3);g.lineTo(-4.8+i*2+j*.8,-2.3+i*3);g.stroke();}}for(let j=0;j<12;j++)tire(g,Math.sin(j*3)*5,Math.cos(j*2)*7,.6);g.restore();}
 for(let i=0;i<100;i++){const x=random()*112-56,y=random()*152-76;if(roadPoint(x,y).d<ROAD+3)continue;g.save();g.translate(x,y);g.rotate(random()*6);g.fillStyle=['#5c6a5a','#956c3e','#92753f','#607879'][i%4];g.fillRect(-1,-.4,2+random()*2,.8);g.restore();}
 g.save();g.translate(0,0);g.rotate(-Math.PI/2);g.font='900 2.6px sans-serif';g.textAlign='center';g.fillStyle='#e8d4a522';g.fillText('THE BONEYARD',0,0);g.restore();return c;}
export class DerbyView{constructor(){this.camera={x:0,y:0};this.particles=[];this.marks=[];this.lastT=-1;this.matchId='';this.shake=0;this.frame=0;}
 ingest(m,motion){if(this.matchId!==m.id){this.matchId=m.id;this.particles=[];this.marks=[];this.lastT=-1;}if(this.lastT===m.t)return;this.lastT=m.t;for(const e of m.events){const count=motion?(e.type==='explode'?65:e.type==='blast'?42:e.type==='impact'?28:e.type==='crate'?15:5):e.type==='explode'?8:0;this.shake=Math.max(this.shake,motion?Math.min(.7,e.power*.02):0);for(let i=0;i<count;i++){const ang=Math.random()*6.28,speed=Math.random()*(e.power*.18+3),life=.3+Math.random()*(e.type==='explode'?1.5:.7);this.particles.push({x:e.x,y:e.y,vx:Math.cos(ang)*speed,vy:Math.sin(ang)*speed,life,max:life,size:i%5===0?.9:.15+Math.random()*.3,angle:ang,color:i%5===0?CARS[e.car%6]?.color||'#aaa':i%2?'#ffc879':'#f36d2f',kind:i%5===0?'panel':'spark'});}if(e.type==='explode'||e.type==='blast')this.marks.push({x:e.x,y:e.y,burn:true});if(e.power>12)for(let j=0;j<3;j++)this.marks.push({x:e.x+Math.sin(j*2+e.car)*3,y:e.y+Math.cos(j*2+e.car)*3,panel:true,a:j*2,color:CARS[e.car%6]?.color||'#999'});}if(motion&&this.frame++%3===0)for(const c of m.cars)if(!c.dead&&Math.hypot(c.vx,c.vy)>4){const side=-c.vx*Math.sin(c.angle)+c.vy*Math.cos(c.angle);if(c.input.brake||Math.abs(side)>1.5)this.marks.push({x:c.x,y:c.y,a:c.angle,burn:false});}this.marks=this.marks.slice(-1800);this.particles=this.particles.slice(-500);}
 draw(g,w,h,m,me,{menu=false,motion=true,dt=.016}={}){this.ingest(m,motion);this.shake*=Math.exp(-8*dt);let target=m.cars[me];if(target.dead)target=m.cars.find(c=>!c.dead)||target;
 const scale=menu?Math.min(w/88,h/133):Math.max(w/115,Math.min(w/64,h/70));const limitX=Math.max(0,47-w/scale/2),limitY=Math.max(24,65-(h-160)/scale/2);const tx=menu?0:Math.max(-limitX,Math.min(limitX,target.x+target.vx*.3)),ty=menu?0:Math.max(-limitY,Math.min(limitY,target.y+target.vy*.28));const follow=1-Math.exp(-7*dt);this.camera.x+=(tx-this.camera.x)*follow;this.camera.y+=(ty-this.camera.y)*follow;
 g.fillStyle='#39412d';g.fillRect(0,0,w,h);g.save();g.translate(w/2+(motion?(Math.random()-.5)*this.shake*scale:0),h/2+(motion?(Math.random()-.5)*this.shake*scale:0));g.scale(scale,scale);g.translate(-this.camera.x,-this.camera.y);if(ground)g.drawImage(ground,-60,-80,120,160);
 for(const mark of this.marks){g.save();g.translate(mark.x,mark.y);if(mark.burn){const grad=g.createRadialGradient(0,0,0,0,0,4);grad.addColorStop(0,'#0c110cdc');grad.addColorStop(1,'#141a0f00');g.fillStyle=grad;g.fillRect(-4,-4,8,8);}else if(mark.panel){g.rotate(mark.a);g.fillStyle='#10191177';g.fillRect(-.7,-.3,1.5,.7);g.fillStyle=mark.color;g.fillRect(-.8,-.45,1.35,.6);g.strokeStyle='#292c22';g.lineWidth=.12;g.strokeRect(-.8,-.45,1.35,.6);}else{g.rotate(mark.a);g.fillStyle='#151b1660';g.fillRect(-1.8,-1.4,2,.24);g.fillRect(-1.8,1.2,2,.24);}g.restore();}
 for(const p of m.props){g.save();g.translate(p.x,p.y);if(p.dead){g.fillStyle='#161b1466';g.beginPath();g.ellipse(0,0,1.8,1.2,0,0,7);g.fill();g.strokeStyle='#8b6948';g.lineWidth=.3;g.beginPath();g.moveTo(-1,-.6);g.lineTo(.8,.4);g.moveTo(.5,-1);g.lineTo(-.4,.8);g.stroke();}else if(p.kind==='fuel'){g.fillStyle='#352c20';g.beginPath();g.arc(.15,.2,1.3,0,7);g.fill();g.fillStyle='#b45c35';g.strokeStyle='#ebba6b';g.lineWidth=.15;g.beginPath();g.arc(0,0,1.05,0,7);g.fill();g.stroke();g.fillStyle='#272e20';g.fillRect(-.8,-.15,1.6,.3);g.beginPath();g.arc(.45,-.3,.18,0,7);g.fill();}else{g.rotate(p.id*.75);g.fillStyle='#8b603c';g.fillRect(-1,-1,2,2);g.strokeStyle='#cda46d';g.lineWidth=.18;g.strokeRect(-1,-1,2,2);g.beginPath();g.moveTo(-1,-1);g.lineTo(1,1);g.moveTo(1,-1);g.lineTo(-1,1);g.stroke();}g.restore();}
 for(const c of [...m.cars].sort((a,b)=>Number(b.dead)-Number(a.dead))){g.save();g.translate(c.x,c.y);if(c.id===me&&!c.dead&&!menu){g.strokeStyle='#aee6af';g.lineWidth=.22;g.beginPath();g.arc(0,0,4.1,0,7);g.stroke();}g.rotate(c.angle+Math.PI/2);g.fillStyle='#11181188';g.fillRect(-1.5,-2.9,3.4,6.2);const im=art.cars[c.skin];if(im){g.save();if([2,4,5].includes(c.skin))g.rotate(Math.PI);if(c.dead)g.filter='grayscale(1) brightness(.35)';else if(c.hp<40)g.filter='saturate(.55) brightness(.72)';g.drawImage(im,-1.65,-3.2,3.3,6.4);g.restore();}else{g.fillStyle=CARS[c.skin].color;g.fillRect(-1.6,-3.1,3.2,6.2);}if(c.hp<70){g.strokeStyle='#172219bb';g.lineWidth=.15;g.beginPath();g.moveTo(-1.2,-1.5);g.lineTo(.6,-.5);g.lineTo(-.4,.7);g.stroke();}if(c.input.boost&&c.boost>1&&!c.dead){g.fillStyle='#79d8ed';g.beginPath();g.moveTo(-.7,2.9);g.lineTo(-.2,2.9);g.lineTo(-.45,4.6+Math.sin(m.t*40)*.5);g.fill();}if(c.flash>0&&!c.dead){g.fillStyle='#ffc98344';g.fillRect(-1.5,-2.9,3,5.8);}g.restore();
 if(!menu){g.textAlign='center';g.font='700 '+(c.id===me?1.5:1.2)+'px system-ui';g.fillStyle=c.id===me?'#d7ffc7':c.dead?'#a6a28c':'#f3e4bd';g.shadowColor='#111';g.shadowBlur=2;g.fillText(c.dead?'WRECK':c.id===me?'YOU':c.name,c.x,c.y-4.7);g.shadowBlur=0;if(!c.dead&&c.id!==me){g.fillStyle='#151d16';g.fillRect(c.x-2,c.y-4.2,4,.42);g.fillStyle=c.hp<35?'#e38153':'#bad08b';g.fillRect(c.x-2,c.y-4.2,4*c.hp/100,.42);}}
 if((c.hp<40||c.dead)&&!menu){for(let i=0;i<5;i++){const t=(m.t*.65+i*.2)%1;g.fillStyle=`rgba(24,28,22,${.35*(1-t)})`;g.beginPath();g.arc(c.x+t*2,c.y-t*4, .5+t*1.6,0,7);g.fill();}if(c.dead){for(let i=0;i<3;i++){g.fillStyle=i%2?'#f6b65099':'#e5763288';g.beginPath();g.ellipse(c.x+Math.sin(m.t*12+i)*.5,c.y-.5, .6,.9+Math.sin(m.t*9+i)*.3,0,0,7);g.fill();}}}}
 for(const p of this.particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=Math.exp(-2*dt);p.vy*=Math.exp(-2*dt);g.save();g.globalAlpha=Math.max(0,p.life/p.max);g.translate(p.x,p.y);g.rotate(p.angle+p.life*6);g.fillStyle=p.color;g.fillRect(-p.size,-p.size*.3,p.size*2,p.size*.6);g.restore();}this.particles=this.particles.filter(p=>p.life>0);g.restore();
 // Small map makes the full figure-eight visible while the camera follows the car.
 if(!menu){const mw=w<600?63:83,mh=mw*1.43,mx=w-mw-13,my=91;g.save();g.translate(mx+mw/2,my+mh/2);g.fillStyle='#14251cbd';g.fillRect(-mw/2,-mh/2,mw,mh);g.scale(mw/90,mh/130);roadPath(g);g.strokeStyle='#a89f7966';g.lineWidth=ROAD*1.45;g.stroke();for(const c of m.cars){g.fillStyle=c.dead?'#363e2c':c.id===me?'#c6ffd0':'#f8a36b';g.beginPath();g.arc(c.x,c.y,c.id===me?3:2,0,7);g.fill();}g.restore();}
}
}
