export const VERSION=2,ROAD=12.8,RADIUS=1.45;
export const CARS=[{name:'Rustbucket',color:'#dc8649'},{name:'Sidewinder',color:'#55bab3'},{name:'Delivery of Doom',color:'#e4d5b3'},{name:'Last Fare',color:'#d8b948'},{name:'Bad Debt',color:'#a87aa7'},{name:'Scrap Wagon',color:'#84965d'}];
export const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
export const pathPoint=t=>({x:27*Math.sin(2*t),y:47*Math.sin(t)});
export const PATH=Array.from({length:160},(_,i)=>pathPoint(i/160*Math.PI*2));
export function roadPoint(x,y){let best=Infinity,px=0,py=0,index=0;for(let i=0;i<PATH.length;i++){const a=PATH[i],b=PATH[(i+1)%PATH.length],dx=b.x-a.x,dy=b.y-a.y,t=clamp(((x-a.x)*dx+(y-a.y)*dy)/(dx*dx+dy*dy),0,1),qx=a.x+dx*t,qy=a.y+dy*t,d=(x-qx)**2+(y-qy)**2;if(d<best){best=d;px=qx;py=qy;index=i;}}return{x:px,y:py,d:Math.sqrt(best),index};}
export function rng(seed){return()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};}
const angleDiff=(a,b)=>Math.atan2(Math.sin(a-b),Math.cos(a-b));
export function makeMatch(profiles=[{}],id='derby',seed=789){const slots=[.45,1.36,2.4,3.6,4.5,5.55],used=new Set(profiles.map((p,i)=>p.skin??i)),available=[0,1,2,3,4,5].filter(i=>!used.has(i));return{version:VERSION,id,seed,t:0,countdown:3,finished:false,winner:null,eliminated:[],pairs:{},events:[],cars:slots.map((t,i)=>{const p=pathPoint(t),v=profiles[i]||{};return{id:i,name:String(v.name||['YOU','RIVET','BOLT','SPANNER','RATCHET','DIESEL'][i]).slice(0,18),human:i<profiles.length,skin:clamp(Math.floor(v.skin??available[i-profiles.length]??i),0,5),x:p.x,y:p.y,angle:Math.atan2(47*Math.cos(t),54*Math.cos(2*t)),vx:0,vy:0,hp:100,boost:100,dead:false,kills:0,damage:0,flash:0,lastHit:-10,stuck:0,reverse:0,input:{throttle:0,steer:0,brake:false,boost:false,aim:null}};}),props:Array.from({length:20},(_,i)=>{const t=i/20*Math.PI*2+.14,p=pathPoint(t),a=Math.atan2(47*Math.cos(t),54*Math.cos(2*t)),side=i%2?1:-1;return{id:i,x:p.x-Math.sin(a)*side*9.1,y:p.y+Math.cos(a)*side*9.1,kind:i%4===0?'fuel':'crate',hp:1,dead:false};})};}
export function control(c,v={}){c.input={throttle:clamp(Number(v.throttle)||0,-1,1),steer:clamp(Number(v.steer)||0,-1,1),brake:!!v.brake,boost:!!v.boost,aim:v.aim&&Number.isFinite(v.aim.x)&&Number.isFinite(v.aim.y)?{x:clamp(v.aim.x,-1,1),y:clamp(v.aim.y,-1,1)}:null};}
function ai(c,m,dt){const alive=m.cars.filter(o=>!o.dead&&o.id!==c.id);if(!alive.length)return control(c,{});let target=alive.reduce((a,b)=>Math.hypot(a.x-c.x,a.y-c.y)<Math.hypot(b.x-c.x,b.y-c.y)?a:b);if(m.t<16&&Math.abs(c.y)>10)target={x:0,y:0,vx:0,vy:0};let dx=target.x-c.x,dy=target.y-c.y,dist=Math.hypot(dx,dy),point={x:target.x+target.vx*.35,y:target.y+target.vy*.35};let clear=true;for(let i=1;i<=5;i++)if(roadPoint(c.x+dx*i/6,c.y+dy*i/6).d>ROAD-2)clear=false;
 if(!clear){const from=roadPoint(c.x,c.y),to=roadPoint(target.x,target.y);let delta=(to.index-from.index+160)%160;if(delta>80)delta-=160;const sign=delta>=0?1:-1;point=PATH[(from.index+sign*9+160)%160];}
 const speed=Math.hypot(c.vx,c.vy);c.stuck=speed<2?c.stuck+dt:0;if(c.stuck>1.3){c.reverse=1.0;c.stuck=0;}c.reverse=Math.max(0,c.reverse-dt);let error=angleDiff(Math.atan2(point.y-c.y,point.x-c.x),c.angle);if(c.reverse>0){control(c,{throttle:-.8,steer:-Math.sign(error||1)});return;}
 if(dist<7&&Math.abs(error)>1.0){c.reverse=.85;control(c,{throttle:-1,steer:0});return;}control(c,{throttle:clamp((dist/18)*Math.max(.3,1-Math.abs(error)*.55),.28,1),steer:clamp(error*2,-1,1),boost:clear&&dist>7&&dist<29&&Math.abs(error)<.23&&c.boost>25,brake:Math.abs(error)>1.8&&speed>12});}
function hurt(m,c,amount,source){if(c.dead||amount<=0)return;amount=Math.min(c.hp,amount);c.hp=Math.max(0,c.hp-amount);c.flash=.24;c.lastHit=m.t;if(source&&source.id!==c.id)source.damage+=amount;m.events.push({type:'hit',x:c.x,y:c.y,power:amount,car:c.id});if(c.hp<=0){c.dead=true;c.input={throttle:0,steer:0,boost:false,brake:false,aim:null};if(source)source.kills++;m.eliminated.push(c.id);m.events.push({type:'explode',x:c.x,y:c.y,power:55,car:c.id});}}
export function bumpers(c){const f={x:Math.cos(c.angle)*1.65,y:Math.sin(c.angle)*1.65};return[{x:c.x+f.x,y:c.y+f.y},{x:c.x-f.x,y:c.y-f.y}];}
function carContact(a,b){let result=null;for(const p of bumpers(a))for(const q of bumpers(b)){let dx=q.x-p.x,dy=q.y-p.y,d=Math.hypot(dx,dy);if(d<RADIUS*2&&(!result||d<result.d)){if(d<.001){dx=.001;dy=0;d=.001;}result={nx:dx/d,ny:dy/d,d};}}return result;}
export function step(m,dt){if(m.finished)return;dt=clamp(dt,0,1/30);m.t+=dt;m.events=[];if(m.countdown>0){m.countdown=Math.max(0,m.countdown-dt);return;}
 for(const c of m.cars){c.flash=Math.max(0,c.flash-dt);if(c.dead){c.vx*=Math.exp(-3*dt);c.vy*=Math.exp(-3*dt);c.x+=c.vx*dt;c.y+=c.vy*dt;continue;}if(!c.human)ai(c,m,dt);const i=c.input;let fx=Math.cos(c.angle),fy=Math.sin(c.angle),forward=c.vx*fx+c.vy*fy,steer=i.steer;if(i.aim&&Math.hypot(i.aim.x,i.aim.y)>.1){const desired=Math.atan2(i.aim.y,i.aim.x)+(i.throttle<0?Math.PI:0);steer=clamp(angleDiff(desired,c.angle)*2,-1,1);if(i.throttle<0)steer=-steer;}
 const turn=(i.brake?3.1:2.1)*clamp(Math.abs(forward)/5,.12,1)*(forward<-.5?-1:1);c.angle+=steer*turn*dt;
 fx=Math.cos(c.angle);fy=Math.sin(c.angle);forward=c.vx*fx+c.vy*fy;let lateral=-c.vx*fy+c.vy*fx;
 const boosting=i.boost&&c.boost>2&&i.throttle>0;c.boost=clamp(c.boost+(boosting?-32:10)*dt,0,100);
 forward+=i.throttle*(boosting?25:15)*dt;forward*=Math.exp(-(i.brake?3.3:Math.abs(i.throttle)<.05?1.9:.60)*dt);forward=clamp(forward,-10,boosting?33:25);lateral*=Math.exp(-(i.brake?1.6:7)*dt);c.vx=fx*forward-fy*lateral;c.vy=fy*forward+fx*lateral;c.x+=c.vx*dt;c.y+=c.vy*dt;
 for(const b of bumpers(c)){const road=roadPoint(b.x,b.y);if(road.d>ROAD-RADIUS){const nx=(road.x-b.x)/road.d,ny=(road.y-b.y)/road.d,depth=road.d-(ROAD-RADIUS);c.x+=nx*depth;c.y+=ny*depth;const vn=c.vx*nx+c.vy*ny;if(vn<0){c.vx-=vn*1.3*nx;c.vy-=vn*1.3*ny;if(vn< -7&&m.t-c.lastHit>.4)hurt(m,c,Math.min(10,(-vn-5)*.55),null);}}}
 for(const p of m.props){if(p.dead||Math.hypot(c.x-p.x,c.y-p.y)>3.5)continue;if(Math.hypot(c.vx,c.vy)<3)continue;p.dead=true;m.events.push({type:p.kind==='fuel'?'blast':'crate',x:p.x,y:p.y,power:p.kind==='fuel'?40:15,car:c.id});if(p.kind==='fuel'){for(const other of m.cars)if(!other.dead&&Math.hypot(other.x-p.x,other.y-p.y)<10)hurt(m,other,Math.max(0,24-Math.hypot(other.x-p.x,other.y-p.y)*2),c.id===other.id?null:c);}else c.boost=clamp(c.boost+8,0,100);}
 }
 for(let i=0;i<6;i++)for(let j=i+1;j<6;j++){const a=m.cars[i],b=m.cars[j];if(a.dead&&b.dead)continue;const hit=carContact(a,b);if(!hit)continue;const{nx,ny,d}=hit,depth=RADIUS*2-d,wa=a.dead?.18:.5,wb=b.dead?.18:.5,total=wa+wb;a.x-=nx*depth*wa/total;a.y-=ny*depth*wa/total;b.x+=nx*depth*wb/total;b.y+=ny*depth*wb/total;const closing=(a.vx-b.vx)*nx+(a.vy-b.vy)*ny;if(closing<=0)continue;const impulse=closing*.67;a.vx-=impulse*nx;a.vy-=impulse*ny;b.vx+=impulse*nx;b.vy+=impulse*ny;const pair=i+':'+j;if(closing>3&&m.t-(m.pairs[pair]??-10)>.32){m.pairs[pair]=m.t;const force=clamp((closing-2)*1.65,2,48),frontA=Math.max(0,Math.cos(a.angle)*nx+Math.sin(a.angle)*ny),frontB=Math.max(0,-Math.cos(b.angle)*nx-Math.sin(b.angle)*ny);hurt(m,a,force*(1-frontA*.65),b.dead?null:b);hurt(m,b,force*(1-frontB*.65),a.dead?null:a);m.events.push({type:'impact',x:(a.x+b.x)/2,y:(a.y+b.y)/2,power:force,car:a.id});}}
 const alive=m.cars.filter(c=>!c.dead);if(alive.length<=1){m.finished=true;m.winner=alive[0]?.id??-1;m.events.push({type:'winner',car:m.winner,x:0,y:0,power:0});}
}
export const freshSave=()=>({skin:0,sound:true,motion:true,wins:0,matches:0,kills:0,claimed:[]});
export function readSave(raw){try{const v=JSON.parse(raw);if(!v)return freshSave();return{skin:clamp(Math.floor(Number(v.skin)||0),0,5),sound:v.sound!==false,motion:v.motion!==false,wins:clamp(Number(v.wins)||0,0,1e6),matches:clamp(Number(v.matches)||0,0,1e6),kills:clamp(Number(v.kills)||0,0,1e6),claimed:Array.isArray(v.claimed)?v.claimed.filter(v=>typeof v==='string').slice(-100):[]};}catch{return freshSave();}}
export function record(save,m,id){if(!m.finished||save.claimed.includes(m.id))return false;save.matches++;if(m.winner===id)save.wins++;save.kills+=m.cars[id].kills;save.claimed.push(m.id);save.claimed=save.claimed.slice(-100);return true;}
export function validMatch(m){return !!(m&&m.version===2&&typeof m.id==='string'&&m.id.length<90&&Number.isFinite(m.t)&&m.t>=0&&m.t<86400&&Number.isFinite(m.countdown)&&m.countdown>=0&&m.countdown<=3&&Array.isArray(m.cars)&&m.cars.length===6&&Array.isArray(m.props)&&m.props.length===20&&Array.isArray(m.events)&&m.events.length<100&&m.events.every(e=>e&&typeof e.type==='string'&&['x','y','power','car'].every(k=>Number.isFinite(e[k])))&&m.props.every(p=>p&&Number.isFinite(p.x)&&Number.isFinite(p.y)&&Math.abs(p.x)<70&&Math.abs(p.y)<80)&&m.cars.every((c,i)=>c&&c.id===i&&typeof c.name==='string'&&c.name.length<=18&&Number.isInteger(c.skin)&&c.skin>=0&&c.skin<6&&['x','y','vx','vy','angle','hp','boost','kills','damage','flash'].every(k=>Number.isFinite(c[k]))&&Math.abs(c.x)<90&&Math.abs(c.y)<95&&c.hp>=0&&c.hp<=100&&c.boost>=0&&c.boost<=100&&c.input));}
