import {initAds,maybeInterstitial,bannerOnScreens} from './arcade-ads.js';
import {CARS,makeMatch,control,step,readSave,record,validMatch,clamp} from './arena.mjs';
import {DerbyView,ready} from './arena-draw.mjs';import {room} from './room.mjs';
const $=id=>document.getElementById(id),canvas=$('game'),g=canvas.getContext('2d'),view=new DerbyView(),saveKey='scrapyard-showdown.derby-v2';let save;try{save=readSave(localStorage.getItem(saveKey));}catch{save=readSave(null);}let match=null,demo=makeMatch([],'demo'),me=0,inMatch=false,paused=false,remotePaused=false,network=false,finishedShown=false,w=innerWidth,h=innerHeight,last=0,acc=0,netAcc=0,netEvents=[],bannerUntil=0,toastTimer,stick=null,keys=new Set(),buttons={reverse:false,brake:false,boost:false},input={throttle:0,steer:0,aim:null,brake:false,boost:false};demo.countdown=0;
function resize(){w=innerWidth;h=innerHeight;const d=Math.min(devicePixelRatio||1,2);canvas.width=w*d;canvas.height=h*d;g.setTransform(d,0,0,d,0,0);}addEventListener('resize',resize);resize();
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3500);}
function persist(){try{localStorage.setItem(saveKey,JSON.stringify(save));}catch{toast('Storage unavailable. Progress lasts while this page stays open.');}menuLabels();}
function menuLabels(){$('selectedCar').textContent=CARS[save.skin].name.toUpperCase();$('record').textContent=save.matches?`${save.wins} WINS / ${save.matches} DERBIES / ${save.kills} KNOCKOUTS`:'DRIVE IT. WRECK IT. BE THE LAST ONE MOVING.';}
let audio,osc,gain;
function soundStart(){if(!save.sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();if(!osc){osc=audio.createOscillator();osc.type='sawtooth';gain=audio.createGain();gain.gain.value=0;osc.connect(gain).connect(audio.destination);osc.start();}}catch{}}
function crash(e){if(!save.sound||!audio||e.type==='winner')return;const o=audio.createOscillator(),v=audio.createGain();o.type='triangle';o.frequency.setValueAtTime(e.type==='explode'?90:170,audio.currentTime);o.frequency.exponentialRampToValueAtTime(25,audio.currentTime+.22);v.gain.setValueAtTime(Math.min(.13,e.power*.004),audio.currentTime);v.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.35);o.connect(v).connect(audio.destination);o.start();o.stop(audio.currentTime+.36);}
function resetInput(){stick=null;keys.clear();buttons={reverse:false,brake:false,boost:false};input={throttle:0,steer:0,aim:null,brake:false,boost:false};$('knob').style.transform='';for(const b of document.querySelectorAll('.pressed'))b.classList.remove('pressed');}
function makeInput(){const dx=stick?.dx||0,dy=stick?.dy||0,len=Math.min(1,Math.hypot(dx,dy)),keyboardThrottle=Number(keys.has('w')||keys.has('ArrowUp'))-Number(keys.has('s')||keys.has('ArrowDown'));input={throttle:buttons.reverse?-1:keyboardThrottle||(len>.10?len:buttons.boost||keys.has('Shift')?1:0),steer:Number(keys.has('d')||keys.has('ArrowRight'))-Number(keys.has('a')||keys.has('ArrowLeft')),aim:len>.10?{x:dx,y:dy}:null,brake:buttons.brake||keys.has(' '),boost:buttons.boost||keys.has('Shift')};return input;}
function closeDialogs(){for(const d of document.querySelectorAll('dialog[open]'))d.close();}
function enter(m,guest=false){closeDialogs();match=m;me=guest?1:0;network=net.state.connected;inMatch=true;paused=false;remotePaused=false;finishedShown=false;acc=0;netEvents=[];resetInput();view.camera.x=m.cars[me].x;view.camera.y=m.cars[me].y;$('home').hidden=true;$('hud').hidden=false;$('spectate').hidden=true;$('controls').hidden=false;$('driveHint').textContent=matchMedia('(pointer:fine)').matches?'WASD / arrows · Shift boost · Space handbrake':'Drag the stick to drive · Release to brake';$('driverLabel').textContent=CARS[m.cars[me].skin].name.toUpperCase();document.body.dataset.view='derby';document.documentElement.requestFullscreen?.().catch(()=>{});soundStart();}
const profile=()=>({name:$('driverName').value,skin:save.skin});
function solo(){if(net.state.connected)net.leave();network=false;enter(makeMatch([{name:'YOU',skin:save.skin}],crypto.randomUUID(),Date.now()>>>0));}
$('play').onclick=solo;
function home(notify=true){if(inMatch)maybeInterstitial().catch(e=>console.warn('Interstitial not shown:',e?.message||e));if(notify&&network&&net.state.connected)net.send('exit',{});network=false;inMatch=false;match=null;paused=false;resetInput();closeDialogs();$('home').hidden=false;$('hud').hidden=true;document.body.dataset.view='menu';menuLabels();}
function openSettings(){if(inMatch){paused=true;resetInput();if(network&&!net.state.host)net.send('input',{...input,paused:true});}$('sound').checked=save.sound;$('motion').checked=save.motion;$('quit').hidden=!inMatch;$('pauseNote').textContent=network?'Both drivers must return before the derby continues.':'';$('settings').showModal();soundStart();}
$('pause').onclick=openSettings;$('settingsOpen').onclick=openSettings;$('resume').onclick=()=>{$('settings').close();paused=false;resetInput();if(network&&!net.state.host)net.send('input',{...input,paused:false});soundStart();};$('quit').onclick=()=>home();$('sound').onchange=()=>{save.sound=$('sound').checked;persist();soundStart();};$('motion').onchange=()=>{save.motion=$('motion').checked;persist();};
const joy=$('joystick');joy.addEventListener('pointerdown',e=>{if(!inMatch||paused||match.cars[me].dead)return;e.preventDefault();joy.setPointerCapture(e.pointerId);const b=joy.getBoundingClientRect();stick={id:e.pointerId,x:b.x+b.width/2,y:b.y+b.height/2,dx:0,dy:0};moveStick(e);soundStart();});function moveStick(e){if(!stick||stick.id!==e.pointerId)return;const dx=(e.clientX-stick.x)/43,dy=(e.clientY-stick.y)/43,len=Math.max(1,Math.hypot(dx,dy));stick.dx=dx/len;stick.dy=dy/len;$('knob').style.transform=`translate(${stick.dx*36}px,${stick.dy*36}px)`;makeInput();}joy.addEventListener('pointermove',moveStick);const drop=e=>{if(stick?.id===e.pointerId){stick=null;$('knob').style.transform='';makeInput();}};joy.addEventListener('pointerup',drop);joy.addEventListener('pointercancel',drop);joy.addEventListener('lostpointercapture',drop);
for(const[id,key]of [['boost','boost'],['reverse','reverse'],['handbrake','brake']]){const b=$(id);b.addEventListener('pointerdown',e=>{if(!inMatch||paused||match.cars[me].dead)return;e.preventDefault();b.setPointerCapture(e.pointerId);buttons[key]=true;b.classList.add('pressed');soundStart();});const off=()=>{buttons[key]=false;b.classList.remove('pressed');};b.addEventListener('pointerup',off);b.addEventListener('pointercancel',off);b.addEventListener('lostpointercapture',off);}
addEventListener('keydown',e=>{if(e.target.matches('input'))return;if(e.key==='Escape'&&inMatch&&!paused){openSettings();return;}if(!inMatch||paused)return;if(['w','a','s','d','W','A','S','D','ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' ','Shift'].includes(e.key)){e.preventDefault();keys.add(e.key.length===1?e.key.toLowerCase():e.key);makeInput();}});addEventListener('keyup',e=>{keys.delete(e.key.length===1?e.key.toLowerCase():e.key);makeInput();});addEventListener('blur',resetInput);document.addEventListener('visibilitychange',()=>{if(document.hidden&&inMatch&&!paused&&!finishedShown)openSettings();});
function chooseCars(){const grid=$('carGrid');grid.replaceChildren();CARS.forEach((c,i)=>{const b=document.createElement('button');b.className=save.skin===i?'selected':'';b.dataset.skin=i;const img=document.createElement('img');img.src='assets/top-car-'+i+'.webp';img.alt=c.name;if([2,4,5].includes(i))img.style.transform='rotate(180deg)';const t=document.createElement('span');t.textContent=c.name;b.append(img,t);b.onclick=()=>{save.skin=i;persist();chooseCars();};grid.append(b);});if(!$('cars').open)$('cars').showModal();}$('carsOpen').onclick=chooseCars;$('carsClose').onclick=()=>$('cars').close();
for(const d of document.querySelectorAll('dialog'))d.addEventListener('cancel',e=>{e.preventDefault();if(d.id==='settings')$('resume').click();else if(d.id==='result')home();else d.close();});
function result(){if(finishedShown)return;finishedShown=true;resetInput();record(save,match,me);persist();const winner=match.cars[match.winner];$('resultEyebrow').textContent=match.winner===me?'LAST CAR STANDING':'DERBY OVER';$('resultTitle').textContent=match.winner===me?'Still rolling.':winner?winner.name+' survives.':'Mutual destruction.';$('resultStats').textContent=`${match.cars[me].kills} knockouts Â· ${Math.round(match.cars[me].damage)} damage dealt Â· ${Math.floor((match.t-3)/60)}:${String(Math.floor((match.t-3)%60)).padStart(2,'0')}`;const order=match.winner>=0?[match.winner,...[...match.eliminated].reverse()]:[...match.eliminated].reverse();$('standings').replaceChildren();order.forEach((id,index)=>{const c=match.cars[id],row=document.createElement('div'),a=document.createElement('span'),b=document.createElement('span');if(id===me)row.className='you';a.textContent=`${index+1}. ${c.name}`;b.textContent=c.dead?'WRECKED':Math.ceil(c.hp)+'% LEFT';row.append(a,b);$('standings').append(row);});$('again').textContent=network?'BACK TO THE FRIEND ROOM â†—':'ONE MORE WRECK â†—';$('result').showModal();}
$('again').onclick=()=>{if(network){home();$('friends').showModal();}else solo();};$('resultHome').onclick=()=>home();
const net=room((type,data)=>{if(type==='status'){$('roomCode').textContent=data.code?data.code.slice(0,4)+' '+data.code.slice(4):'â€”';$('share').disabled=!data.code;$('accept').hidden=data.status!=='request';$('startTogether').hidden=!(data.host&&data.connected);$('leave').hidden=data.status==='offline';$('roomStatus').textContent=data.error||(data.status==='connecting'?'Connectingâ€¦':data.status==='hosting'?'Share the link. Keep this game open.':data.status==='request'?data.friend.name+' wants to join.':data.connected?'Connected to '+data.friend.name+(data.host?'. Ready when you are.':'. Waiting for the host.'):'Two mates + four bots. Six cars. One survivor.');}
 else if(type==='start'&&!net.state.host&&validMatch(data?.match)){enter(data.match,true);}
 else if(type==='input'&&net.state.host&&network&&match){control(match.cars[1],data);remotePaused=!!data?.paused;}
 else if(type==='snapshot'&&!net.state.host&&network&&data?.match?.id===match?.id&&validMatch(data.match)){match=data.match;remotePaused=!!data.paused;for(const e of match.events)crash(e);}
 else if((type==='exit'||type==='disconnect')&&network){home(false);toast(type==='disconnect'?'Your mate disconnected. Rejoin or play solo.':'Your mate returned to the menu.');}});
$('friendsOpen').onclick=()=>$('friends').showModal();$('friendsClose').onclick=()=>$('friends').close();$('host').onclick=()=>net.host(profile());$('join').onclick=()=>net.join($('joinCode').value,profile());$('accept').onclick=()=>net.accept(profile());$('leave').onclick=()=>net.leave();$('startTogether').onclick=()=>{if(!net.state.connected||!net.state.host)return;const m=makeMatch([profile(),net.state.friend],crypto.randomUUID());net.send('start',{match:m});enter(m);};$('share').onclick=async()=>{const code=net.state.code;if(!code)return;const url=location.origin+location.pathname+'?room='+code;try{if(navigator.share)await navigator.share({title:'Scrapyard Showdown',text:'Six junk cars. Last one standing wins. Wreck me if you can.',url});else{await navigator.clipboard.writeText(url);toast('Invite link copied.');}}catch(e){if(e.name!=='AbortError')toast('Use room code '+code+' with this game link.');}};
const invite=new URL(location.href).searchParams.get('room');if(invite&&/^[A-HJ-NP-Z2-9]{8}$/.test(invite)){$('joinCode').value=invite;$('friends').showModal();}
function tick(now){const dt=Math.min(.05,(now-last)/1000||0);last=now;let renderMatch=match||demo;if(inMatch&&match){if(!paused&&!remotePaused&&!match.finished&&(!network||net.state.host)){acc+=dt;const events=[];while(acc>=1/60){if(!match.cars[me].dead)control(match.cars[me],makeInput());step(match,1/60);events.push(...match.events);acc-=1/60;}match.events=events.slice(-90);netEvents.push(...events);netEvents=netEvents.slice(-90);for(const e of events){crash(e);if(e.type==='explode'){$('banner').textContent=e.car===me?'YOUâ€™RE WRECKED':match.cars[e.car].name+' IS OUT';bannerUntil=now+1600;}}}
 if(network){netAcc+=dt;if(netAcc>.05){netAcc=0;if(net.state.host){net.send('snapshot',{match:{...match,events:netEvents},paused:paused||remotePaused});netEvents=[];}else net.send('input',{...makeInput(),paused});}}
 const c=match.cars[me],alive=match.cars.filter(c=>!c.dead).length;$('alive').textContent=alive;$('healthBar').style.width=c.hp+'%';$('healthBar').style.background=c.hp<30?'#e78557':'#a4d488';$('healthText').textContent=c.dead?'WRECKED':Math.ceil(c.hp)+'% BODY';$('boostBar').style.width=c.boost+'%';$('controls').hidden=c.dead;$('spectate').hidden=!c.dead||match.finished;$('driveHint').hidden=match.t>12||c.dead;
 if(match.countdown>0)$('banner').textContent=Math.ceil(match.countdown);else if(remotePaused&&!paused)$('banner').textContent='RIVAL PAUSED';else if(now>bannerUntil)$('banner').textContent='';if(match.finished)result();if(gain){gain.gain.setTargetAtTime((save.sound&&!paused&&!remotePaused&&!c.dead&&!match.finished)?0.019:0,audio.currentTime,.12);osc.frequency.setTargetAtTime(28+Math.hypot(c.vx,c.vy)*3,audio.currentTime,.09);}}
 else{if(gain)gain.gain.setTargetAtTime(0,audio.currentTime,.1);if(!document.querySelector('dialog[open]')){step(demo,Math.min(dt,1/30));if(demo.finished)demo=makeMatch([],'demo'+now);renderMatch=demo;}}
 view.draw(g,w,h,renderMatch,me,{menu:!inMatch,motion:save.motion,dt});requestAnimationFrame(tick);}
menuLabels();document.body.dataset.view='menu';initAds().catch(e=>console.warn('Ads unavailable:',e?.message||e));bannerOnScreens('view',['menu']);await ready;requestAnimationFrame(tick);
