// Four Corners: the category bank (Claude, 29 Sep 2026).
// tier: 1 plain, 2 needs some knowledge, 3 wordplay ("___ BALL"), 4 tricky
// (hidden words, palindromes). members: what can appear as tiles.
// also: words that honestly fit this group but are not used as tiles; the
// maker uses them to refuse a day where a tile would fit two groups.
// Every member is one word, capitals, at most 11 letters. Tests enforce it.

export const BANK = [
  // ---- tier 1
  { name: 'Australian birds', tier: 1, members: ['GALAH', 'EMU', 'KOOKABURRA', 'MAGPIE', 'COCKATOO', 'BROLGA', 'LORIKEET'], also: ['EAGLE', 'HAWK', 'FALCON', 'KITE', 'OSPREY', 'HARRIER', 'SWAN', 'DUCK', 'OWL', 'CROW', 'PELICAN'] },
  { name: 'Card games', tier: 1, members: ['POKER', 'SNAP', 'RUMMY', 'BRIDGE', 'EUCHRE', 'CANASTA', 'BLACKJACK'], also: ['SOLITAIRE', 'PATIENCE'] },
  { name: 'Planets', tier: 1, members: ['MERCURY', 'VENUS', 'MARS', 'JUPITER', 'SATURN', 'NEPTUNE', 'URANUS'], also: ['EARTH'] },
  { name: 'Pasta', tier: 1, members: ['PENNE', 'FUSILLI', 'RIGATONI', 'LINGUINE', 'ORZO', 'FARFALLE', 'RAVIOLI'], also: ['SPAGHETTI', 'LASAGNE'] },
  { name: 'Dog breeds', tier: 1, members: ['KELPIE', 'BEAGLE', 'BOXER', 'POODLE', 'PUG', 'CORGI', 'LABRADOR'], also: ['HEELER', 'TERRIER', 'GREYHOUND'] },
  { name: 'Cheeses', tier: 1, members: ['BRIE', 'FETA', 'GOUDA', 'CHEDDAR', 'HALLOUMI', 'CAMEMBERT', 'PARMESAN'], also: [] },
  { name: 'National capitals', tier: 1, members: ['CANBERRA', 'OTTAWA', 'NAIROBI', 'LIMA', 'OSLO', 'CAIRO', 'HANOI'], also: ['WELLINGTON', 'LONDON', 'PARIS', 'ROME', 'TOKYO'] },
  { name: 'Musical instruments', tier: 1, members: ['VIOLIN', 'TUBA', 'OBOE', 'CELLO', 'BANJO', 'HARP', 'DIDGERIDOO'], also: ['PICCOLO', 'FLUTE', 'DRUM', 'PIANO', 'KEYBOARD', 'ACCORDION', 'TRUMPET', 'HORN'] },
  { name: 'Trees', tier: 1, members: ['OAK', 'ELM', 'BIRCH', 'WILLOW', 'CEDAR', 'WATTLE', 'JARRAH'], also: ['GUM', 'PINE', 'ASH', 'PALM'] },
  { name: 'Gemstones', tier: 1, members: ['RUBY', 'OPAL', 'JADE', 'TOPAZ', 'GARNET', 'SAPPHIRE', 'EMERALD'], also: ['DIAMOND', 'PEARL', 'AMETHYST'] },
  { name: 'Weather', tier: 1, members: ['HAIL', 'SLEET', 'DRIZZLE', 'FOG', 'THUNDER', 'SNOW', 'CYCLONE'], also: ['RAIN', 'WIND', 'STORM'] },
  { name: 'Rocks', tier: 1, members: ['GRANITE', 'BASALT', 'SHALE', 'MARBLE', 'SLATE', 'SANDSTONE', 'PUMICE'], also: ['LIMESTONE', 'FLINT'] },
  { name: 'Mining machines', tier: 1, members: ['DOZER', 'GRADER', 'LOADER', 'EXCAVATOR', 'DRAGLINE', 'SCRAPER'], also: ['SHOVEL', 'TRUCK'] },
  { name: 'Fruit', tier: 1, members: ['MANGO', 'LYCHEE', 'PAPAYA', 'PEACH', 'PLUM', 'FIG', 'KIWI'], also: ['APPLE', 'LEMON', 'ORANGE', 'PEAR', 'LIME', 'MELON', 'BANANA', 'AVO', 'AVOCADO', 'DATE', 'CHERRY', 'OLIVE', 'TOMATO'] },
  { name: 'Vegetables', tier: 1, members: ['LEEK', 'KALE', 'TURNIP', 'PARSNIP', 'CELERY', 'CARROT', 'RADISH'], also: ['PEA', 'BEAN', 'ONION', 'POTATO', 'PUMPKIN'] },
  { name: 'Units of length', tier: 1, members: ['METRE', 'INCH', 'FOOT', 'YARD', 'MILE', 'FATHOM', 'FURLONG'], also: ['CHAIN', 'LEAGUE', 'HAND'] },
  { name: 'Shades of blue', tier: 1, members: ['NAVY', 'TEAL', 'COBALT', 'AZURE', 'INDIGO', 'CYAN', 'SAPPHIRE'], also: ['SKY', 'ROYAL', 'BLUE'] },
  { name: 'Shades of red', tier: 1, members: ['SCARLET', 'CRIMSON', 'RUBY', 'MAROON', 'CHERRY', 'CLARET', 'CARMINE'], also: ['GARNET', 'BRICK', 'RED', 'CARDINAL'] },
  { name: 'Cocktails', tier: 1, members: ['MOJITO', 'MARGARITA', 'NEGRONI', 'DAIQUIRI', 'MARTINI', 'SPRITZ'], also: [] },
  { name: 'Coffee orders', tier: 1, members: ['LATTE', 'MOCHA', 'MACCHIATO', 'CAPPUCCINO', 'ESPRESSO', 'PICCOLO'], also: ['LONGBLACK', 'FLATWHITE'] },
  { name: 'Dances', tier: 1, members: ['TANGO', 'SALSA', 'WALTZ', 'FOXTROT', 'RUMBA', 'POLKA', 'CHARLESTON'], also: ['JIVE', 'SAMBA'] },
  { name: 'Australian cities', tier: 1, members: ['DARWIN', 'HOBART', 'PERTH', 'CAIRNS', 'MACKAY', 'TOWNSVILLE', 'ADELAIDE'], also: ['CANBERRA', 'SYDNEY', 'MELBOURNE', 'BRISBANE'] },
  { name: 'Bones', tier: 1, members: ['FEMUR', 'TIBIA', 'ULNA', 'RADIUS', 'PATELLA', 'STERNUM', 'SKULL'], also: ['RIB', 'SPINE'] },
  { name: 'Footwear', tier: 1, members: ['BOOT', 'SANDAL', 'THONG', 'LOAFER', 'SNEAKER', 'CLOG', 'STILETTO'], also: ['SLIPPER', 'PUMP'] },
  { name: 'Tools', tier: 1, members: ['HAMMER', 'CHISEL', 'SPANNER', 'WRENCH', 'PLIERS', 'SAW', 'DRILL'], also: ['SHOVEL', 'SCREWDRIVER', 'AXE'] },
  { name: 'Ocean creatures', tier: 1, members: ['SHARK', 'DOLPHIN', 'OCTOPUS', 'SQUID', 'STINGRAY', 'DUGONG', 'WHALE'], also: ['PRAWN', 'OYSTER', 'SCALLOP', 'MUSSEL', 'FLATHEAD', 'BARRAMUNDI', 'CRAB', 'SALMON', 'JELLYFISH', 'STARFISH'] },
  { name: 'Metals', tier: 1, members: ['COPPER', 'NICKEL', 'ZINC', 'IRON', 'TIN', 'LEAD', 'COBALT'], also: ['GOLD', 'SILVER', 'STEEL', 'BRONZE', 'PLATINUM'] },
  { name: 'Olympic sports', tier: 1, members: ['ARCHERY', 'FENCING', 'ROWING', 'JUDO', 'DIVING', 'SAILING', 'BOXING'], also: ['SWIMMING', 'CYCLING'] },
  { name: 'Spices', tier: 1, members: ['CUMIN', 'TURMERIC', 'NUTMEG', 'CLOVE', 'PAPRIKA', 'SAFFRON', 'CINNAMON'], also: ['PEPPER'] },
  { name: 'Herbs', tier: 1, members: ['BASIL', 'THYME', 'SAGE', 'MINT', 'DILL', 'OREGANO', 'ROSEMARY'], also: ['PARSLEY', 'CORIANDER'] },
  { name: 'Board games', tier: 1, members: ['MONOPOLY', 'SCRABBLE', 'CLUEDO', 'RISK', 'CHESS', 'BACKGAMMON', 'TWISTER'], also: ['DRAUGHTS', 'CHECKERS'] },
  { name: 'Breads', tier: 1, members: ['SOURDOUGH', 'BAGUETTE', 'CIABATTA', 'FOCACCIA', 'NAAN', 'BRIOCHE', 'DAMPER'], also: ['TOAST', 'ROLL'] },
  { name: 'Seafood on the menu', tier: 1, members: ['PRAWN', 'BARRAMUNDI', 'OYSTER', 'CALAMARI', 'SCALLOP', 'MUSSEL', 'FLATHEAD'], also: ['OCTOPUS', 'SQUID', 'SALMON', 'CRAB', 'LOBSTER'] },
  { name: 'Marsupials', tier: 1, members: ['WOMBAT', 'KOALA', 'QUOKKA', 'BILBY', 'NUMBAT', 'POSSUM', 'WALLABY'], also: ['KANGAROO'] },
  { name: 'Star signs', tier: 1, members: ['ARIES', 'TAURUS', 'GEMINI', 'LEO', 'VIRGO', 'LIBRA', 'SCORPIO'], also: ['CANCER', 'PISCES'] },
  { name: 'Painters', tier: 1, members: ['MONET', 'DALI', 'PICASSO', 'REMBRANDT', 'VERMEER', 'KLIMT', 'MATISSE'], also: [] },
  { name: 'Hats', tier: 1, members: ['BEANIE', 'AKUBRA', 'FEDORA', 'BERET', 'BOWLER', 'SOMBRERO', 'TRILBY'], also: ['CAP', 'HELMET'] },
  { name: 'Fabrics', tier: 1, members: ['DENIM', 'SILK', 'VELVET', 'LINEN', 'TWEED', 'SATIN', 'CORDUROY'], also: ['COTTON', 'WOOL'] },
  { name: 'Wine grapes', tier: 1, members: ['SHIRAZ', 'MERLOT', 'RIESLING', 'MALBEC', 'SEMILLON', 'PINOT', 'TEMPRANILLO'], also: [] },
  { name: 'In space', tier: 1, members: ['ORBIT', 'COMET', 'NEBULA', 'QUASAR', 'PULSAR', 'GALAXY'], also: ['MERCURY', 'VENUS', 'MARS', 'JUPITER', 'SATURN', 'NEPTUNE', 'URANUS', 'MOON', 'STAR', 'SUN', 'ASTEROID'] },
  { name: 'Breakfast', tier: 1, members: ['TOAST', 'PORRIDGE', 'MUESLI', 'PANCAKE', 'OMELETTE', 'CEREAL'], also: ['EGG', 'BACON'] },
  { name: 'Currencies', tier: 1, members: ['DOLLAR', 'EURO', 'YEN', 'PESO', 'RUPEE', 'POUND', 'FRANC'], also: [] },

  // ---- tier 2
  { name: 'Things with keys', tier: 2, members: ['PIANO', 'LOCK', 'MAP', 'KEYBOARD', 'TYPEWRITER'], also: ['ACCORDION'] },
  { name: 'Things with shells', tier: 2, members: ['TURTLE', 'EGG', 'TACO', 'SNAIL', 'OYSTER', 'PEANUT'], also: ['CRAB', 'SCALLOP', 'MUSSEL', 'PRAWN'] },
  { name: 'Things with teeth', tier: 2, members: ['COMB', 'SAW', 'ZIP', 'GEAR', 'SHARK'], also: ['DOG'] },
  { name: 'Poker words', tier: 2, members: ['FLUSH', 'STRAIGHT', 'RIVER', 'BLIND', 'FOLD', 'RAISE', 'CALL'], also: ['BLUFF', 'POT'] },
  { name: 'Chess', tier: 2, members: ['CASTLE', 'CHECK', 'PAWN', 'KNIGHT', 'BISHOP', 'KING', 'QUEEN'], also: ['ROOK', 'MATE'] },
  { name: 'Aussie words for a mate', tier: 2, members: ['MATE', 'COBBER', 'CUZ', 'BRO', 'CHINA'], also: ['DIGGER', 'BUDDY'] },
  { name: 'Aussie words ending in O', tier: 2, members: ['ARVO', 'SERVO', 'BOTTLO', 'SMOKO', 'AVO', 'JOURNO'], also: ['RELLO', 'DOCO'] },
  { name: 'Horse gaits', tier: 2, members: ['WALK', 'TROT', 'CANTER', 'GALLOP', 'PACE'], also: [] },
  { name: 'Greek letters', tier: 2, members: ['ALPHA', 'BETA', 'DELTA', 'SIGMA', 'OMEGA', 'GAMMA', 'THETA'], also: ['PI', 'RHO', 'TAU', 'CHI', 'PSI', 'MU', 'NU', 'XI', 'ETA', 'IOTA', 'KAPPA', 'LAMBDA', 'EPSILON', 'ZETA', 'OMICRON', 'UPSILON', 'PHI'] },
  { name: 'NATO alphabet', tier: 2, members: ['BRAVO', 'CHARLIE', 'DELTA', 'ECHO', 'FOXTROT', 'TANGO', 'KILO', 'ROMEO'], also: ['ALFA', 'ALPHA', 'GOLF', 'HOTEL', 'INDIA', 'JULIETT', 'JULIET', 'LIMA', 'MIKE', 'NOVEMBER', 'OSCAR', 'PAPA', 'QUEBEC', 'SIERRA', 'UNIFORM', 'VICTOR', 'WHISKEY', 'XRAY', 'YANKEE', 'ZULU'] },
  { name: 'The Beatles', tier: 2, members: ['JOHN', 'PAUL', 'GEORGE', 'RINGO'], also: [] },
  { name: 'Cricket', tier: 2, members: ['WICKET', 'OVER', 'BAILS', 'CREASE', 'DUCK', 'YORKER', 'GULLY'], also: ['BOWLER', 'PITCH', 'STUMPS', 'SLIPS', 'BAT', 'SIX', 'FOUR', 'INNINGS'] },
  { name: 'Knots', tier: 2, members: ['REEF', 'BOWLINE', 'HITCH', 'SHEEPSHANK', 'GRANNY', 'SLIPKNOT'], also: [] },
  { name: 'Car parts', tier: 2, members: ['BONNET', 'BOOT', 'CLUTCH', 'AXLE', 'EXHAUST', 'GEARBOX', 'DIFF'], also: ['ENGINE', 'GEAR', 'HORN', 'WHEEL', 'TYRE'] },
  { name: 'Birds of prey', tier: 2, members: ['EAGLE', 'HAWK', 'FALCON', 'KITE', 'OSPREY', 'HARRIER'], also: ['OWL'] },
  { name: 'Beer glasses', tier: 2, members: ['SCHOONER', 'MIDDY', 'POT', 'PINT', 'JUG', 'PONY'], also: [] },
  { name: 'Computer keys', tier: 2, members: ['ENTER', 'ESCAPE', 'SHIFT', 'TAB', 'DELETE', 'HOME', 'CONTROL'], also: ['SPACE', 'END'] },
  { name: 'Australian rivers', tier: 2, members: ['MURRAY', 'DARLING', 'YARRA', 'SWAN', 'FITZROY', 'BURDEKIN', 'DAINTREE'], also: [] },
  { name: 'AFL clubs', tier: 2, members: ['CROWS', 'EAGLES', 'HAWKS', 'SWANS', 'LIONS', 'SAINTS', 'DOCKERS', 'BOMBERS'], also: ['TIGERS', 'MAGPIES', 'CATS', 'BLUES', 'POWER', 'SUNS', 'GIANTS', 'DEMONS', 'KANGAROOS', 'BULLDOGS'] },
  { name: 'Ways to cook an egg', tier: 2, members: ['POACH', 'SCRAMBLE', 'FRY', 'BOIL', 'CODDLE', 'BAKE'], also: [] },

  // ---- tier 3: wordplay
  { name: '___ BALL', tier: 3, members: ['FOOT', 'BASKET', 'NET', 'FIRE', 'EYE', 'MEAT', 'HAND', 'SNOW'], also: ['BASE', 'HAIR'] },
  { name: '___ FISH', tier: 3, members: ['GOLD', 'STAR', 'SWORD', 'CAT', 'JELLY', 'BLOW', 'CRAY'], also: ['SHELL', 'MONK'] },
  { name: '___ STONE', tier: 3, members: ['MILE', 'KEY', 'CORNER', 'SAND', 'LIME', 'BRIM', 'HAIL'], also: ['GRAVE', 'HEAD'] },
  { name: '___ BOARD', tier: 3, members: ['SKATE', 'SURF', 'KEY', 'DASH', 'CUP', 'CLIP', 'SNOW'], also: ['BILL', 'CARD', 'HEAD'] },
  { name: '___ CAKE', tier: 3, members: ['CUP', 'PAN', 'CHEESE', 'SPONGE', 'FRUIT', 'CARROT', 'PATTY'], also: ['FISH'] },
  { name: 'SUN ___', tier: 3, members: ['FLOWER', 'BURN', 'DIAL', 'SET', 'RISE', 'GLASSES', 'DOWNER'], also: ['DECK', 'SHINE', 'SCREEN'] },
  { name: 'FIRE ___', tier: 3, members: ['WORK', 'PLACE', 'FLY', 'MAN', 'ARM', 'WOOD', 'TRUCK'], also: ['BALL', 'SIDE'] },
  { name: 'RING ___', tier: 3, members: ['TONE', 'LEADER', 'MASTER', 'SIDE', 'WORM', 'BARK', 'ROAD'], also: [] },
  { name: '___ LINE', tier: 3, members: ['HEAD', 'DEAD', 'COAST', 'SKY', 'TIME', 'BORDER', 'PUNCH'], also: ['PIPE', 'SHORE'] },
  { name: 'HEAD ___', tier: 3, members: ['LIGHT', 'LINE', 'BAND', 'PHONES', 'MASTER', 'STRONG', 'WIND'], also: ['STONE', 'BOARD'] },
  { name: '___ HOUSE', tier: 3, members: ['LIGHT', 'GREEN', 'WARE', 'FARM', 'BOAT', 'DOG', 'OPERA'], also: ['TREE', 'FIRE'] },
  { name: 'BACK ___', tier: 3, members: ['PACK', 'FIRE', 'YARD', 'BONE', 'HAND', 'STAGE', 'GROUND'], also: ['BOARD'] },
  { name: '___ POT', tier: 3, members: ['JACK', 'TEA', 'HOT', 'FLOWER', 'CRACK', 'LOBSTER', 'CHIMNEY'], also: [] },
  { name: '___ DECK', tier: 3, members: ['POOP', 'SUN', 'TAPE', 'FLIGHT', 'TOP', 'QUARTER'], also: [] },
  { name: 'Parts of a mine', tier: 3, members: ['SHAFT', 'ADIT', 'STOPE', 'DRIVE', 'PORTAL', 'DECLINE', 'WINZE'], also: ['PIT', 'TUNNEL'] },
  { name: 'Footy talk', tier: 3, members: ['MARK', 'BEHIND', 'TORP', 'RUCK', 'SPECKY', 'HANDBALL'], also: ['GOAL', 'KICK'] },
  { name: 'Things that get cracked', tier: 3, members: ['CODE', 'KNUCKLES', 'JOKE', 'SMILE', 'WHIP', 'EGG', 'SAFE'], also: ['NUT', 'CASE'] },
  { name: 'Things you draw', tier: 3, members: ['CURTAINS', 'BATH', 'SWORD', 'BREATH', 'CONCLUSION', 'BLANK', 'STRAWS'], also: ['PICTURE', 'LINE', 'CARD'] },
  { name: 'Things you break', tier: 3, members: ['NEWS', 'EVEN', 'ICE', 'RECORD', 'BREAD', 'WIND', 'SILENCE'], also: ['BONE', 'HEART', 'LAW'] },
  { name: 'Things that run', tier: 3, members: ['NOSE', 'TAP', 'RIVER', 'ENGINE', 'MASCARA', 'CANDIDATE'], also: ['CLOCK'] },
  { name: 'Things you poach', tier: 3, members: ['EGG', 'PEAR', 'SALMON', 'STAFF', 'IVORY'], also: [] },
  { name: 'Things with legs', tier: 3, members: ['TABLE', 'WINE', 'JOURNEY', 'RELAY', 'TRIPOD', 'SPIDER'], also: ['CHAIR'] },
  { name: 'Things with wings', tier: 3, members: ['PLANE', 'ANGEL', 'HOSPITAL', 'STAGE', 'BAT', 'CHICKEN'], also: ['BIRD'] },
  { name: 'Things with pips', tier: 3, members: ['DICE', 'DOMINO', 'LEMON', 'APPLE', 'ORANGE'], also: [] },

  // ---- tier 4: hidden words and letter tricks
  { name: 'Hidden animals', tier: 4, members: ['SCATTER', 'PIRATE', 'PLANT', 'SPIGOT', 'GOATEE', 'DOGMA', 'BOWLING'], also: [] },
  { name: 'Hidden numbers', tier: 4, members: ['OFTEN', 'WEIGHT', 'FREIGHT', 'ANTENNA', 'KITTEN', 'STONE', 'PHONE'], also: [] },
  { name: 'Hidden colours', tier: 4, members: ['SHRED', 'BORED', 'TANGO', 'STANDARD', 'CREDIT'], also: [] },
  { name: 'Hidden countries', tier: 4, members: ['PERUSE', 'MALIBU', 'WOMAN', 'CHADOR', 'INDIANA'], also: [] },
  { name: 'Silent K', tier: 4, members: ['KNIFE', 'KNEE', 'KNOT', 'KNOCK', 'KNIGHT', 'KNUCKLE', 'KNIT'], also: ['KNOW', 'KNEEL'] },
  { name: 'Palindromes', tier: 4, members: ['RADAR', 'LEVEL', 'CIVIC', 'KAYAK', 'ROTOR', 'REFER', 'MADAM'], also: [] },
];
