// Ring Lock levels (Claude). Chapter 1 is LEVELS[0..9].
// ring: {n notches, target notch, links: [[otherRing, factor]]}. Turning a ring
// by dir also turns each linked ring by dir * factor (factor -1 turns it the
// other way). scramble: moves played on the solved board to make the start, so
// a level is always solvable in at most scramble.length moves. moves: the budget.
// Chapter 2 (LEVELS[10..19]) adds optional step, fixed and gate: see sim.mjs.
const R = (n, target = 0, links = [], extra = {}) => ({ n, target, links, ...extra });

export const LEVELS = [
  { id: 1, chapter: 1, name: 'First Turn', objective: 'Turn the ring until its mark sits at the top.',
    rings: [R(6)], scramble: [[0, 1], [0, 1]], moves: 5 },
  { id: 2, chapter: 1, name: 'Two Rings', objective: 'Line up both rings at the top.',
    rings: [R(6), R(6)], scramble: [[0, 1], [1, -1], [1, -1]], moves: 6 },
  { id: 3, chapter: 1, name: 'Three Deep', objective: 'Line up all three rings at the top.',
    rings: [R(8), R(8), R(8)], scramble: [[0, 1], [0, 1], [1, -1], [2, 1], [2, 1], [2, 1]], moves: 9 },
  { id: 4, chapter: 1, name: 'Off Centre', objective: 'Match the pattern: each ring has its own target notch.',
    rings: [R(8, 0), R(8, 2), R(8, 5)], scramble: [[0, -1], [1, 1], [1, 1], [2, -1], [2, -1]], moves: 8 },
  { id: 5, chapter: 1, name: 'Linked', objective: 'The first ring drags the second along. Plan around it.',
    rings: [R(6, 0, [[1, 1]]), R(6)], scramble: [[0, 1], [0, 1], [1, 1]], moves: 6 },
  { id: 6, chapter: 1, name: 'Opposites', objective: 'The first ring turns the second the other way.',
    rings: [R(6, 0, [[1, -1]]), R(6), R(6)], scramble: [[0, 1], [0, 1], [0, 1], [2, 1], [1, -1]], moves: 9 },
  { id: 7, chapter: 1, name: 'Odd Gears', objective: 'Rings with different notch counts share a link.',
    rings: [R(6, 0, [[1, 1]]), R(12), R(8, 0, [[1, 1]])], scramble: [[0, 1], [0, 1], [2, 1], [2, 1], [2, 1]], moves: 10 },
  { id: 8, chapter: 1, name: 'Chain Reaction', objective: 'Each ring nudges the next. Work from the end of the chain.',
    rings: [R(6, 0, [[1, 1]]), R(6, 0, [[2, 1]]), R(6, 0, [[3, -1]]), R(6)], scramble: [[0, 1], [1, 1], [2, 1], [3, 1]], moves: 8 },
  { id: 9, chapter: 1, name: 'Tight Fit', objective: 'Four rings, a pattern, and only six moves.',
    rings: [R(8, 0, [[1, 1]]), R(8, 3), R(8, 0), R(8, 5, [[2, -1]])],
    scramble: [[0, 1], [0, 1], [1, -1], [2, 1], [3, 1], [3, 1]], moves: 6 },
  { id: 10, chapter: 1, name: 'The Lock', objective: 'Four linked rings, mixed sizes, one spare move. Open the lock.',
    rings: [R(6, 0, [[1, 1], [3, -1]]), R(8, 3, [[2, 1]]), R(12, 6, [[3, 1]]), R(6, 2)],
    scramble: [[0, 1], [1, 1], [2, -1], [3, 1], [0, 1], [2, -1]], moves: 7 },

  // Chapter 2: Gates and Gears.
  { id: 11, chapter: 2, name: 'Double Step', objective: 'This ring jumps two notches a turn. Count the jumps.',
    rings: [R(8, 0, [], { step: 2 }), R(6)], scramble: [[0, 1], [0, 1], [1, 1]], moves: 4 },
  { id: 12, chapter: 2, name: 'Odd Count', objective: 'Seven notches and two-notch jumps: it still gets there, the long way round.',
    rings: [R(7, 0, [], { step: 2 }), R(7, 0, [[0, 1]])], scramble: [[0, 1], [0, 1], [0, 1], [1, -1]], moves: 5 },
  { id: 13, chapter: 2, name: 'First Gate', objective: 'The second ring only turns while the first sits at the top.',
    rings: [R(6), R(6, 0, [], { gate: { ring: 0, at: 0 } })], scramble: [[1, 1], [0, 1], [0, 1]], moves: 4 },
  { id: 14, chapter: 2, name: 'Key Notch', objective: 'The gate opens at notch three, not at the top. Open it, turn, then come home.',
    rings: [R(6), R(6, 0, [], { gate: { ring: 0, at: 3 } })],
    scramble: [[0, 1], [0, 1], [0, 1], [1, 1], [1, 1], [0, -1]], moves: 7 },
  { id: 15, chapter: 2, name: 'Frozen Ring', objective: 'The middle ring will not turn by hand. Move it with its neighbours.',
    rings: [R(6, 0, [[1, 1]]), R(6, 0, [], { fixed: true }), R(6, 0, [[1, -1]])],
    scramble: [[0, 1], [0, 1], [2, 1], [2, 1], [2, 1]], moves: 6 },
  { id: 16, chapter: 2, name: 'Jump the Gate', objective: 'Two-notch jumps meet a gate that opens at notch four.',
    rings: [R(8, 0, [], { step: 2 }), R(8, 3, [], { gate: { ring: 0, at: 4 } })],
    scramble: [[0, 1], [0, 1], [1, 1], [1, 1], [0, 1]], moves: 6 },
  { id: 17, chapter: 2, name: 'Two Gates', objective: 'Each gate is held open by the ring before it. Work from the front.',
    rings: [R(6), R(6, 0, [], { gate: { ring: 0, at: 0 } }), R(6, 2, [], { gate: { ring: 1, at: 0 } })],
    scramble: [[2, 1], [2, 1], [1, 1], [0, 1], [0, 1]], moves: 6 },
  { id: 18, chapter: 2, name: 'Frozen Gate', objective: 'A frozen ring holds the gate. Turn its neighbours to free it.',
    rings: [R(8, 0, [[1, 1]]), R(8, 0, [], { fixed: true }), R(8, 0, [], { gate: { ring: 1, at: 0 } }), R(8, 4, [[1, -1]])],
    scramble: [[2, 1], [3, 1], [3, 1], [0, 1], [0, 1]], moves: 6 },
  { id: 19, chapter: 2, name: 'Clockwork', objective: 'Jumps, links and two gates in one tight machine. Six moves at most.',
    rings: [R(8, 0, [[3, 1]], { step: 2 }), R(8, 2, [], { gate: { ring: 0, at: 4 } }), R(8, 0, [], { gate: { ring: 1, at: 2 } }), R(8, 5)],
    scramble: [[2, 1], [0, 1], [0, 1], [1, 1], [1, 1], [0, 1]], moves: 6 },
  { id: 20, chapter: 2, name: 'The Vault', objective: 'Every trick so far, five rings, one spare move. Open the vault.',
    rings: [R(6, 0, [[1, 1]]), R(6, 3, [], { fixed: true }), R(8, 0, [[3, 1]], { step: 2, gate: { ring: 1, at: 3 } }),
      R(8, 4, [], { gate: { ring: 0, at: 0 } }), R(6, 0, [[1, -1]])],
    scramble: [[2, 1], [3, 1], [0, 1], [4, 1], [0, 1], [4, 1], [2, 1]], moves: 8 },

  // Chapter 3: Blocked Notches (LEVELS[20..29]). Adds block: see sim.mjs.
  { id: 21, chapter: 3, name: 'Blocked Notch', objective: 'Notch three is blocked on the first ring. Turn the other way round.',
    rings: [R(6, 0, [], { block: [3] }), R(6)], scramble: [[0, 1], [0, 1], [1, -1]], moves: 4 },
  { id: 22, chapter: 3, name: 'Wrong Way Round', objective: 'The short way home is blocked. Take the long way.',
    rings: [R(6, 0, [], { block: [5] }), R(6, 2)], scramble: [[0, 1], [0, 1], [0, 1], [0, 1], [1, 1]], moves: 6 },
  { id: 23, chapter: 3, name: 'Narrow Lane', objective: 'Two notches are blocked, and the first ring drags the second as it turns.',
    rings: [R(8, 0, [[1, 1]], { block: [1, 2] }), R(8, 4)], scramble: [[0, -1], [0, -1], [0, -1], [1, 1]], moves: 5 },
  { id: 24, chapter: 3, name: 'Gate and Block', objective: 'The gate opens at notch two, and notch four is blocked behind it.',
    rings: [R(6), R(6, 0, [], { gate: { ring: 0, at: 2 }, block: [4] })],
    scramble: [[0, 1], [0, 1], [1, 1], [1, 1], [1, 1]], moves: 6 },
  { id: 25, chapter: 3, name: 'Blocked Jump', objective: 'Two-notch jumps with a blocked landing. Count the long way.',
    rings: [R(10, 0, [], { step: 2, block: [2] }), R(6)], scramble: [[0, -1], [0, -1], [0, -1], [1, 1]], moves: 5 },
  { id: 26, chapter: 3, name: 'Mirror Block', objective: 'The first ring turns the second the other way, and cannot land on notch five.',
    rings: [R(6, 0, [[1, -1]], { block: [5] }), R(6, 3), R(6)],
    scramble: [[0, 1], [0, 1], [2, -1], [0, 1]], moves: 5 },
  { id: 27, chapter: 3, name: 'Locked Chain', objective: 'A frozen ring holds the gate. Free it with a blocked neighbour.',
    rings: [R(6, 0, [[1, 1]], { block: [5] }), R(6, 0, [], { fixed: true }), R(6, 0, [], { gate: { ring: 1, at: 0 } })],
    scramble: [[2, 1], [2, 1], [0, 1], [0, 1]], moves: 5 },
  { id: 28, chapter: 3, name: 'Two Blockades', objective: 'Two rings each have a blocked notch, and one lever moves both.',
    rings: [R(8, 0, [], { block: [7] }), R(8, 4, [], { block: [3] }), R(8, 0, [[0, 1], [1, -1]])],
    scramble: [[0, 1], [0, 1], [1, 1], [1, 1], [2, 1]], moves: 5 },
  { id: 29, chapter: 3, name: 'Careful Steps', objective: 'Links, a gate, a jump ring and three blocked notches. Plan the order.',
    rings: [R(8, 0, [[2, 1]], { block: [7] }), R(8, 2, [], { gate: { ring: 0, at: 0 }, block: [1] }), R(10, 0, [], { step: 2, block: [8] })],
    scramble: [[1, 1], [1, 1], [0, 1], [0, 1], [2, 1]], moves: 6 },
  { id: 30, chapter: 3, name: 'The Blockade', objective: 'A frozen ring, two gates, a jump and blocked notches. Open the way.',
    rings: [R(6, 0, [[1, 1], [3, -1]], { block: [5] }), R(6, 3, [], { fixed: true }),
      R(8, 0, [], { step: 2, gate: { ring: 1, at: 3 }, block: [6] }), R(6, 2, [], { gate: { ring: 0, at: 0 }, block: [4] })],
    scramble: [[2, 1], [2, 1], [3, 1], [0, 1], [0, 1]], moves: 6 },

  // Chapter 4: Jams (LEVELS[30..39]). Adds jam: see sim.mjs.
  { id: 31, chapter: 4, name: 'First Jam', objective: 'The second ring jams while the first sits at the top. Step off, then turn.',
    rings: [R(6), R(6, 0, [], { jam: { ring: 0, at: 0 } })], scramble: [[0, 1], [1, 1], [1, 1]], moves: 4 },
  { id: 32, chapter: 4, name: 'Jam Notch', objective: 'The jam holds at notch three, not at the top. Step aside before you turn.',
    rings: [R(6), R(6, 0, [], { jam: { ring: 0, at: 3 } })], scramble: [[1, 1], [1, 1], [0, 1], [0, 1], [0, 1]], moves: 5 },
  { id: 33, chapter: 4, name: 'Two Jams', objective: 'One ring jams two others, at different notches. Find the gaps.',
    rings: [R(6), R(6, 0, [], { jam: { ring: 0, at: 2 } }), R(6, 3, [], { jam: { ring: 0, at: 4 } })],
    scramble: [[2, 1], [0, 1], [1, 1], [0, 1], [0, 1], [2, 1]], moves: 6 },
  { id: 34, chapter: 4, name: 'Gate and Jam', objective: 'One ring needs a gate open, the next needs a jam clear. Order matters.',
    rings: [R(6), R(6, 0, [], { gate: { ring: 0, at: 0 } }), R(6, 0, [], { jam: { ring: 1, at: 0 } })],
    scramble: [[1, 1], [2, 1], [2, 1], [0, 1]], moves: 4 },
  { id: 35, chapter: 4, name: 'Dragged Along', objective: 'A link can drag a jammed ring, but your hand cannot. Free it first.',
    rings: [R(8, 0, [[2, 1]]), R(8), R(8, 0, [], { jam: { ring: 1, at: 3 } })],
    scramble: [[0, 1], [2, 1], [1, 1], [1, 1], [1, 1], [0, 1]], moves: 6 },
  { id: 36, chapter: 4, name: 'Jam Chain', objective: 'Each ring jams the next. Clear the chain from the front.',
    rings: [R(6), R(6, 0, [], { jam: { ring: 0, at: 1 } }), R(6, 0, [], { jam: { ring: 1, at: 1 } })],
    scramble: [[2, 1], [2, 1], [1, 1], [0, 1], [0, 1]], moves: 5 },
  { id: 37, chapter: 4, name: 'Jumping Jam', objective: 'Two-notch jumps, and a jam at notch four. Plan the jumps around it.',
    rings: [R(8), R(8, 0, [], { step: 2, jam: { ring: 0, at: 4 } })],
    scramble: [[1, 1], [1, 1], [0, 1], [0, 1], [0, 1], [0, 1]], moves: 6 },
  { id: 38, chapter: 4, name: 'Frozen Key', objective: 'A frozen ring holds the jam. Its neighbour turns it, so use that.',
    rings: [R(6, 0, [[1, 1]]), R(6, 0, [], { fixed: true }), R(6, 0, [], { jam: { ring: 1, at: 0 } })],
    scramble: [[0, 1], [2, 1], [2, 1], [0, 1]], moves: 4 },
  { id: 39, chapter: 4, name: 'Tangled Locks', objective: 'Links, a gate, a jump and two jams across four rings. Five moves only.',
    rings: [R(8, 0, [[3, 1]]), R(8, 0, [], { jam: { ring: 0, at: 2 } }), R(8, 4, [], { gate: { ring: 1, at: 0 } }),
      R(8, 0, [], { step: 2, jam: { ring: 2, at: 4 } })],
    scramble: [[2, 1], [0, 1], [1, 1], [0, 1], [3, 1]], moves: 5 },
  { id: 40, chapter: 4, name: 'The Gatehouse', objective: 'Five rings, a frozen key, a gate and three jams. Open the gatehouse.',
    rings: [R(6, 0, [[1, 1]]), R(6, 3, [], { fixed: true }), R(8, 0, [], { step: 2, jam: { ring: 1, at: 3 } }),
      R(8, 4, [], { gate: { ring: 0, at: 0 } }), R(6, 2, [], { jam: { ring: 3, at: 4 } })],
    scramble: [[3, 1], [4, 1], [0, 1], [2, 1], [0, 1], [2, 1]], moves: 6 },

  // Chapter 5: Ratchets (LEVELS[40..49]). Adds oneWay: see sim.mjs.
  { id: 41, chapter: 5, name: 'First Ratchet', objective: 'The first ring only turns one way. Keep turning until it comes round.',
    rings: [R(6, 0, [], { oneWay: 1 }), R(6)], scramble: [[0, 1], [0, 1], [1, -1]], moves: 5 },
  { id: 42, chapter: 5, name: 'Backwards Only', objective: 'This ratchet only turns the other way. The second ring is free.',
    rings: [R(6, 0, [], { oneWay: -1 }), R(6, 3)], scramble: [[0, -1], [0, -1], [1, 1], [1, 1]], moves: 6 },
  { id: 43, chapter: 5, name: 'Dragged Back', objective: 'A ratchet drags a free ring along. Use the free ring to fix the overshoot.',
    rings: [R(6, 0, [[1, 1]], { oneWay: 1 }), R(6)], scramble: [[0, 1], [0, 1], [0, 1], [1, -1]], moves: 5 },
  { id: 44, chapter: 5, name: 'Ratchet Gate', objective: 'The ratchet is also the key. Bring it home, then the gate opens.',
    rings: [R(6, 0, [], { oneWay: 1 }), R(6, 0, [], { gate: { ring: 0, at: 0 } })],
    scramble: [[1, 1], [0, 1], [0, 1]], moves: 5 },
  { id: 45, chapter: 5, name: 'Ratchet Jam', objective: 'A backwards ratchet is jammed while the first ring sits at the top. Step off first.',
    rings: [R(6), R(6, 0, [], { oneWay: -1, jam: { ring: 0, at: 0 } })],
    scramble: [[0, 1], [1, -1], [1, -1], [0, -1]], moves: 6 },
  { id: 46, chapter: 5, name: 'Odd Ratchet', objective: 'Seven notches, two-notch jumps and one direction. It takes the long way.',
    rings: [R(7, 0, [], { oneWay: 1, step: 2 }), R(7)], scramble: [[0, 1], [0, 1], [1, -1]], moves: 6 },
  { id: 47, chapter: 5, name: 'Ratchet Chain', objective: 'The ratchet drags the next ring, which drags the last the other way.',
    rings: [R(6, 0, [[1, 1]], { oneWay: 1 }), R(6, 0, [[2, -1]]), R(6)],
    scramble: [[0, 1], [0, 1], [1, 1]], moves: 5 },
  { id: 48, chapter: 5, name: 'Opposite Ratchets', objective: 'Two ratchets turn opposite ways. One lever drags them both.',
    rings: [R(4, 0, [], { oneWay: 1 }), R(4, 0, [], { oneWay: -1 }), R(4, 0, [[0, 1], [1, -1]])],
    scramble: [[0, 1], [1, -1], [2, 1]], moves: 7 },
  { id: 49, chapter: 5, name: 'Ratchet Key', objective: 'A frozen ring holds the gate to the ratchet. One lever flips it open and shut.',
    rings: [R(6, 0, [[1, 3]]), R(6, 0, [], { fixed: true }), R(8, 0, [], { oneWay: 1, gate: { ring: 1, at: 3 } })],
    scramble: [[0, 1], [2, 1], [2, 1], [2, 1], [2, 1], [2, 1], [0, 1]], moves: 5 },
  { id: 50, chapter: 5, name: 'The Final Lock', objective: 'Two ratchets, a gate, a jam, a jump and a frozen key. Open the last lock.',
    rings: [R(6, 0, [[1, 3]]), R(6, 0, [], { fixed: true }), R(8, 0, [], { oneWay: 1, step: 2, gate: { ring: 1, at: 3 } }),
      R(6, 2, [], { oneWay: -1, jam: { ring: 0, at: 0 } })],
    scramble: [[0, 1], [2, 1], [2, 1], [3, -1], [3, -1], [0, 1]], moves: 8 },
];
