import {factionOf} from './factions.mjs';
import {UNITS} from './catalog.mjs';
const cap=(v,a,b)=>Math.max(a,Math.min(b,v));
export function safeProfile(p={}){const army={};let left=80;for(const k of Object.keys(UNITS)){army[k]=cap(Math.floor(Number(p.army?.[k]))||0,0,left);left-=army[k];}return{faction:factionOf(p).id,age:['frontier','stone','imperial'].includes(p.age)?p.age:'stone',name:String(p.name||'Kingdom').replace(/[<>\x00-\x1f]/g,'').slice(0,22),army,flag:['stag','lion','raven','sun'].includes(p.flag)?p.flag:'stag',skin:['classic','ivory','obsidian'].includes(p.skin)?p.skin:'classic',attack:cap(Number(p.attack)||1,1,1.15),health:cap(Number(p.health)||1,1,1.2),fortress:cap(Number(p.fortress)||1,1,2.2),defence:cap(Number(p.defence)||0,0,8)};}
export function createBattle(a,b,{ai=true,mission=0}={}){const profiles=[safeProfile(a),safeProfile(b)];const s={time:0,ai,mission,profiles,units:[],keeps:[],effects:[],orders:[{x:40,y:87},{x:40,y:107}],winner:null,paused:false};let id=0;profiles.forEach((p,side)=>{s.keeps.push({id:'keep'+side,side,x:40,y:side?21:99,hp:650*p.fortress+p.defence*35,max:650*p.fortress+p.defence*35,cool:0});let n=0;for(const[type,count]of Object.entries(p.army))for(let i=0;i<count;i++){const t=UNITS[type];s.units.push({id:id++,type,side,x:20+(n%9)*5,y:side?31+Math.floor(n/9)*4:87-Math.floor(n/9)*4,hp:t.hp*p.health,max:t.hp*p.health,cool:(n%3)*.2,order:null});n++;}});return s;}
export function order(s,side,a){if(s.winner!==null||![0,1].includes(side)||!a||!Number.isFinite(a.x)||!Number.isFinite(a.y)||!['all',...Object.keys(UNITS)].includes(a.group))return false;const p={x:cap(a.x,4,76),y:cap(a.y,5,115)};if(p.y>=45&&p.y<=64)p.x=p.x<40?20:60;for(const u of s.units)if(u.side===side&&(a.group==='all'||u.type===a.group))u.order={...p};if(a.group==='all')s.orders[side]=p;return true;}
function move(u,target,dt){let x=target.x,y=target.y;const crossing=(u.y<45&&y>64)||(u.y>64&&y<45);if(crossing){const bridge=Math.abs(u.x-20)<Math.abs(u.x-60)?20:60;if(Math.abs(u.x-bridge)>4){x=bridge;y=u.y<45?41:68;}else{x=bridge;y=u.y<45?68:41;}}else if(u.y>=45&&u.y<=64){x=u.x<40?20:60;y=target.y>=45&&target.y<=64?target.y:target.y<45?41:68;}const dx=x-u.x,dy=y-u.y,d=Math.hypot(dx,dy),step=Math.min(d,UNITS[u.type].speed*dt);if(d>.15){u.x+=dx/d*step;u.y+=dy/d*step;}}
export function stepBattle(s,dt){if(s.winner!==null||s.paused)return;s.time+=dt;s.effects=s.effects.filter(e=>(e.life-=dt)>0);for(const u of s.units){if(u.hp<=0)continue;const t=UNITS[u.type];u.cool-=dt;let target=null,best=Infinity;for(const v of s.units)if(v.side!==u.side&&v.hp>0){const d=Math.hypot(u.x-v.x,u.y-v.y);if(d<best){best=d;target=v;}}const keep=s.keeps[1-u.side],kd=Math.hypot(u.x-keep.x,u.y-keep.y);if(kd<best){target=keep;best=kd;}const destination=u.order||s.orders[u.side];const inCombat=best<=Math.max(t.range,11);if(inCombat&&best<=t.range+1){if(u.cool<=0){const rally=s.units.some(v=>v.side===u.side&&v.type==='commander'&&v.hp>0&&Math.hypot(v.x-u.x,v.y-u.y)<15)?1.12:1;target.hp-=t.attack*s.profiles[u.side].attack*rally;u.cool=t.period;s.effects.push({x:u.x,y:u.y,tx:target.x,ty:target.y,life:.25,side:u.side});}}else if(inCombat)move(u,target,dt);else move(u,destination,dt);}
for(let i=0;i<s.units.length;i++){const a=s.units[i];if(a.hp<=0)continue;for(let j=i+1;j<s.units.length;j++){const b=s.units[j];if(b.hp<=0)continue;let dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy);if(d<1.9){if(d<.01){dx=.1;dy=.1;d=.14;}const shift=(1.9-d)*.3;a.x=cap(a.x-dx/d*shift,3,77);a.y=cap(a.y-dy/d*shift,4,116);b.x=cap(b.x+dx/d*shift,3,77);b.y=cap(b.y+dy/d*shift,4,116);}}}
for(const k of s.keeps){k.cool-=dt;const target=s.units.find(u=>u.side!==k.side&&u.hp>0&&Math.hypot(u.x-k.x,u.y-k.y)<17);if(target&&k.cool<=0){target.hp-=13+s.profiles[k.side].defence*1.5;k.cool=1.2;s.effects.push({x:k.x,y:k.y,tx:target.x,ty:target.y,life:.3,side:k.side});}}
for(let side=0;side<2;side++)if(s.keeps[side].hp<=0||!s.units.some(u=>u.side===side&&u.hp>0)){s.winner=1-side;break;}
}
export function survivors(s,side){return Object.fromEntries(Object.keys(UNITS).map(k=>[k,s.units.filter(u=>u.side===side&&u.type===k&&u.hp>0).length]));}
