import {workerKey} from './workers.mjs';
import {workerCount,assigned} from './town.mjs';
import {riverSurface} from './water.mjs';
import {FACTIONS,factionOf,factionArt,unitArt} from './factions.mjs';
import {ageOf,AGES,buildingArt} from './ages.mjs';
import {DEPOSITS} from './land.mjs';
import {BUILDINGS,UNITS,FLAGS} from './catalog.mjs';
export async function renderer(canvas){const c=canvas.getContext('2d'),assets={};await Promise.all([...FACTIONS.flatMap(f=>[0,1,2,5].flatMap(unit=>Array.from({length:4},(_,frame)=>(f.id==='verdant'?'':f.id+'-')+'walk-'+unit+'-'+frame))),...FACTIONS.slice(1).flatMap(f=>[...['frontier','building','imperial'].flatMap(a=>Array.from({length:12},(_,i)=>f.id+'-'+a+'-'+i)),...['unit','gather'].flatMap(a=>Array.from({length:6},(_,i)=>f.id+'-'+a+'-'+i))]),...['building','frontier','imperial'].flatMap(a=>Array.from({length:12},(_,i)=>a+'-'+i)),...Array.from({length:6},(_,i)=>'land-'+i),...Array.from({length:6},(_,i)=>'gather-'+i),...Array.from({length:6},(_,i)=>'unit-'+i)].map(k=>new Promise(resolve=>{const im=new Image();im.onload=()=>{assets[k]=im;resolve();};im.onerror=resolve;im.src='assets/'+k+'.webp';})));const terrain={};for(const key of ['town','battle']){const im=new Image();im.src='assets/'+key+'-terrain.webp';terrain[key]=im;}let w=innerWidth,h=innerHeight,scale=1,ox=0,oy=0,aspectX=1,aspectY=1;const camera={zoom:1,x:0,y:0},river=riverSurface(),reducedMotion=matchMedia('(prefers-reduced-motion: reduce)');function resize(){w=innerWidth;h=innerHeight;const d=Math.min(devicePixelRatio,2);canvas.width=w*d;canvas.height=h*d;c.setTransform(d,0,0,d,0,0);}resize();addEventListener('resize',resize);
const rand=n=>{const x=Math.sin(n*127.1+311.7)*43758.5453;return x-Math.floor(x);};
function ellipse(x,y,rx,ry,color){c.fillStyle=color;c.beginPath();c.ellipse(x,y,rx,ry,0,0,Math.PI*2);c.fill();}
function sprite(key,x,y,width,skin){const im=assets[key];if(!im)return;const height=width*im.height/im.width;c.save();if(skin==='ivory')c.filter='brightness(1.3) saturate(.55)';if(skin==='obsidian')c.filter='brightness(.7) hue-rotate(50deg)';c.drawImage(im,x-width/2,y-height,width,height);c.restore();}
// Full painted walk frames keep knees, weapons and clothing intact.
function walker(key,x,y,width,phase,moving=true,direction=1){
const match=key.match(/^(.*)unit-(\d)$/),frame=Math.floor(((phase%(Math.PI*2)+Math.PI*2)%(Math.PI*2))/(Math.PI*.5)),walkKey=match?match[1]+'walk-'+match[2]+'-'+frame:null;
const idleKey=match?match[1]+'walk-'+match[2]+'-1':null,chosen=assets[walkKey]?(moving?walkKey:idleKey):key,im=assets[chosen],original=assets[key];const height=width*(original?original.height/original.width:1.9),drawWidth=im?height*im.width/im.height:width;
c.save();c.translate(x,y);if(direction<0)c.scale(-1,1);sprite(chosen,0,0,drawWidth);c.restore();}
let workerPositions=[],workerUI={},workerTown=null;const transfers=new Map();
function workerView(s,record,x,y,width,time,moving=false,direction=1,workingKey=null){
const key=workerKey(record.kind,record.id,record.index),trip=transfers.get(key);let travelling=false;
if(trip){const t=Math.min(1,(performance.now()-trip.start)/1300),a=point(trip.x,trip.y);direction=x>=a.x?1:-1;x=a.x+(x-a.x)*t;y=a.y+(y-a.y)*t;travelling=t<1;if(!travelling)transfers.delete(key);}
const height=width*1.9;workerPositions.push({...record,key,x,y,width,height});
if(workerUI.drag&&workerUI.selectedWorker?.key===key)return;
if(workerUI.selectedWorker?.key===key){ellipse(x,y+2*scale,Math.max(15,width*.65),Math.max(6,width*.25),'#e8d07599');c.strokeStyle='#fff3b5';c.lineWidth=1.5;c.beginPath();c.ellipse(x,y+2*scale,Math.max(15,width*.65),Math.max(6,width*.25),0,0,7);c.stroke();}
if(workingKey&&!travelling)sprite(workingKey,x,y+6*scale,52*scale);else walker(unitArt(s,0),x,y,width,time*9+record.index*1.5,(moving||travelling)&&s.settings.motion,direction);
}
function workerOverlay(){const drag=workerUI.drag;if(!drag)return;const target=drag.target;if(target){const site=target.kind==='node'?workerTown.nodes.find(n=>n.id===target.id):workerTown.buildings.find(b=>b.id===target.id);if(site){const p=iso(site.x,site.y);ellipse(p.x,p.y,48*scale,25*scale,drag.error?'#d2655b88':'#79e2aa88');c.strokeStyle=drag.error?'#ffd0c5':'#dbffe8';c.lineWidth=2;c.beginPath();c.ellipse(p.x,p.y,48*scale,25*scale,0,0,7);c.stroke();}}
c.save();c.globalAlpha=.85;walker(unitArt(workerTown,0),drag.x,drag.y+18*scale,28*scale,0,false);c.restore();}
const unitTracks=new Map();let trackedBattle=-1;
function point(x,y){return {x:ox+x*scale*aspectX,y:oy+y*scale*aspectY};}function iso(x,y){return point((x-y)*52,(x+y)*28);}
function ground(){c.fillStyle='#344b2d';c.fillRect(0,0,w,h);for(let i=0;i<1200;i++){const x=rand(i)*w,y=rand(i+2000)*h;c.fillStyle=i%2?'#64834a20':'#132e1920';c.fillRect(x,y,2+rand(i+50)*4,1+rand(i+70)*3);}const g=c.createRadialGradient(w*.5,h*.4,50,w*.5,h*.5,Math.max(w,h)*.75);g.addColorStop(0,'#b5b76b13');g.addColorStop(1,'#001a1666');c.fillStyle=g;c.fillRect(0,0,w,h);}
function tree(x,y,size,seed){ellipse(x,y,size*.48,size*.16,'#071f1677');c.strokeStyle='#645537';c.lineWidth=size*.09;c.beginPath();c.moveTo(x,y);c.lineTo(x,y-size*.8);c.stroke();for(let j=0;j<7;j++)ellipse(x+(rand(seed+j)-.5)*size*.7,y-size*.55-rand(seed+j+50)*size*.45,size*(.22+rand(seed+j+30)*.13),size*.3,['#1b3a23','#24472b','#335835','#42603a'][j%4]);}
function flag(x,y,id,profile){const f=id==='stag'?factionOf(profile):FLAGS.find(v=>v.id===id)||FLAGS[0];c.strokeStyle='#c9aa67';c.lineWidth=2;c.beginPath();c.moveTo(x,y);c.lineTo(x,y-30);c.stroke();c.fillStyle=f.color;c.beginPath();c.moveTo(x,y-30);c.lineTo(x+19,y-27);c.lineTo(x+16,y-12);c.lineTo(x,y-15);c.fill();c.fillStyle='#f3dd93';c.font='12px Georgia';c.fillText(f.symbol,x+3,y-17);}
function town(s,selected,placing,time,interaction={}){workerUI=interaction;workerTown=s;workerPositions=[];aspectX=aspectY=1;scale=Math.min(w/420,h/650)*camera.zoom;ox=w/2+camera.x;oy=h/2-280*scale+camera.y;ground();if(terrain.town.complete&&terrain.town.naturalWidth){const width=Math.max(w,900*scale),height=width*terrain.town.height/terrain.town.width;c.drawImage(terrain.town,w/2-width/2+camera.x,h/2-height/2+camera.y,width,height);}for(let i=0;i<0;i++){const x=-3+rand(i+91)*16,y=-3+rand(i+700)*16;if(x>1&&x<10&&y>1&&y<10)continue;const p=iso(x,y);tree(p.x,p.y,(28+rand(i)*30)*scale,i*9);}
// Warm winding paths under the settlement, with smaller worn approaches.
c.lineCap='round';for(const b of s.buildings){const p=iso(b.x,b.y),k=iso(5,5);c.strokeStyle='#a2996555';c.lineWidth=13*scale;c.beginPath();c.moveTo(p.x,p.y);c.quadraticCurveTo(k.x,p.y,k.x,k.y);c.stroke();c.strokeStyle='#c4b68025';c.lineWidth=5*scale;c.stroke();}
if(placing)for(let x=1;x<=9;x++)for(let y=1;y<=9;y++){const p=iso(x,y),occupied=s.buildings.some(b=>b.x===x&&b.y===y)||s.nodes.some(n=>n.x===x&&n.y===y&&(n.remaining>0||n.readyAt));c.fillStyle=occupied?'#944d3220':'#c5d78228';c.strokeStyle='#dae4a855';c.beginPath();c.moveTo(p.x,p.y-25*scale);c.lineTo(p.x+48*scale,p.y);c.lineTo(p.x,p.y+25*scale);c.lineTo(p.x-48*scale,p.y);c.closePath();c.fill();c.stroke();}
const objects=[...s.buildings.map(b=>({...b,kind:'building'})),...s.nodes.map(n=>({...n,kind:'node'}))].sort((a,b)=>a.x+a.y-b.x-b.y);
for(const b of objects){const p=iso(b.x,b.y);if(b.kind==='node'){drawNode(s,b,p,selected,time);continue;}if(b.id===selected)ellipse(p.x,p.y,48*scale,25*scale,'#ddc66a66');sprite(buildingArt(s,BUILDINGS[b.type].art),p.x,p.y+17*scale,(b.type==='keep'?116:103)*scale,s.skin);if(b.type==='keep')flag(p.x+35*scale,p.y-70*scale,s.flag,s);if(b.level>1){c.fillStyle='#ead797';c.font=`${Math.max(9,11*scale)}px sans-serif`;c.fillText('◆'.repeat(b.level-1),p.x-12*scale,p.y+28*scale);}}
for(const j of s.jobs.filter(j=>j.kind==='build')){const p=iso(j.x,j.y);ellipse(p.x,p.y,35*scale,18*scale,'#d7b97444');c.fillStyle='#efdca4';c.font='17px Georgia';c.fillText('⚒',p.x-8,p.y);}
for(const b of s.buildings.filter(b=>b.workers)){for(let i=0;i<b.workers;i++){const p=iso(b.x,b.y),sway=s.settings.motion?Math.sin(time*.35+i*2)*8*scale:0;workerView(s,{kind:'farm',id:b.id,index:i},p.x+(i-1)*19*scale+sway,p.y+22*scale,25*scale,time,s.settings.motion,Math.cos(time*.35+i*2)>=0?1:-1);}}
const assembly=[[5,7],[4,5],[6,5],[5,4],[4,7],[6,7]].find(([x,y])=>!s.buildings.some(b=>b.x===x&&b.y===y)&&!s.nodes.some(n=>n.x===x&&n.y===y&&(n.remaining>0||n.readyAt)))||[5,7],keep=iso(...assembly);for(let i=0;i<Math.max(0,workerCount(s)-assigned(s));i++)workerView(s,{kind:'idle',id:'keep',index:i},keep.x+((i%4)-1.5)*25*scale,keep.y+(16+Math.floor(i/4)*26)*scale,25*scale,time);
workerOverlay();}

function nodeWidth(n){return n.type==='wood'?82:n.type==='pine'?60:76;}
function drawNode(s,n,p,selected,time){const t=DEPOSITS[n.type],active=n.remaining>0&&!n.readyAt,wood=t.resource==='wood',width=nodeWidth(n)*scale;
if(n.id===selected||n.workers){ellipse(p.x,p.y,31*scale,16*scale,n.id===selected?'#dfc77266':'#88c39930');}
const phase=n.clearedAt?Math.min(1,(Date.now()-n.clearedAt)/850):1;
if(!active&&wood&&phase<1&&s.settings.motion){c.save();c.translate(p.x,p.y+15*scale);c.rotate(phase*1.4);c.globalAlpha=1-phase;sprite('land-'+t.art,0,0,width);c.restore();}
const shrink=!wood&&active?.7+.3*n.remaining/n.capacity:1;sprite('land-'+(active?t.art:t.spentArt),p.x,p.y+15*scale,(active?width*shrink:wood?45*scale:65*scale));
if(n.readyAt){c.fillStyle='#d8d998';c.font=`${11*scale}px sans-serif`;c.fillText(wood?'Growing…':'Excavating…',p.x-25*scale,p.y+28*scale);}
if(n.workers&&active){bar(p.x,p.y+22*scale,45*scale,n.remaining/n.capacity,true);for(let i=0;i<n.workers;i++){const x=p.x+(i-1)*20*scale,y=p.y+22*scale;workerView(s,{kind:'node',id:n.id,index:i},x,y,28*scale,time,false,1,factionArt(s,'gather-'+((wood?0:3)+(Math.floor(time*4+i)%3))));if(s.settings.motion&&Math.sin(time*7+i)>.6){c.fillStyle=wood?'#e5bf76':'#d1d2c2';c.fillRect(x,y-6*scale,2*scale,2*scale);}}}}

function battle(s,side,group,time=s.time,motion=true){if(s.time<trackedBattle)unitTracks.clear();trackedBattle=s.time;const base=Math.min(w/80,h/120);aspectX=w/80/base;aspectY=h/120/base;scale=base*camera.zoom;ox=w/2-w*camera.zoom/2+camera.x;oy=h/2-h*camera.zoom/2+camera.y;ground();const art=terrain.battle;if(art.complete&&art.naturalWidth)c.drawImage(art,ox,oy,w*camera.zoom,h*camera.zoom);river.draw(c,art,ox,oy,w*camera.zoom,h*camera.zoom,time,motion&&!reducedMotion.matches&&!s.paused);const riverY=point(0,54).y;c.fillStyle=terrain.battle.complete?'#52777900':'#527779';c.fillRect(0,riverY,w,11*scale);for(let i=0;i<0;i++){c.strokeStyle='#c3e3d223';c.lineWidth=1;c.beginPath();c.moveTo(rand(i+38)*w,riverY+rand(i+63)*11*scale);c.lineTo(rand(i+38)*w+25,riverY+rand(i+63)*11*scale);c.stroke();}for(const x of (terrain.battle.complete?[]:[20,60])){const p=point(x,54);c.fillStyle='#6d6650';c.fillRect(p.x-6*scale,p.y-3*scale,12*scale,17*scale);c.strokeStyle='#bdb48c';c.lineWidth=2;for(let i=-3;i<14;i+=2){c.beginPath();c.moveTo(p.x-6*scale,p.y+i*scale);c.lineTo(p.x+6*scale,p.y+i*scale);c.stroke();}}
for(let i=0;i<0;i++){const p=point(i%2?rand(i)*8:72+rand(i)*8,rand(i+420)*120);if(p.y>riverY-15&&p.y<riverY+12*scale)continue;tree(p.x,p.y,8*scale,i);}
for(const k of s.keeps){const p=point(k.x,k.y);sprite(factionArt(s.profiles[k.side],(AGES.find(a=>a.id===s.profiles[k.side].age)?.art||'building')+'-0'),p.x,p.y+5*scale,22*scale,s.profiles[k.side].skin);flag(p.x+8*scale,p.y-18*scale,s.profiles[k.side].flag,s.profiles[k.side]);bar(p.x,p.y+7*scale,22*scale,k.hp/k.max,k.side===side);}
for(const u of [...s.units].sort((a,b)=>a.y-b.y)){const p=point(u.x,u.y);if(u.hp<=0){ellipse(p.x,p.y,2.5*scale,1.3*scale,'#69372c88');continue;}ellipse(p.x,p.y,2.5*scale,1.3*scale,u.side===side?'#5cd9b15e':'#e7655c77');if(u.side===side&&(group==='all'||group===u.type)){c.strokeStyle='#d3c67a77';c.beginPath();c.ellipse(p.x,p.y,3*scale,1.5*scale,0,0,7);c.stroke();}const old=unitTracks.get(u.id),distance=old?Math.hypot(u.x-old.x,u.y-old.y):0,phase=(old?.phase||u.id)+(distance*2),lastMove=distance>.002?s.time:(old?.lastMove??-1),direction=old&&Math.abs(u.x-old.x)>.001?(u.x>old.x?1:-1):(old?.direction||1);unitTracks.set(u.id,{x:u.x,y:u.y,phase,lastMove,direction});if(u.type==='siege')sprite(unitArt(s.profiles[u.side],4),p.x,p.y,9*scale);else walker(unitArt(s.profiles[u.side],UNITS[u.type].art),p.x,p.y,6*scale,phase,!s.paused&&s.winner===null&&s.time-lastMove<.15,direction);bar(p.x,p.y-8*scale,6*scale,u.hp/u.max,u.side===side);}
for(const e of s.effects){const a=point(e.x,e.y),b=point(e.tx,e.ty);c.strokeStyle=e.side===side?'#fae9a1':'#ffad83';c.lineWidth=1.5;c.beginPath();c.moveTo(a.x,a.y-10);c.lineTo(b.x,b.y-6);c.stroke();}const p=point(s.orders[side].x,s.orders[side].y);c.strokeStyle='#f8d883';c.beginPath();c.ellipse(p.x,p.y,9,5,0,0,7);c.stroke();}
function bar(x,y,width,ratio,friendly){c.fillStyle='#10251edb';c.fillRect(x-width/2,y,width,3);c.fillStyle=friendly?'#83cbaa':'#dc8064';c.fillRect(x-width/2,y,width*Math.max(0,ratio),3);}
return{camera,town,battle,get workerPositions(){return workerPositions;},pickWorker(x,y){return workerPositions.map(v=>({...v,d:Math.hypot((x-v.x),y-(v.y-v.height*.45))})).filter(v=>Math.abs(x-v.x)<Math.max(21,v.width*.7)&&y>v.y-Math.max(44,v.height)&&y<v.y+12).sort((a,b)=>a.d-b.d)[0]||null;},walkTo(key,from){transfers.set(key,{x:(from.x-ox)/scale,y:(from.y-oy)/scale,start:performance.now()});},targetPoint(site){const p=iso(site.x,site.y);return{x:p.x,y:p.y-12*scale};},focusTown(n){camera.zoom=Math.max(camera.zoom,1.35);const z=Math.min(w/420,h/650)*camera.zoom;camera.x=-(n.x-n.y)*52*z;camera.y=(280-(n.x+n.y)*28)*z+60;},pickTown(s,x,y){return [...s.buildings.map(b=>({...b,kind:'building'})),...s.nodes.map(n=>({...n,kind:'node'}))].sort((a,b)=>b.x+b.y-a.x-a.y).find(b=>{const p=iso(b.x,b.y),node=b.kind==='node',width=(node?nodeWidth(b):b.type==='keep'?116:103)*scale,key=node?'land-'+(b.remaining>0?DEPOSITS[b.type].art:DEPOSITS[b.type].spentArt):buildingArt(s,BUILDINGS[b.type].art),im=assets[key],height=im?width*im.height/im.width:width;return x>p.x-width*.4&&x<p.x+width*.4&&y>p.y+17*scale-height&&y<p.y+24*scale;});},toTown(x,y){const a=(x-ox)/scale/52,b=(y-oy)/scale/28;return{x:Math.round((a+b)/2),y:Math.round((b-a)/2)};},toBattle:(x,y)=>({x:(x-ox)/scale/aspectX,y:(y-oy)/scale/aspectY}),reset(){camera.zoom=1;camera.x=camera.y=0;}};
}

