import {moveWorker} from './workers.mjs';
import {FACTIONS,factionOf} from './factions.mjs';
import {ageOf} from './ages.mjs';
import {ensureLand,harvestLand,landCommand} from './land.mjs';
import {BUILDINGS,UNITS,FEATURES,levelOf,hasFeature,LOOT} from './catalog.mjs';
export const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));export const resources=['food','wood','stone','gold'];
export function newTown(now=Date.now()){return ensureLand({version:1,faction:'verdant',factionChosen:false,name:'Greenhaven',xp:35,resources:{food:360,wood:360,stone:220,gold:180},buildings:[{id:1,type:'keep',x:5,y:5,level:1,workers:0},{id:2,type:'farm',x:4,y:6,level:1,workers:2},{id:3,type:'lumber',x:3,y:4,level:1,workers:0},{id:4,type:'quarry',x:7,y:4,level:1,workers:0},{id:5,type:'mine',x:7,y:6,level:1,workers:0},{id:6,type:'house',x:3,y:5,level:1,workers:0},{id:7,type:'barracks',x:6,y:6,level:1,workers:0}],army:{sword:7,archer:2,knight:0,siege:0,commander:0},jobs:[],nextId:8,last:now,cleared:[],battles:0,wins:0,chests:1,flags:['stag'],skins:['classic'],flag:'stag',skin:'classic',unlocks:[],log:['Your first war chest awaits in the Treasury.'],claimed:[],settings:{sound:true,motion:true}});}
export const population=s=>12+s.buildings.filter(b=>b.type==='house').reduce((n,b)=>n+6*b.level,0);
export const armyCount=s=>Object.values(s.army).reduce((n,v)=>n+v,0)+s.jobs.filter(j=>j.kind==='train').length;
export const workerCount=s=>6+Math.max(0,levelOf(s.xp)-1)*2+ageOf(s).workers;
export const assigned=s=>s.buildings.reduce((n,b)=>n+(b.workers||0),0)+(s.nodes||[]).reduce((n,b)=>n+(b.workers||0),0);
export function canPay(s,cost){return Object.entries(cost).every(([k,n])=>s.resources[k]>=n);}
function pay(s,cost){for(const[k,n]of Object.entries(cost))s.resources[k]-=n;}
export function upgradeCost(b){return Object.fromEntries(Object.entries(BUILDINGS[b.type].cost).map(([k,n])=>[k,Math.ceil(n*(.65+b.level*.6))]));}
export const costText=c=>Object.entries(c).map(([k,v])=>`${v} ${k}`).join(' · ');
export function validCell(s,x,y){return Number.isInteger(x)&&Number.isInteger(y)&&x>=1&&y>=1&&x<=9&&y<=9&&!s.buildings.some(b=>b.x===x&&b.y===y)&&!s.jobs.some(j=>j.kind==='build'&&j.x===x&&j.y===y)&&!(s.nodes||[]).some(n=>n.x===x&&n.y===y&&(n.remaining>0||n.readyAt));}
export function command(s,a,paid=[]){ensureLand(s);const now=s.last;switch(a.type){
 case'moveWorker':return moveWorker(s,workerCount(s),a.source,a.target);
 case'faction':if(!FACTIONS.some(f=>f.id===a.id))return'Choose a known faction.';s.faction=a.id;s.factionChosen=true;return null;
 case'gather':case'renew':return landCommand(s,a,workerCount(s)-assigned(s));
 case'build':{const b=BUILDINGS[a.building];if(!b||a.building==='keep')return'Choose a building.';if(!hasFeature(s,b.feature,paid))return'Gain more XP or unlock this feature in the Treasury.';if(!validCell(s,a.x,a.y))return'Choose an empty plot. Clear trees or mine deposits before building over them.';if(s.jobs.filter(j=>j.kind!=='train').length>=(hasFeature(s,'logistics',paid)?2:1))return'Your construction crew is busy.';if(!canPay(s,b.cost))return'Not enough resources.';pay(s,b.cost);s.nodes=s.nodes.filter(n=>n.x!==a.x||n.y!==a.y);s.jobs.push({id:s.nextId++,kind:'build',building:a.building,x:a.x,y:a.y,end:now+10000});return null;}
 case'upgrade':{const b=s.buildings.find(b=>b.id===a.id);if(!b)return'Choose a building.';if(b.level>=ageOf(s,paid).maxBuilding)return'Advance to the next age to upgrade further.';if(s.jobs.some(j=>j.target===b.id))return'Already upgrading.';if(s.jobs.filter(j=>j.kind!=='train').length>=(hasFeature(s,'logistics',paid)?2:1))return'Your construction crew is busy.';const cost=upgradeCost(b);if(!canPay(s,cost))return'Not enough resources.';pay(s,cost);s.jobs.push({id:s.nextId++,kind:'upgrade',target:b.id,end:now+15000*b.level});return null;}
 case'worker':{const b=s.buildings.find(b=>b.id===a.id);if(!b||BUILDINGS[b.type].resource!=='food')return'Assign workers directly to a tree or deposit on the land.';if(a.delta===1){if(assigned(s)>=workerCount(s))return'All workers are assigned. Move one from another building.';if(b.workers>=4)return'Four workers is the limit here.';b.workers++;}else if(a.delta===-1&&b.workers>0)b.workers--;return null;}
 case'train':{const u=UNITS[a.unit];if(!u)return'Unknown unit.';if(!hasFeature(s,u.feature,paid))return'This troop requires an XP or paid unlock.';if(!s.buildings.some(b=>b.type===u.building))return'Build a '+BUILDINGS[u.building].name+' first.';if(armyCount(s)>=population(s))return'Build cottages to increase your army capacity.';if(a.unit==='commander'&&(s.army.commander+s.jobs.filter(j=>j.unit==='commander').length)>=1)return'Only one commander may lead your army.';if(s.jobs.filter(j=>j.kind==='train').length>=5)return'Your recruitment queue is full.';if(!canPay(s,u.cost))return'Not enough resources.';pay(s,u.cost);s.jobs.push({id:s.nextId++,kind:'train',unit:a.unit,end:now+6000+s.jobs.filter(j=>j.kind==='train').length*2000});return null;}
 case'flag':if(s.flags.includes(a.id)){s.flag=a.id;return null;}return'You do not own that flag.';
 case'skin':if(s.skins.includes(a.id)){s.skin=a.id;return null;}return'You do not own that skin.';
 case'name':s.name=String(a.name||'Greenhaven').replace(/[<>\x00-\x1f]/g,'').trim().slice(0,22)||'Greenhaven';return null;
 default:return'Unknown command.';}}
export function tickTown(s,now=Date.now(),paid=[]){if(!Number.isFinite(now)||now<=s.last)return;ensureLand(s);const end=Math.min(now,s.last+2*3600*1000);let cursor=s.last;function gather(seconds){const ageBonus=ageOf(s,paid).production;harvestLand(s,seconds,cursor+seconds*1000,ageBonus,hasFeature(s,'logistics',paid));for(const b of s.buildings){const t=BUILDINGS[b.type];if(t.resource==='food'&&b.workers){const bonus=hasFeature(s,'logistics',paid)?1.25:1;const rate=t.rate*b.workers*(1+(b.level-1)*.35)*bonus*ageBonus;s.resources[t.resource]=Math.min(50000,s.resources[t.resource]+rate*seconds);}}}
 const jobs=[...s.jobs].sort((a,b)=>a.end-b.end);for(const j of jobs){if(j.end>end)continue;gather(Math.max(0,j.end-cursor)/1000);cursor=Math.max(cursor,j.end);if(j.kind==='build'){s.buildings.push({id:j.id,type:j.building,x:j.x,y:j.y,level:1,workers:0});s.xp+=15;s.log.unshift(BUILDINGS[j.building].name+' completed. Assign workers if needed.');}else if(j.kind==='upgrade'){const b=s.buildings.find(b=>b.id===j.target);if(b){b.level++;s.xp+=20;s.log.unshift(BUILDINGS[b.type].name+' upgraded to '+b.level+'.');}}else if(j.kind==='train'){s.army[j.unit]++;s.xp+=3;}s.jobs=s.jobs.filter(v=>v.id!==j.id);}gather(Math.max(0,end-cursor)/1000);s.last=now;s.log=s.log.slice(0,8);}
export function openEarnedChest(s,roll,pick=.5){if(s.chests<1)return null;if(!Number.isFinite(roll)||roll<0||roll>=1||!Number.isFinite(pick)||pick<0||pick>=1)return null;s.chests--;let edge=0;const loot=LOOT.find(i=>(edge+=i.weight)>roll*100);let result=loot.name;if(loot.id==='supplies'){for(const[k,n]of Object.entries({food:180,wood:180,stone:100,gold:100}))s.resources[k]+=n;}else if(loot.id==='standard'){const id=pick<.5?'lion':'raven';if(s.flags.includes(id)){s.resources.gold+=250;result='Duplicate standard → 250 gold';}else{s.flags.push(id);result=id==='lion'?'Golden Lion flag':'Night Raven flag';}}else if(loot.id==='court'){const id=pick<.5?'ivory':'obsidian';if(s.skins.includes(id)){s.resources.gold+=500;result='Duplicate skin → 500 gold';}else{s.skins.push(id);result=id==='ivory'?'Ivory citadel skin':'Obsidian court skin';}}else{if(hasFeature(s,'cavalry')){s.resources.gold+=800;result='Duplicate cavalry charter → 800 gold';}else s.unlocks.push('cavalry');}s.log.unshift(loot.rarity+': '+result);s.log=s.log.slice(0,8);return{rarity:loot.rarity,name:result};}
export function readTown(raw,now=Date.now()){try{const s=JSON.parse(raw);if(!s||s.version!==1||!Array.isArray(s.buildings)||s.buildings.length>81||!Array.isArray(s.jobs)||s.jobs.length>15)return newTown(now);if(!Number.isFinite(s.last)||!Number.isFinite(s.xp)||!s.resources||!s.army)return newTown(now);for(const k of resources)if(!Number.isFinite(s.resources[k])||s.resources[k]<0)return newTown(now);for(const k of Object.keys(UNITS))if(!Number.isInteger(s.army[k])||s.army[k]<0||s.army[k]>100)return newTown(now);if(!s.buildings.every(b=>BUILDINGS[b.type]&&Number.isInteger(b.x)&&Number.isInteger(b.y)&&b.x>=1&&b.x<=9&&b.y>=1&&b.y<=9&&Number.isInteger(b.level)&&b.level>=1&&b.level<=5&&Number.isInteger(b.workers)&&b.workers>=0&&b.workers<=4))return newTown(now);if(!s.jobs.every(j=>Number.isFinite(j.end)&&['build','upgrade','train'].includes(j.kind)&&(j.kind!=='build'||BUILDINGS[j.building])&&(j.kind!=='train'||UNITS[j.unit])))return newTown(now);for(const k of ['claimed','cleared','flags','skins','unlocks','log'])if(!Array.isArray(s[k]))return newTown(now);if(!s.settings)s.settings={sound:true,motion:true};s.name=String(s.name).slice(0,22);s.xp=clamp(s.xp,0,1000000);s.chests=clamp(Math.floor(s.chests)||0,0,1000);s.last=Math.min(s.last,now);s.faction=factionOf(s).id;s.factionChosen=!!s.factionChosen;ensureLand(s);if(s.nodes.length>81||!s.nodes.every(n=>['wood','pine','stone','gold'].includes(n.type)&&Number.isInteger(n.x)&&Number.isInteger(n.y)&&n.x>=1&&n.x<=9&&n.y>=1&&n.y<=9&&Number.isFinite(n.remaining)&&n.remaining>=0&&Number.isFinite(n.capacity)&&n.capacity>0&&n.remaining<=n.capacity&&Number.isInteger(n.workers)&&n.workers>=0&&n.workers<=3&&Number.isFinite(n.readyAt)))return newTown(now);return s;}catch{return newTown(now);}}
export function battleProfile(s,paid=[]){return{faction:factionOf(s).id,name:s.name,age:ageOf(s,paid).id,army:{...s.army},flag:s.flag,skin:s.skin,attack:hasFeature(s,'steel',paid)?1.15:1,health:hasFeature(s,'empire',paid)?1.2:1,fortress:ageOf(s,paid).fortress*(hasFeature(s,'masonry',paid)?1.15:1)*(1+.06*(s.buildings.find(b=>b.type==='keep').level-1)),defence:Math.min(8,s.buildings.reduce((n,b)=>n+(b.type==='tower'?b.level:b.type==='wall'?b.level*.4:0),0))};}
