export const DEFAULTS={sound:true,haptics:true,reduced:false,trail:'original',dot:'original',death:'original'};
export function loadPrefs(storage, reduced=false){try{return {...DEFAULTS,reduced,...JSON.parse(storage.getItem('theline.look.v1')||'{}')};}catch{return {...DEFAULTS,reduced};}}
export function validLook(prefs,unlocks){const allowed=new Set(unlocks.map(x=>x.unlock));for(const kind of ['trail','dot','death'])if(prefs[kind]!=='original'&&!allowed.has(prefs[kind]))prefs[kind]='original';return prefs;}
export function makeAudio(prefs){let audio;return function sound(kind){if(!prefs.sound)return;try{audio ||= new (window.AudioContext||window.webkitAudioContext)();audio.resume();const notes={start:[220,330,440],erase:[880,440,220],death:[160,75],unlock:[440,554,660,880],click:[480]}[kind]||[440];notes.forEach((f,i)=>{const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime+i*.055;o.type=kind==='death'?'triangle':'sine';o.frequency.setValueAtTime(f,t);o.frequency.exponentialRampToValueAtTime(Math.max(35,f*.72),t+.16);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.055,t+.006);g.gain.exponentialRampToValueAtTime(.001,t+.2);o.connect(g);g.connect(audio.destination);o.start(t);o.stop(t+.22);});}catch{}};}
export function backdrop(cx,w,h,scale,X,Y){cx.fillStyle='#080c15';cx.fillRect(0,0,w,h);const g=cx.createRadialGradient(w*.5,h*.45,0,w*.5,h*.45,h*.7);g.addColorStop(0,'#102031');g.addColorStop(1,'#080c15');cx.fillStyle=g;cx.fillRect(0,0,w,h);cx.strokeStyle='#53749313';cx.lineWidth=1;cx.beginPath();for(let x=-5;x<=5;x+=.5){cx.moveTo(X(x),0);cx.lineTo(X(x),h);}for(let y=-9;y<=9;y+=.5){cx.moveTo(0,Y(y));cx.lineTo(w,Y(y));}cx.stroke();}
export function runner(cx,run,{X,Y,scale,dpr,R,prefs,time}){const p=run.pts,color=prefs.trail==='trail-gold'?'#ffd16a':'#c6ff3d';cx.lineCap=cx.lineJoin='round';cx.beginPath();cx.moveTo(X(p[0]),Y(p[1]));for(let i=2;i<p.length;i+=2)cx.lineTo(X(p[i]),Y(p[i+1]));if(!run.over)cx.lineTo(X(run.x),Y(run.y));cx.strokeStyle=color;cx.lineWidth=7*dpr;cx.globalAlpha=.12;cx.stroke();cx.globalAlpha=1;cx.lineWidth=2.8*dpr;cx.shadowColor=color;cx.shadowBlur=(prefs.reduced?8:14)*dpr;
 if(prefs.trail==='trail-pulse'&&!prefs.reduced)cx.lineWidth=(2.5+Math.sin(time*5)*.6)*dpr;
 cx.stroke();if(prefs.trail==='trail-dashed'){cx.setLineDash([7*dpr,9*dpr]);cx.lineDashOffset=prefs.reduced?0:-time*14*dpr;cx.strokeStyle='#f5ffde';cx.lineWidth=1.5*dpr;cx.stroke();cx.setLineDash([]);}cx.shadowBlur=0;
 if(run.over)return;const x=X(run.x),y=Y(run.y),r=R*scale;cx.save();cx.translate(x,y);cx.rotate(-run.a);cx.shadowColor=color;cx.shadowBlur=20*dpr;cx.fillStyle='#f2ffd4';cx.strokeStyle=color;cx.lineWidth=2*dpr;
 if(prefs.dot==='dot-comet'){const tail=cx.createLinearGradient(-r*4,0,r,0);tail.addColorStop(0,'#c6ff3d00');tail.addColorStop(1,color);cx.fillStyle=tail;cx.beginPath();cx.moveTo(r,0);cx.lineTo(-r*4,-r*.65);cx.lineTo(-r*3,0);cx.lineTo(-r*4,r*.65);cx.closePath();cx.fill();cx.fillStyle='#fff';}
 if(prefs.dot==='dot-star'){cx.beginPath();for(let i=0;i<8;i++){const a=i*Math.PI/4,rr=i%2?r*.48:r*1.2;cx.lineTo(Math.cos(a)*rr,Math.sin(a)*rr);}cx.closePath();cx.fill();}else{cx.beginPath();cx.arc(0,0,r,0,Math.PI*2);cx.fill();if(prefs.dot==='dot-ring'){cx.beginPath();cx.arc(0,0,r*1.7,0,Math.PI*2);cx.stroke();}}
 cx.shadowBlur=0;cx.strokeStyle='#efffc766';cx.lineWidth=dpr;cx.beginPath();cx.arc(0,0,r*2.3,0,Math.PI*2);cx.stroke();cx.restore();}
